/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

 /*
 * CommonDRNote.java
 *
 * Created on Feb 27, 2012, 1:38:40 PM
 */
package com.nbs.view.F28.Payments;

import Sources.GLCodes;
import Sources.TableColumnRightAlign;
import com.nbs.impl.ServerConnection;
import com.nbs.view.common.FormatConstants;
import com.nbs.view.common.GeneralUserLogin;
import com.nbs.view.common.TableHeaders;
import com.nbs.view.common.search.FindAccount5Data;
import com.nbs.view.common.search.FindSectionOrOutsider;
import com.nbs.view.manager.CommonJurnalForm;
import java.awt.Color;
import java.awt.Component;
import java.awt.Dimension;
import java.awt.Font;
import java.rmi.RemoteException;
import java.sql.SQLException;
import java.text.ParseException;
import java.util.ArrayList;
import java.util.List;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JDialog;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author mmh
 */
public class CommonRuralBank9E extends javax.swing.JDialog {

    public static int DRSubSectionID;
    public static int DROutSiderID;
    public static int acctL5ID;
    public static int reasonID;
    private int glcode;
    DefaultTableModel dtm1;
    DefaultTableModel dtm2;
    private String hdID = "0";
    private JDialog dialog;

    public CommonRuralBank9E(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setTitle("Server on " + GeneralUserLogin.data.getIP());

        setLocationRelativeTo(null);
        this.dialog = this;
        statusUserName.setText(GeneralUserLogin.data.getUserCode() + "-" + GeneralUserLogin.data.getUsername());
        jdtTrnDate.setDate(GeneralUserLogin.data.getSystemDate());
        txtTotalCr1.setText("0.00");
        txtTotalDr1.setText("0.00");
        txtTotalCr2.setText("0.00");
        txtTotalDr2.setText("0.00");
        dtm2 = (DefaultTableModel) Table2.getModel();
        dtm1 = (DefaultTableModel) Table1.getModel();
        Table1.getTableHeader().setFont(new Font("Iskoola Pota", Font.PLAIN, 16));
        Table2.getTableHeader().setMaximumSize(new Dimension(jScrollPane2.getWidth(), 1));
        TableColumnRightAlign.alignMany(Table2, new int[]{1, 2, 3, 4});
        enableComponents(false);
    }

    public CommonRuralBank9E(java.awt.Frame parent, boolean b, int GLCode, String title) {
        this(parent, b);
    }

    public CommonRuralBank9E(java.awt.Frame parent, boolean b, int GLCode, String title, String hdid) {
        this(parent, b, GLCode, title);
        try {
            this.hdID = hdid;
            List<Object> inputs = new ArrayList<>();
            inputs.add(1);
            inputs.add(hdid);

            List<Object> outputs = ServerConnection.getServerConnector().searchSingleResult(inputs, "ssp_F28_LoadCombo_View9E_Edit", 12);
            txtNo2.setText(hdid);
            jdtTrnDate.setDate(FormatConstants.dateFormat.parse(String.valueOf(outputs.get(1))));
            txtBillNo.setText(String.valueOf(outputs.get(2)));
            txtSubSection.setId(Integer.parseInt(String.valueOf(outputs.get(3))));
            txtSubSection.setText(String.valueOf(outputs.get(4)));
            txtOutSider.setId(Integer.parseInt(String.valueOf(outputs.get(5))));
            txtOutSider.setText(String.valueOf(outputs.get(6)));
            txtF9ENo.setText(String.valueOf(outputs.get(11)));

            viewDT(hdid);
            getTotal();
            enableComponents(true);
        } catch (SQLException ex) {
            Logger.getLogger(CommonRuralBank9E.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(CommonRuralBank9E.class.getName()).log(Level.SEVERE, null, ex);
        } catch (RemoteException ex) {
            Logger.getLogger(CommonRuralBank9E.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ParseException ex) {
            Logger.getLogger(CommonRuralBank9E.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        lableName = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        txtBillNo = new javax.swing.JTextField();
        txtNo2 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtF9ENo = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtSubSection = new org.nbs.components.HiddenIDTextField();
        jLabel3 = new javax.swing.JLabel();
        txtOutSider = new org.nbs.components.HiddenIDTextField();
        jdtTrnDate = new com.toedter.calendar.JDateChooser();
        jScrollPane2 = new javax.swing.JScrollPane();
        Table2 = new org.jdesktop.swingx.JXTable();
        jPanel7 = new javax.swing.JPanel();
        btnNew = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        txtTotalCr1 = new org.nbs.components.SelectAtFocusFormattedTextField();
        txtTotalDr1 = new org.nbs.components.SelectAtFocusFormattedTextField();
        txtTotalDr2 = new org.nbs.components.SelectAtFocusFormattedTextField();
        txtTotalCr2 = new org.nbs.components.SelectAtFocusFormattedTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        Table1 = new org.jdesktop.swingx.JXTable();
        jPanel8 = new javax.swing.JPanel();
        txtDTLegderAccount = new org.nbs.components.HiddenIDTextField();
        txtDTDR = new org.nbs.components.HiddenIDTextField();
        txtDTCR = new org.nbs.components.HiddenIDTextField();
        txtDTJurnalCR = new org.nbs.components.HiddenIDTextField();
        txtDTJurnalDR = new org.nbs.components.HiddenIDTextField();
        jXStatusBar1 = new org.jdesktop.swingx.JXStatusBar();
        jLabel1 = new javax.swing.JLabel();
        statusGLCode = new javax.swing.JLabel();
        statusSubsection = new javax.swing.JLabel();
        statusOutsider = new javax.swing.JLabel();
        statusReason = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        statusUserName = new javax.swing.JLabel();
        statusHDID = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setAutoRequestFocus(false);
        setMinimumSize(new java.awt.Dimension(1285, 723));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jPanel1.setPreferredSize(new java.awt.Dimension(1380, 685));

        jPanel2.setBackground(new java.awt.Color(0, 88, 136));
        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        lableName.setFont(new java.awt.Font("Iskoola Pota", 0, 25)); // NOI18N
        lableName.setForeground(new java.awt.Color(255, 255, 255));
        lableName.setText("බැංකු අංශයේ මාසික වාර්තාව - 9E");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addComponent(lableName, javax.swing.GroupLayout.PREFERRED_SIZE, 392, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(lableName, javax.swing.GroupLayout.DEFAULT_SIZE, 52, Short.MAX_VALUE)
                .addGap(6, 6, 6))
        );

        jPanel3.setBackground(java.awt.Color.white);
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(37, 51, 224)), "විස්තරය", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Iskoola Pota", 0, 17), new java.awt.Color(222, 56, 21))); // NOI18N

        jLabel9.setFont(new java.awt.Font("Iskoola Pota", 1, 18)); // NOI18N
        jLabel9.setText("අංකය :");

        txtBillNo.setEditable(false);
        txtBillNo.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txtBillNo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        txtNo2.setEditable(false);
        txtNo2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txtNo2.setText("0");
        txtNo2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel4.setFont(new java.awt.Font("Iskoola Pota", 1, 18)); // NOI18N
        jLabel4.setText("දිනය");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel7.setText("F9E No :");

        txtF9ENo.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txtF9ENo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtF9ENo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtF9ENoFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtF9ENoFocusLost(evt);
            }
        });
        txtF9ENo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtF9ENoActionPerformed(evt);
            }
        });
        txtF9ENo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtF9ENoKeyReleased(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Iskoola Pota", 1, 18)); // NOI18N
        jLabel6.setText("අංශය");

        txtSubSection.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtSubSection.setFont(new java.awt.Font("AMALEE", 0, 18)); // NOI18N
        txtSubSection.setForeground(java.awt.Color.black);
        txtSubSection.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtSubSectionKeyTyped(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtSubSectionKeyReleased(evt);
            }
        });
        txtSubSection.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSubSectionActionPerformed(evt);
            }
        });
        txtSubSection.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtSubSectionFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtSubSectionFocusLost(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Iskoola Pota", 1, 18)); // NOI18N
        jLabel3.setText("නම");

        txtOutSider.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtOutSider.setFont(new java.awt.Font("AMALEE", 0, 18)); // NOI18N
        txtOutSider.setForeground(java.awt.Color.black);
        txtOutSider.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtOutSiderKeyTyped(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtOutSiderKeyReleased(evt);
            }
        });
        txtOutSider.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtOutSiderActionPerformed(evt);
            }
        });
        txtOutSider.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtOutSiderFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtOutSiderFocusLost(evt);
            }
        });

        jdtTrnDate.setDateFormatString("yyyy-MM-dd");
        jdtTrnDate.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtBillNo, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtNo2, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jdtTrnDate, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtF9ENo, javax.swing.GroupLayout.DEFAULT_SIZE, 142, Short.MAX_VALUE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtSubSection, javax.swing.GroupLayout.PREFERRED_SIZE, 394, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtOutSider, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtBillNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNo2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(1, 1, 1)
                        .addComponent(txtF9ENo, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(1, 1, 1)
                        .addComponent(txtOutSider, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addComponent(txtSubSection, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jdtTrnDate, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        Table2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "", "", "", "", "", "", "", "", ""
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true, true, true, true, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        Table2.setFont(new java.awt.Font("Iskoola Pota", 0, 15)); // NOI18N
        Table2.setRowHeight(25);
        Table2.getTableHeader().setReorderingAllowed(false);
        Table2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                Table2MouseReleased(evt);
            }
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Table2MouseClicked(evt);
            }
        });
        Table2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                Table2KeyReleased(evt);
            }
        });
        jScrollPane2.setViewportView(Table2);
        if (Table2.getColumnModel().getColumnCount() > 0) {
            Table2.getColumnModel().getColumn(0).setMinWidth(355);
            Table2.getColumnModel().getColumn(0).setPreferredWidth(355);
            Table2.getColumnModel().getColumn(0).setMaxWidth(355);
            Table2.getColumnModel().getColumn(1).setMinWidth(250);
            Table2.getColumnModel().getColumn(1).setPreferredWidth(250);
            Table2.getColumnModel().getColumn(1).setMaxWidth(250);
            Table2.getColumnModel().getColumn(2).setMinWidth(250);
            Table2.getColumnModel().getColumn(2).setPreferredWidth(250);
            Table2.getColumnModel().getColumn(2).setMaxWidth(250);
            Table2.getColumnModel().getColumn(3).setMinWidth(250);
            Table2.getColumnModel().getColumn(3).setPreferredWidth(250);
            Table2.getColumnModel().getColumn(3).setMaxWidth(250);
            Table2.getColumnModel().getColumn(4).setMinWidth(250);
            Table2.getColumnModel().getColumn(4).setPreferredWidth(250);
            Table2.getColumnModel().getColumn(4).setMaxWidth(250);
            Table2.getColumnModel().getColumn(5).setMinWidth(0);
            Table2.getColumnModel().getColumn(5).setPreferredWidth(0);
            Table2.getColumnModel().getColumn(5).setMaxWidth(0);
            Table2.getColumnModel().getColumn(6).setMinWidth(0);
            Table2.getColumnModel().getColumn(6).setPreferredWidth(0);
            Table2.getColumnModel().getColumn(6).setMaxWidth(0);
            Table2.getColumnModel().getColumn(7).setMinWidth(0);
            Table2.getColumnModel().getColumn(7).setPreferredWidth(0);
            Table2.getColumnModel().getColumn(7).setMaxWidth(0);
            Table2.getColumnModel().getColumn(8).setMinWidth(0);
            Table2.getColumnModel().getColumn(8).setPreferredWidth(0);
            Table2.getColumnModel().getColumn(8).setMaxWidth(0);
        }

        jPanel7.setBackground(new java.awt.Color(204, 204, 204));

        btnNew.setFont(new java.awt.Font("Iskoola Pota", 0, 18)); // NOI18N
        btnNew.setText("නිව්");
        btnNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewActionPerformed(evt);
            }
        });

        jButton5.setFont(new java.awt.Font("Iskoola Pota", 0, 18)); // NOI18N
        jButton5.setText("සේව්");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setFont(new java.awt.Font("Iskoola Pota", 0, 18)); // NOI18N
        jButton6.setText("වසන්න");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton8.setFont(new java.awt.Font("Iskoola Pota", 0, 18)); // NOI18N
        jButton8.setText("ස්ථීර");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel14.setText("Total");

        txtTotalCr1.setText("0.00");
        txtTotalCr1.setFont(new java.awt.Font("Ubuntu", 1, 17)); // NOI18N
        txtTotalCr1.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#,##0.00"))));
        txtTotalCr1.setHorizontalAlignment(11);

        txtTotalDr1.setText("0.00");
        txtTotalDr1.setFont(new java.awt.Font("Ubuntu", 1, 17)); // NOI18N
        txtTotalDr1.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#,##0.00"))));
        txtTotalDr1.setHorizontalAlignment(11);

        txtTotalDr2.setText("0.00");
        txtTotalDr2.setFont(new java.awt.Font("Ubuntu", 1, 17)); // NOI18N
        txtTotalDr2.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#,##0.00"))));
        txtTotalDr2.setHorizontalAlignment(11);

        txtTotalCr2.setText("0.00");
        txtTotalCr2.setFont(new java.awt.Font("Ubuntu", 1, 17)); // NOI18N
        txtTotalCr2.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#,##0.00"))));
        txtTotalCr2.setHorizontalAlignment(11);

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnNew, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtTotalDr1, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtTotalCr1, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtTotalDr2, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtTotalCr2, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(3, 3, 3)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnNew, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTotalCr1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTotalDr1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTotalDr2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTotalCr2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6))
        );

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);
        jScrollPane1.setViewportBorder(null);

        Table1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ලෙජර ගිණුම", "මුදල් හර", "මුදල් බැර", "පැවරුම් හර", "පැවරුම් බැර", "SubSectionID", "OutsiderID", "RecID", "AcctL5ID"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Double.class, java.lang.Double.class, java.lang.Double.class, java.lang.Double.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        Table1.setRowHeight(29);
        Table1.getTableHeader().setReorderingAllowed(false);
        Table1.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentMoved(java.awt.event.ComponentEvent evt) {
                Table1ComponentMoved(evt);
            }
        });
        Table1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                Table1KeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(Table1);
        if (Table1.getColumnModel().getColumnCount() > 0) {
            Table1.getColumnModel().getColumn(0).setMinWidth(355);
            Table1.getColumnModel().getColumn(0).setPreferredWidth(355);
            Table1.getColumnModel().getColumn(0).setMaxWidth(355);
            Table1.getColumnModel().getColumn(1).setMinWidth(250);
            Table1.getColumnModel().getColumn(1).setPreferredWidth(250);
            Table1.getColumnModel().getColumn(1).setMaxWidth(250);
            Table1.getColumnModel().getColumn(2).setMinWidth(250);
            Table1.getColumnModel().getColumn(2).setPreferredWidth(250);
            Table1.getColumnModel().getColumn(2).setMaxWidth(250);
            Table1.getColumnModel().getColumn(3).setMinWidth(250);
            Table1.getColumnModel().getColumn(3).setPreferredWidth(250);
            Table1.getColumnModel().getColumn(3).setMaxWidth(250);
            Table1.getColumnModel().getColumn(4).setMinWidth(250);
            Table1.getColumnModel().getColumn(4).setPreferredWidth(250);
            Table1.getColumnModel().getColumn(4).setMaxWidth(250);
            Table1.getColumnModel().getColumn(5).setMinWidth(0);
            Table1.getColumnModel().getColumn(5).setPreferredWidth(0);
            Table1.getColumnModel().getColumn(5).setMaxWidth(0);
            Table1.getColumnModel().getColumn(6).setMinWidth(0);
            Table1.getColumnModel().getColumn(6).setPreferredWidth(0);
            Table1.getColumnModel().getColumn(6).setMaxWidth(0);
            Table1.getColumnModel().getColumn(7).setMinWidth(0);
            Table1.getColumnModel().getColumn(7).setPreferredWidth(0);
            Table1.getColumnModel().getColumn(7).setMaxWidth(0);
            Table1.getColumnModel().getColumn(8).setMinWidth(0);
            Table1.getColumnModel().getColumn(8).setPreferredWidth(0);
            Table1.getColumnModel().getColumn(8).setMaxWidth(0);
        }

        jPanel8.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 2, 1, 1));

        txtDTLegderAccount.setBackground(new java.awt.Color(191, 214, 235));
        txtDTLegderAccount.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtDTLegderAccount.setFont(new java.awt.Font("Iskoola Pota", 0, 18)); // NOI18N
        txtDTLegderAccount.setMaximumSize(new java.awt.Dimension(355, 30));
        txtDTLegderAccount.setMinimumSize(new java.awt.Dimension(355, 30));
        txtDTLegderAccount.setPreferredSize(new java.awt.Dimension(355, 30));
        txtDTLegderAccount.setSize(new java.awt.Dimension(355, 30));
        txtDTLegderAccount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDTLegderAccountActionPerformed(evt);
            }
        });
        txtDTLegderAccount.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtDTLegderAccountFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtDTLegderAccountFocusLost(evt);
            }
        });

        txtDTDR.setText("0.00");
        txtDTDR.setBackground(new java.awt.Color(191, 214, 235));
        txtDTDR.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtDTDR.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        txtDTDR.setHorizontalAlignment(11);
        txtDTDR.setMaximumSize(new java.awt.Dimension(250, 30));
        txtDTDR.setMinimumSize(new java.awt.Dimension(250, 30));
        txtDTDR.setPreferredSize(new java.awt.Dimension(250, 30));
        txtDTDR.setSize(new java.awt.Dimension(250, 30));
        txtDTDR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDTDRActionPerformed(evt);
            }
        });
        txtDTDR.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtDTDRFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtDTDRFocusLost(evt);
            }
        });

        txtDTCR.setText("0.00");
        txtDTCR.setBackground(new java.awt.Color(191, 214, 235));
        txtDTCR.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtDTCR.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        txtDTCR.setHorizontalAlignment(11);
        txtDTCR.setMaximumSize(new java.awt.Dimension(250, 30));
        txtDTCR.setMinimumSize(new java.awt.Dimension(250, 30));
        txtDTCR.setPreferredSize(new java.awt.Dimension(250, 30));
        txtDTCR.setSize(new java.awt.Dimension(250, 30));
        txtDTCR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDTCRActionPerformed(evt);
            }
        });
        txtDTCR.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtDTCRFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtDTCRFocusLost(evt);
            }
        });

        txtDTJurnalCR.setText("0.00");
        txtDTJurnalCR.setBackground(new java.awt.Color(191, 214, 235));
        txtDTJurnalCR.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtDTJurnalCR.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        txtDTJurnalCR.setHorizontalAlignment(11);
        txtDTJurnalCR.setMaximumSize(new java.awt.Dimension(250, 30));
        txtDTJurnalCR.setMinimumSize(new java.awt.Dimension(250, 30));
        txtDTJurnalCR.setPreferredSize(new java.awt.Dimension(250, 30));
        txtDTJurnalCR.setSize(new java.awt.Dimension(250, 30));
        txtDTJurnalCR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDTJurnalCRActionPerformed(evt);
            }
        });
        txtDTJurnalCR.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtDTJurnalCRFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtDTJurnalCRFocusLost(evt);
            }
        });

        txtDTJurnalDR.setText("0.00");
        txtDTJurnalDR.setBackground(new java.awt.Color(191, 214, 235));
        txtDTJurnalDR.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtDTJurnalDR.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        txtDTJurnalDR.setHorizontalAlignment(11);
        txtDTJurnalDR.setMaximumSize(new java.awt.Dimension(250, 30));
        txtDTJurnalDR.setMinimumSize(new java.awt.Dimension(250, 30));
        txtDTJurnalDR.setPreferredSize(new java.awt.Dimension(250, 30));
        txtDTJurnalDR.setSize(new java.awt.Dimension(250, 30));
        txtDTJurnalDR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDTJurnalDRActionPerformed(evt);
            }
        });
        txtDTJurnalDR.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtDTJurnalDRFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtDTJurnalDRFocusLost(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addComponent(txtDTLegderAccount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(txtDTDR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(txtDTCR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(txtDTJurnalCR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(txtDTJurnalDR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtDTLegderAccount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDTDR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDTCR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDTJurnalCR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDTJurnalDR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jPanel8, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 348, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        javax.swing.GroupLayout jXStatusBar1Layout = new javax.swing.GroupLayout(jXStatusBar1);
        jXStatusBar1.setLayout(jXStatusBar1Layout);
        jXStatusBar1Layout.setHorizontalGroup(
            jXStatusBar1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jXStatusBar1Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(statusHDID, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(statusGLCode, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(statusSubsection, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(statusOutsider, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(statusReason, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(588, 588, 588)
                .addComponent(statusUserName, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jXStatusBar1Layout.setVerticalGroup(
            jXStatusBar1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jXStatusBar1Layout.createSequentialGroup()
                .addGroup(jXStatusBar1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(statusGLCode, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(statusSubsection, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(statusOutsider, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(statusReason, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(statusUserName, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(statusHDID, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jXStatusBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1382, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(1, 1, 1)
                .addComponent(jXStatusBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
    this.dispose();
    CommonJurnalForm.ItemRefresh.doClick();
}//GEN-LAST:event_jButton6ActionPerformed

private void Table2MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Table2MouseReleased

}//GEN-LAST:event_Table2MouseReleased

private void btnNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewActionPerformed
    enableComponents(true);
    saveHeader();
}//GEN-LAST:event_btnNewActionPerformed

private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
    saveHeader();
    saveDetail();
    CommonJurnalForm.ItemRefresh.doClick();
}//GEN-LAST:event_jButton5ActionPerformed

private void Table2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Table2MouseClicked
    if (Table2.getSelectedRow() > -1) {
        int selectedRow = Table2.getSelectedRow();
        txtDTLegderAccount.setText(String.valueOf(Table2.getValueAt(selectedRow, 0)));
        txtDTDR.setText(String.valueOf(Table2.getValueAt(selectedRow, 1)));
        txtDTCR.setText(String.valueOf(Table2.getValueAt(selectedRow, 2)));
        txtDTJurnalDR.setText(String.valueOf(Table2.getValueAt(selectedRow, 3)));
        txtDTJurnalCR.setText(String.valueOf(Table2.getValueAt(selectedRow, 4)));
        txtDTLegderAccount.setId(Integer.parseInt(String.valueOf(Table2.getValueAt(selectedRow, 8))));
        dtid = Integer.parseInt(String.valueOf(Table2.getValueAt(selectedRow, 7)));
    }
}//GEN-LAST:event_Table2MouseClicked

private void Table2KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Table2KeyReleased

}//GEN-LAST:event_Table2KeyReleased

private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
    CommonJurnalForm.ItemRefresh.doClick();
}//GEN-LAST:event_jButton8ActionPerformed

    private void Table1ComponentMoved(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_Table1ComponentMoved
        jScrollPane2.getViewport().setViewPosition(jScrollPane1.getViewport().getViewPosition());
    }//GEN-LAST:event_Table1ComponentMoved

    private void Table1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Table1KeyReleased

    }//GEN-LAST:event_Table1KeyReleased

    private void txtDTLegderAccountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDTLegderAccountActionPerformed
        new FindAccount5Data(this, true, 7).setVisible(true);
    }//GEN-LAST:event_txtDTLegderAccountActionPerformed

    private void txtDTDRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDTDRActionPerformed
        txtDTCR.grabFocus();
    }//GEN-LAST:event_txtDTDRActionPerformed

    private void txtDTCRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDTCRActionPerformed
        txtDTJurnalCR.grabFocus();
    }//GEN-LAST:event_txtDTCRActionPerformed

    private void txtDTLegderAccountFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtDTLegderAccountFocusGained
        txtDTLegderAccount.selectAll();
        txtDTLegderAccount.setBackground(Color.YELLOW);
        if (txtOutSider.getId() == 0) {
            JOptionPane.showMessageDialog(this, "කරුණාකර නම ඇතුලත් කරන්න", "කරුණාකර නම ඇතුලත් කරන්න", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_txtDTLegderAccountFocusGained

    private void txtDTLegderAccountFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtDTLegderAccountFocusLost
        txtDTLegderAccount.select(0, 0);
        txtDTLegderAccount.setBackground(new Color(191, 214, 235));
    }//GEN-LAST:event_txtDTLegderAccountFocusLost

    private void txtDTDRFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtDTDRFocusGained
        txtDTDR.selectAll();
        txtDTDR.setBackground(Color.YELLOW);
        if (txtDTDR.getText().trim().isEmpty()) {
            txtDTDR.setText("0.00");
        }
    }//GEN-LAST:event_txtDTDRFocusGained

    private void txtDTDRFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtDTDRFocusLost
        txtDTDR.select(0, 0);
        txtDTDR.setBackground(new Color(191, 214, 235));
        if (txtDTDR.getText().trim().isEmpty()) {
            txtDTDR.setText("0.00");
        }
    }//GEN-LAST:event_txtDTDRFocusLost

    private void txtDTCRFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtDTCRFocusGained
        txtDTCR.selectAll();
        txtDTCR.setBackground(Color.YELLOW);
        if (txtDTCR.getText().trim().isEmpty()) {
            txtDTCR.setText("0.00");
        }
    }//GEN-LAST:event_txtDTCRFocusGained

    private void txtDTCRFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtDTCRFocusLost
        txtDTCR.select(0, 0);
        txtDTCR.setBackground(new Color(191, 214, 235));
        if (txtDTCR.getText().trim().isEmpty()) {
            txtDTCR.setText("0.00");
        }
    }//GEN-LAST:event_txtDTCRFocusLost

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        CommonJurnalForm.ItemRefresh.doClick();
    }//GEN-LAST:event_formWindowClosing

    private void txtF9ENoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtF9ENoFocusGained
        txtF9ENo.setBackground(Color.YELLOW);

    }//GEN-LAST:event_txtF9ENoFocusGained

    private void txtF9ENoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtF9ENoFocusLost
        txtF9ENo.setBackground(Color.WHITE);
    }//GEN-LAST:event_txtF9ENoFocusLost

    private void txtF9ENoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtF9ENoActionPerformed
        txtSubSection.grabFocus();
    }//GEN-LAST:event_txtF9ENoActionPerformed

    private void txtF9ENoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtF9ENoKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtF9ENoKeyReleased

    private void txtSubSectionKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSubSectionKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSubSectionKeyTyped

    private void txtSubSectionKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSubSectionKeyReleased

    }//GEN-LAST:event_txtSubSectionKeyReleased

    private void txtSubSectionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSubSectionActionPerformed
        new FindSectionOrOutsider(this, true, TableHeaders.SUBSECTIONFINDER_TABLE_MODEL, TableHeaders.SUBSECTIONFINDER_TABLE_MODEL2, 31, "අනු අංශය").setVisible(true);
    }//GEN-LAST:event_txtSubSectionActionPerformed

    private void txtSubSectionFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtSubSectionFocusGained
        txtSubSection.setBackground(Color.YELLOW);
        if (txtF9ENo.getText().trim().equals("")) {
            JOptionPane.showMessageDialog(this, "කරුණාකර 9E අංකය ඇතුලත් කරන්න", "කරුණාකර 9E අංකය ඇතුලත් කරන්න", JOptionPane.ERROR_MESSAGE);
            txtF9ENo.grabFocus();
        }
    }//GEN-LAST:event_txtSubSectionFocusGained

    private void txtSubSectionFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtSubSectionFocusLost
        txtSubSection.setBackground(Color.WHITE);
    }//GEN-LAST:event_txtSubSectionFocusLost

    private void txtOutSiderKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtOutSiderKeyTyped

    }//GEN-LAST:event_txtOutSiderKeyTyped

    private void txtOutSiderKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtOutSiderKeyReleased

    }//GEN-LAST:event_txtOutSiderKeyReleased

    private void txtOutSiderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtOutSiderActionPerformed
        new FindSectionOrOutsider(this, true, TableHeaders.OUTSIDERFINDER_TABLE_MODEL, TableHeaders.OUTSIDERFINDER_TABLE_MODEL2, 32, "පාර්ශවකරු").setVisible(true);
    }//GEN-LAST:event_txtOutSiderActionPerformed

    private void txtOutSiderFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtOutSiderFocusGained
        txtOutSider.setBackground(Color.YELLOW);
        if (txtSubSection.getId() == 0) {
            JOptionPane.showMessageDialog(this, "කරුණාකර අංශය ඇතුලත් කරන්න", "කරුණාකර අංශය ඇතුලත් කරන්න", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_txtOutSiderFocusGained

    private void txtOutSiderFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtOutSiderFocusLost
        txtOutSider.setBackground(Color.WHITE);
    }//GEN-LAST:event_txtOutSiderFocusLost

    private void txtDTJurnalCRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDTJurnalCRActionPerformed
        txtDTJurnalDR.grabFocus();
    }//GEN-LAST:event_txtDTJurnalCRActionPerformed

    private void txtDTJurnalCRFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtDTJurnalCRFocusGained
        txtDTJurnalCR.selectAll();
        txtDTJurnalCR.setBackground(Color.YELLOW);
        if (txtDTJurnalCR.getText().trim().isEmpty()) {
            txtDTJurnalCR.setText("0.00");
        }
    }//GEN-LAST:event_txtDTJurnalCRFocusGained

    private void txtDTJurnalCRFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtDTJurnalCRFocusLost
        txtDTJurnalCR.select(0, 0);
        txtDTJurnalCR.setBackground(new Color(191, 214, 235));
        if (txtDTJurnalCR.getText().trim().isEmpty()) {
            txtDTJurnalCR.setText("0.00");
        }
    }//GEN-LAST:event_txtDTJurnalCRFocusLost

    private void txtDTJurnalDRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDTJurnalDRActionPerformed
        saveDetail();
        saveHeader();
        viewDT(hdID);
        getTotal();
        txtDTCR.setText("0.00");
        txtDTDR.setText("0.00");
        txtDTJurnalCR.setText("0.00");
        txtDTJurnalDR.setText("0.00");
        txtDTLegderAccount.setText("");
        txtDTLegderAccount.setId(0);
        dtid = 0;
        txtDTLegderAccount.grabFocus();
    }//GEN-LAST:event_txtDTJurnalDRActionPerformed

    private void txtDTJurnalDRFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtDTJurnalDRFocusGained
        txtDTJurnalDR.selectAll();
        txtDTJurnalDR.setBackground(Color.YELLOW);
        if (txtDTJurnalDR.getText().trim().isEmpty()) {
            txtDTJurnalDR.setText("0.00");
        }
    }//GEN-LAST:event_txtDTJurnalDRFocusGained

    private void txtDTJurnalDRFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtDTJurnalDRFocusLost
        txtDTJurnalDR.select(0, 0);
        txtDTJurnalDR.setBackground(new Color(191, 214, 235));
        if (txtDTJurnalDR.getText().trim().isEmpty()) {
            txtDTJurnalDR.setText("0.00");
        }
    }//GEN-LAST:event_txtDTJurnalDRFocusLost

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CommonRuralBank9E.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CommonRuralBank9E.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CommonRuralBank9E.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CommonRuralBank9E.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>


        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {

                CommonRuralBank9E dialog = new CommonRuralBank9E(new javax.swing.JFrame(), true);
                dialog.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static org.jdesktop.swingx.JXTable Table1;
    private org.jdesktop.swingx.JXTable Table2;
    private javax.swing.JButton btnNew;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    public static javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private org.jdesktop.swingx.JXStatusBar jXStatusBar1;
    private com.toedter.calendar.JDateChooser jdtTrnDate;
    private javax.swing.JLabel lableName;
    private javax.swing.JLabel statusGLCode;
    private javax.swing.JLabel statusHDID;
    public static javax.swing.JLabel statusOutsider;
    public static javax.swing.JLabel statusReason;
    public static javax.swing.JLabel statusSubsection;
    private javax.swing.JLabel statusUserName;
    private javax.swing.JTextField txtBillNo;
    public static org.nbs.components.HiddenIDTextField txtDTCR;
    public static org.nbs.components.HiddenIDTextField txtDTDR;
    public static org.nbs.components.HiddenIDTextField txtDTJurnalCR;
    public static org.nbs.components.HiddenIDTextField txtDTJurnalDR;
    public static org.nbs.components.HiddenIDTextField txtDTLegderAccount;
    private javax.swing.JTextField txtF9ENo;
    private javax.swing.JTextField txtNo2;
    public static org.nbs.components.HiddenIDTextField txtOutSider;
    public static org.nbs.components.HiddenIDTextField txtSubSection;
    private org.nbs.components.SelectAtFocusFormattedTextField txtTotalCr1;
    private org.nbs.components.SelectAtFocusFormattedTextField txtTotalCr2;
    private org.nbs.components.SelectAtFocusFormattedTextField txtTotalDr1;
    private org.nbs.components.SelectAtFocusFormattedTextField txtTotalDr2;
    // End of variables declaration//GEN-END:variables

    private void saveHeader() {
        try {
            System.out.println(hdID);
            List<Object> inputs = new ArrayList<>();
            inputs.add(hdID);
            inputs.add(FormatConstants.dateFormat.format(jdtTrnDate.getDate()));
            inputs.add(txtBillNo.getText());
            inputs.add(txtF9ENo.getText());
            inputs.add(txtSubSection.getId());
            inputs.add(GLCodes.RURALBANK9E);
            inputs.add(txtOutSider.getId());
            inputs.add(1);
            inputs.add("");
            double dr1 = FormatConstants.decimalFormat.parse(txtTotalDr1.getText()).doubleValue();
            double dr2 = FormatConstants.decimalFormat.parse(txtTotalDr2.getText()).doubleValue();
            double dr = dr1 + dr2;
            inputs.add(dr);
            double cr1 = FormatConstants.numberFormat1.parse(txtTotalCr1.getText()).doubleValue();
            double cr2 = FormatConstants.numberFormat1.parse(txtTotalCr2.getText()).doubleValue();
            double cr = cr1 + cr2;
            inputs.add(cr);
            inputs.add("");
            inputs.add(GeneralUserLogin.data.getUsername());
            inputs.add("@recID");
            inputs.add("@BillNo");

            List<Object> outputs = ServerConnection.getServerConnector().insertData(inputs, "ssp_F28_Insert_Other9EHD", 2);
            hdID = String.valueOf(outputs.get(0));
            txtNo2.setText(hdID);
            txtBillNo.setText(String.valueOf(outputs.get(1)));
        } catch (RemoteException ex) {
            Logger.getLogger(CommonRuralBank9E.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(CommonRuralBank9E.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(CommonRuralBank9E.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ParseException ex) {
            Logger.getLogger(CommonRuralBank9E.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    private int dtid = 0;

    private void saveDetail() {
        try {
            List<Object> inputs = new ArrayList<>();
            System.out.println("dt " + dtid);
            inputs.add(dtid);
            inputs.add(txtNo2.getText());
            inputs.add(txtSubSection.getId());
            inputs.add(txtOutSider.getId());
            inputs.add(GLCodes.RURALBANK9E);
            inputs.add(15);
            inputs.add("");
            inputs.add("");
            inputs.add(txtDTLegderAccount.getId());
            inputs.add(txtDTLegderAccount.getText());
            inputs.add(0);
            inputs.add(FormatConstants.numberFormat1.parse(txtDTDR.getText()));
            inputs.add(FormatConstants.numberFormat1.parse(txtDTCR.getText()));
            inputs.add(FormatConstants.numberFormat1.parse(txtDTJurnalDR.getText()));
            inputs.add(FormatConstants.numberFormat1.parse(txtDTJurnalCR.getText()));
            inputs.add(GeneralUserLogin.data.getUsername());

            ServerConnection.getServerConnector().insertData(inputs, "ssp_F28_Insert_Other9EDT", 0);
        } catch (SQLException ex) {
            Logger.getLogger(CommonRuralBank9E.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(CommonRuralBank9E.class.getName()).log(Level.SEVERE, null, ex);
        } catch (RemoteException ex) {
            Logger.getLogger(CommonRuralBank9E.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ParseException ex) {
            Logger.getLogger(CommonRuralBank9E.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void viewDT(String hdID) {
        try {
            dtm2.setRowCount(0);
            List<Object> inputs = new ArrayList<>();
            inputs.add(2);
            inputs.add(hdID);
            List<List<Object>> outputs = ServerConnection.getServerConnector().searchMultipleResults(inputs, "ssp_F28_LoadCombo_View9E_Edit", 9);
            for (List<Object> output : outputs) {
                Vector v = new Vector();
                for (Object object : output) {
                    v.add(object);
                }
                dtm2.addRow(v);
            }
        } catch (SQLException ex) {
            Logger.getLogger(CommonRuralBank9E.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(CommonRuralBank9E.class.getName()).log(Level.SEVERE, null, ex);
        } catch (RemoteException ex) {
            Logger.getLogger(CommonRuralBank9E.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void getTotal() {
        double totalDR = 0;
        double totalCR = 0;
        double totalDR2 = 0;
        double totalCR2 = 0;
        for (int i = 0; i < Table2.getRowCount(); i++) {
            try {
                totalDR += FormatConstants.numberFormat1.parse(String.valueOf(Table2.getValueAt(i, 1))).doubleValue();
                totalCR += FormatConstants.numberFormat1.parse(String.valueOf(Table2.getValueAt(i, 2))).doubleValue();
                totalDR2 += FormatConstants.numberFormat1.parse(String.valueOf(Table2.getValueAt(i, 3))).doubleValue();
                totalCR2 += FormatConstants.numberFormat1.parse(String.valueOf(Table2.getValueAt(i, 4))).doubleValue();
            } catch (ParseException ex) {
                Logger.getLogger(CommonRuralBank9E.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        txtTotalDr1.setText(FormatConstants.decimalFormat.format(totalDR));
        txtTotalCr1.setText(FormatConstants.decimalFormat.format(totalCR));
        txtTotalDr2.setText(FormatConstants.decimalFormat.format(totalDR2));
        txtTotalCr2.setText(FormatConstants.decimalFormat.format(totalCR2));
    }

    private void initRowData() {

    }

    private void enableComponents(boolean enable) {
        Component components[] = {txtDTCR, txtDTDR, txtDTLegderAccount, txtF9ENo, txtOutSider, txtSubSection, txtDTJurnalCR, txtDTJurnalDR};
        for (Component component : components) {
            component.setEnabled(enable);
        }
    }

}
