/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.nbs.view.F28.Stock;

import Sources.GLCodes;
import com.nbs.impl.ServerConnection;
import com.nbs.view.common.FormatConstants;
import com.nbs.view.common.GeneralUserLogin;
import com.nbs.view.common.TableHeaders;
import com.nbs.view.common.search.FindSectionOrOutsider;
import com.nbs.view.manager.CommonJurnalForm;
import java.awt.Dialog;
import java.awt.event.KeyEvent;
import java.rmi.RemoteException;
import java.sql.SQLException;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Bhanuka Krish
 */
public class AB16StoresBuyings extends javax.swing.JFrame {

    private String code;
    private DateFormat df;
    private String id;
    private String status;

    /**
     * Creates new form fram
     */
    public AB16StoresBuyings() {
        initComponents();
        setTitle("Server on " + GeneralUserLogin.data.getIP());

        df = new SimpleDateFormat("yyyy-MM-dd");
        jdt16BDate.setDate(GeneralUserLogin.data.getSystemDate());
        jdt14CDate.setDate(GeneralUserLogin.data.getSystemDate());
        txtSection.grabFocus();
        setModalExclusionType(Dialog.ModalExclusionType.APPLICATION_EXCLUDE);
        btnApprove.setVisible(false);
        userName.setText(GeneralUserLogin.data.getUserCode() + " - " + GeneralUserLogin.data.getUsername());
    }

    public AB16StoresBuyings(String code) {
        this();
        this.code = code;
        if (this.code.equals("01-02")) {
            statusglCode.setText(GLCodes.AB16CASHPURCHASE + "");
            jLabel1.setText("16 ඒ / බී අනුමත ගැනුම්");
            jLabel8.setText("බිල් අංකය");
            jLabel7.setEnabled(false);
            txtStores.setEnabled(false);
            jButton7.setEnabled(false);
        } else if (this.code.equals("01-04")) {
            statusglCode.setText(GLCodes.AB16STORESRECEIVINGS + "");
        }

    }

    public AB16StoresBuyings(String code, List dataArray) {
        this(code);
    }

    public AB16StoresBuyings(String code, String id) {
        this(code);
        try {
            this.id = id;
            List<Object> inputs = new ArrayList<>();
            inputs.add(id);
            List<Object> outputs = ServerConnection.getServerConnector().searchSingleResult(inputs, "ssp_F28_LoadCombo_ViewStock_16B_Edit_StkTrn", 16);
            txtNumber.setText(String.valueOf(outputs.get(0)));
            statusglCode.setText(String.valueOf(outputs.get(1)));
            txtSection.setId(Integer.parseInt(String.valueOf(outputs.get(2))));
            txtSection.setText(String.valueOf(outputs.get(3)));
            txtStores.setId(Integer.parseInt(String.valueOf(outputs.get(4))));
            txtStores.setText(String.valueOf(outputs.get(5)));
            txtSupplier.setId(Integer.parseInt(String.valueOf(outputs.get(6))));
            txtSupplier.setText(String.valueOf(outputs.get(7)));
            status = String.valueOf(outputs.get(8));

            jdt16BDate.setDate(FormatConstants.dateFormat.parse(String.valueOf(outputs.get(9))));
            txt16Number.setText(String.valueOf(outputs.get(10)));
            txtBillNumber.setText(String.valueOf(outputs.get(11)));
            jdt14CDate.setDate(FormatConstants.dateFormat.parse(String.valueOf(outputs.get(12))));
            txtStoresValue.setText(String.valueOf(outputs.get(13)));
            txtBillValueForSales.setText(String.valueOf(outputs.get(14)));
            btnApprove.setText(String.valueOf(outputs.get(15)));
            btnApprove.setVisible(true);
            btnNew.setEnabled(false);
            btnSave.setEnabled(true);
            if (/*status.equals("2") ||*/status.equals("11")) {
                btnSave.setEnabled(false);
                btnApprove.setEnabled(false);
            }
        } catch (SQLException ex) {
            Logger.getLogger(AB16StoresBuyings.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(AB16StoresBuyings.class.getName()).log(Level.SEVERE, null, ex);
        } catch (RemoteException ex) {
            Logger.getLogger(AB16StoresBuyings.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ParseException ex) {
            Logger.getLogger(AB16StoresBuyings.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        confirmDialog = new javax.swing.JDialog();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtBillNumber = new javax.swing.JTextField();
        txtNumber = new javax.swing.JTextField();
        txtStores = new org.nbs.components.HiddenIDTextField();
        jLabel13 = new javax.swing.JLabel();
        txtSupplier = new org.nbs.components.HiddenIDTextField();
        txt16Number = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jdt14CDate = new com.toedter.calendar.JDateChooser();
        jdt16BDate = new com.toedter.calendar.JDateChooser();
        jLabel12 = new javax.swing.JLabel();
        txtSection = new org.nbs.components.HiddenIDTextField();
        jLabel20 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        btnSave = new javax.swing.JButton();
        btnApprove = new javax.swing.JButton();
        btnNew = new javax.swing.JButton();
        jLabel26 = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();
        txtStoresValue = new javax.swing.JFormattedTextField();
        txtBillValueForSales = new javax.swing.JFormattedTextField();
        txtCreditPeriod = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButton7 = new javax.swing.JButton();
        jLabel25 = new javax.swing.JLabel();
        jXStatusBar1 = new org.jdesktop.swingx.JXStatusBar();
        statusglCode = new javax.swing.JLabel();
        userName = new javax.swing.JLabel();
        statusglCode1 = new javax.swing.JLabel();

        javax.swing.GroupLayout confirmDialogLayout = new javax.swing.GroupLayout(confirmDialog.getContentPane());
        confirmDialog.getContentPane().setLayout(confirmDialogLayout);
        confirmDialogLayout.setHorizontalGroup(
            confirmDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 416, Short.MAX_VALUE)
        );
        confirmDialogLayout.setVerticalGroup(
            confirmDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 200, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setAlwaysOnTop(true);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 81, 136));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Iskoola Pota", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("16 ඒ / බී ගබඩා ගැනුම්");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(599, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jButton5.setText("...");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 139, 50, 30));

        jLabel3.setFont(new java.awt.Font("Iskoola Pota", 0, 15)); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 230, -1, -1));

        jLabel5.setFont(new java.awt.Font("Iskoola Pota", 0, 16)); // NOI18N
        jLabel5.setText("අංකය ");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, -1, 25));

        jLabel6.setFont(new java.awt.Font("Iskoola Pota", 0, 16)); // NOI18N
        jLabel6.setText("අංශය");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, -1, 25));

        jLabel7.setFont(new java.awt.Font("Iskoola Pota", 0, 16)); // NOI18N
        jLabel7.setText("ගබඩාව");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, -1, 25));

        jLabel8.setFont(new java.awt.Font("Iskoola Pota", 0, 16)); // NOI18N
        jLabel8.setText("14C අංකය");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 260, -1, 25));

        txtBillNumber.setFont(new java.awt.Font("Tahoma", 1, 17)); // NOI18N
        txtBillNumber.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(1, 1, 1)));
        txtBillNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBillNumberActionPerformed(evt);
            }
        });
        getContentPane().add(txtBillNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 260, 180, 26));

        txtNumber.setEditable(false);
        txtNumber.setFont(new java.awt.Font("Tahoma", 1, 17)); // NOI18N
        txtNumber.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        txtNumber.setText("0");
        txtNumber.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(1, 1, 1)));
        txtNumber.setEnabled(false);
        txtNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNumberActionPerformed(evt);
            }
        });
        getContentPane().add(txtNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 110, 180, 26));

        txtStores.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(1, 1, 1)));
        txtStores.setFont(new java.awt.Font("AMALEE", 1, 17)); // NOI18N
        txtStores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtStoresActionPerformed(evt);
            }
        });
        getContentPane().add(txtStores, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 170, 660, 26));

        jLabel13.setFont(new java.awt.Font("Iskoola Pota", 0, 16)); // NOI18N
        jLabel13.setText("සැපැයුම්කරු");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 200, -1, 25));

        txtSupplier.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(1, 1, 1)));
        txtSupplier.setFont(new java.awt.Font("AMALEE", 1, 17)); // NOI18N
        txtSupplier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSupplierActionPerformed(evt);
            }
        });
        getContentPane().add(txtSupplier, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 200, 660, 26));

        txt16Number.setFont(new java.awt.Font("Tahoma", 1, 17)); // NOI18N
        txt16Number.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(1, 1, 1)));
        txt16Number.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt16NumberActionPerformed(evt);
            }
        });
        getContentPane().add(txt16Number, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 230, 180, 26));

        jLabel9.setFont(new java.awt.Font("Iskoola Pota", 0, 16)); // NOI18N
        jLabel9.setText("16 අංකය");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 230, -1, 25));

        jLabel10.setFont(new java.awt.Font("Iskoola Pota", 0, 16)); // NOI18N
        jLabel10.setText("ණය සිමාව");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 260, -1, 25));

        jLabel11.setFont(new java.awt.Font("Iskoola Pota", 0, 16)); // NOI18N
        jLabel11.setText("දිනය");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 230, -1, 25));

        jdt14CDate.setDateFormatString("yyyy-MM-dd");
        jdt14CDate.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        getContentPane().add(jdt14CDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 260, 220, 25));

        jdt16BDate.setDateFormatString("yyyy-MM-dd");
        jdt16BDate.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        getContentPane().add(jdt16BDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 230, 220, 25));

        jLabel12.setFont(new java.awt.Font("Iskoola Pota", 0, 16)); // NOI18N
        jLabel12.setText("14C දිනය ");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 260, -1, 25));

        txtSection.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(1, 1, 1)));
        txtSection.setFont(new java.awt.Font("AMALEE", 1, 17)); // NOI18N
        txtSection.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSectionActionPerformed(evt);
            }
        });
        getContentPane().add(txtSection, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 140, 660, 26));

        jLabel20.setFont(new java.awt.Font("Iskoola Pota", 0, 16)); // NOI18N
        jLabel20.setText("වටිනාකම");
        getContentPane().add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 370, -1, 25));

        jLabel23.setFont(new java.awt.Font("Iskoola Pota", 0, 16)); // NOI18N
        jLabel23.setText("වටිනාකම");
        getContentPane().add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 370, -1, 25));

        btnSave.setFont(new java.awt.Font("Iskoola Pota", 0, 18)); // NOI18N
        btnSave.setText("සේව්");
        btnSave.setEnabled(false);
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });
        btnSave.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                btnSaveKeyReleased(evt);
            }
        });
        getContentPane().add(btnSave, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 450, 160, 35));

        btnApprove.setFont(new java.awt.Font("Iskoola Pota", 0, 18)); // NOI18N
        btnApprove.setText("අනුමත කරන්න");
        btnApprove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnApproveActionPerformed(evt);
            }
        });
        getContentPane().add(btnApprove, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 450, 310, 35));

        btnNew.setFont(new java.awt.Font("Iskoola Pota", 0, 18)); // NOI18N
        btnNew.setText("නව");
        btnNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewActionPerformed(evt);
            }
        });
        getContentPane().add(btnNew, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 450, 140, 35));

        jLabel26.setBackground(new java.awt.Color(204, 204, 204));
        jLabel26.setOpaque(true);
        getContentPane().add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 440, 840, 50));

        jButton6.setText("...");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 200, 50, -1));

        txtStoresValue.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtStoresValue.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#,##0.00"))));
        txtStoresValue.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        txtStoresValue.setText("0.00");
        txtStoresValue.setFont(new java.awt.Font("Ubuntu", 1, 17)); // NOI18N
        txtStoresValue.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtStoresValueFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtStoresValueFocusLost(evt);
            }
        });
        txtStoresValue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtStoresValueActionPerformed(evt);
            }
        });
        getContentPane().add(txtStoresValue, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 370, 230, 26));

        txtBillValueForSales.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtBillValueForSales.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#,##0.00"))));
        txtBillValueForSales.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        txtBillValueForSales.setText("0.00");
        txtBillValueForSales.setFont(new java.awt.Font("Ubuntu", 1, 17)); // NOI18N
        txtBillValueForSales.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtBillValueForSalesFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtBillValueForSalesFocusLost(evt);
            }
        });
        txtBillValueForSales.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBillValueForSalesActionPerformed(evt);
            }
        });
        getContentPane().add(txtBillValueForSales, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 370, 230, 26));

        txtCreditPeriod.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        txtCreditPeriod.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        txtCreditPeriod.setText("0");
        txtCreditPeriod.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtCreditPeriodFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtCreditPeriodFocusLost(evt);
            }
        });
        txtCreditPeriod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCreditPeriodActionPerformed(evt);
            }
        });
        getContentPane().add(txtCreditPeriod, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 260, 120, -1));

        jLabel21.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(51, 51, 255));
        jLabel21.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 153, 255), 2), "ගැණුම් මිළට", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Iskoola Pota", 0, 18), new java.awt.Color(51, 51, 255))); // NOI18N
        getContentPane().add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 310, 420, 120));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 51, 255));
        jLabel4.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 153, 255), 2), "විකුණුම් මිළට", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Iskoola Pota", 0, 18), new java.awt.Color(51, 51, 255))); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 310, 420, 120));

        jButton7.setText("...");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 170, 50, -1));

        jLabel25.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(51, 51, 255));
        jLabel25.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 153, 255), 2), "සාමාන්‍ය තොරතුරු", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Iskoola Pota", 0, 18), new java.awt.Color(51, 51, 255))); // NOI18N
        getContentPane().add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 840, 220));

        statusglCode.setText("202");

        statusglCode1.setFont(new java.awt.Font("Ubuntu", 1, 14)); // NOI18N
        statusglCode1.setForeground(new java.awt.Color(255, 0, 0));
        statusglCode1.setText("ONLINE");

        javax.swing.GroupLayout jXStatusBar1Layout = new javax.swing.GroupLayout(jXStatusBar1);
        jXStatusBar1.setLayout(jXStatusBar1Layout);
        jXStatusBar1Layout.setHorizontalGroup(
            jXStatusBar1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jXStatusBar1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(statusglCode1, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(statusglCode, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 616, Short.MAX_VALUE)
                .addComponent(userName, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jXStatusBar1Layout.setVerticalGroup(
            jXStatusBar1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jXStatusBar1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(statusglCode, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(userName, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(statusglCode1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        getContentPane().add(jXStatusBar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 500, 880, 30));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtBillNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBillNumberActionPerformed
        txtCreditPeriod.grabFocus();
    }//GEN-LAST:event_txtBillNumberActionPerformed

    private void txtNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNumberActionPerformed

    private void txtSupplierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSupplierActionPerformed
        jButton6.doClick();
    }//GEN-LAST:event_txtSupplierActionPerformed

    private void txt16NumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt16NumberActionPerformed
        txtBillNumber.grabFocus();
    }//GEN-LAST:event_txt16NumberActionPerformed

    private void txtSectionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSectionActionPerformed
        jButton5.doClick();
    }//GEN-LAST:event_txtSectionActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        new FindSectionOrOutsider(this, TableHeaders.SUBSECTIONFINDER_TABLE_MODEL, TableHeaders.SUBSECTIONFINDER_TABLE_MODEL2, 45, "අනු අංශය").setVisible(true);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        new FindSectionOrOutsider(this, TableHeaders.OUTSIDERFINDER_TABLE_MODEL, TableHeaders.OUTSIDERFINDER_TABLE_MODEL2, 46, "පාර්ශවකරු").setVisible(true);
    }//GEN-LAST:event_jButton6ActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        save16BStores();
//        JOptionPane.showMessageDialog(this, "<html><p>ගණුදෙනුව සම්පූර්ණයි.</p></html>", "සාර්ථකයි", JOptionPane.INFORMATION_MESSAGE);
//        this.dispose();
//        CommonJurnalForm.ItemRefresh.doClick();
//        String[] buttons = {"Yes", "No"};
//        int i = JOptionPane.showOptionDialog(this, "<html><p>ගණුදෙනුව සම්පූර්ණයි. නව ගණුදෙනුවක් සිදු කරනවාද?</p></html>", "සාර්ථකයි", JOptionPane.YES_NO_OPTION, JOptionPane.INFORMATION_MESSAGE, null, buttons, buttons[1]);

//        if (i == JOptionPane.YES_OPTION) {
//            String section = txtSection.getText();
//            int sid = txtSection.getId();
//            AB16StoresBuyings aB16Buyings = new AB16StoresBuyings(code);
//            int i2 = JOptionPane.showOptionDialog(this, "<html><p>අංශය වෙනස් කරනවාද?</p></html>", "වෙනස් කරනවාද?", JOptionPane.YES_NO_OPTION, JOptionPane.INFORMATION_MESSAGE, null, buttons, buttons[1]);
//            if (i2 == JOptionPane.NO_OPTION) {
//                this.dispose();
//                CommonJurnalForm.ItemRefresh.doClick();
//                AB16StoresBuyings.txtSection.setId(sid);
//                AB16StoresBuyings.txtSection.setText(section);
//                aB16Buyings.setVisible(true);
//                aB16Buyings.btnNew.doClick();
//            } else {
//                this.dispose();
//                CommonJurnalForm.ItemRefresh.doClick();
//                aB16Buyings.setVisible(true);
//                aB16Buyings.btnNew.doClick();
//            }
//        }

    }//GEN-LAST:event_btnSaveActionPerformed

    private void txtStoresValueFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtStoresValueFocusGained
        txtStoresValue.selectAll();
    }//GEN-LAST:event_txtStoresValueFocusGained

    private void txtStoresValueFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtStoresValueFocusLost
        txtStoresValue.select(0, 0);
    }//GEN-LAST:event_txtStoresValueFocusLost

    private void txtBillValueForSalesFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtBillValueForSalesFocusGained
        txtBillValueForSales.selectAll();
    }//GEN-LAST:event_txtBillValueForSalesFocusGained

    private void txtBillValueForSalesFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtBillValueForSalesFocusLost
        txtBillValueForSales.select(0, 0);
    }//GEN-LAST:event_txtBillValueForSalesFocusLost

    private void txtStoresValueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtStoresValueActionPerformed
        txtBillValueForSales.grabFocus();
    }//GEN-LAST:event_txtStoresValueActionPerformed

    private void txtCreditPeriodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCreditPeriodActionPerformed
        txtStoresValue.grabFocus();
    }//GEN-LAST:event_txtCreditPeriodActionPerformed

    private void txtCreditPeriodFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCreditPeriodFocusGained
        txtCreditPeriod.selectAll();
    }//GEN-LAST:event_txtCreditPeriodFocusGained

    private void txtCreditPeriodFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCreditPeriodFocusLost
        txtCreditPeriod.select(0, txtCreditPeriod.getText().length() - 1);
    }//GEN-LAST:event_txtCreditPeriodFocusLost

    private void txtBillValueForSalesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBillValueForSalesActionPerformed
        save16BStores();
    }//GEN-LAST:event_txtBillValueForSalesActionPerformed

    private void btnSaveKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnSaveKeyReleased
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            btnSave.doClick();
        }
    }//GEN-LAST:event_btnSaveKeyReleased

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing

    }//GEN-LAST:event_formWindowClosing

    private void btnNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewActionPerformed
        try {
            doSave();
            btnSave.setEnabled(true);
            btnNew.setEnabled(false);
        } catch (ParseException ex) {
            Logger.getLogger(AB16StoresBuyings.class.getName()).log(Level.SEVERE, null, ex);
        } catch (RemoteException ex) {
            Logger.getLogger(AB16StoresBuyings.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(AB16StoresBuyings.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(AB16StoresBuyings.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnNewActionPerformed

    private void btnApproveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnApproveActionPerformed
        String[] buttons = {"Yes", "No"};
        int i = JOptionPane.showOptionDialog(this, "<html><p><span style='color:red'>" + btnApprove.getText().split(" ")[0] + " කළ පසු වෙනස් කල නොහැක.</span> " + btnApprove.getText().split(" ")[0] + " කරනවාද?</p></html>", "සාර්ථකයි", JOptionPane.YES_NO_OPTION, JOptionPane.INFORMATION_MESSAGE, null, buttons, buttons[1]);
        if (i == JOptionPane.YES_OPTION) {
            try {
                List<Object> inputs = new ArrayList<>();
                inputs.add(status);
                if (code.equals("01-01")) {
                    inputs.add(GLCodes.AB16BUYINGS);
                } else if (code.equals("01-02")) {
                    inputs.add(GLCodes.AB16CASHPURCHASE);
                } else if (code.equals("01-03")) {
                    inputs.add(GLCodes.AB16PURCHASEDADVANCE);
                } else if (code.equals("01-04")) {
                    inputs.add(GLCodes.AB16STORESRECEIVINGS);
                }
                inputs.add(id);
                inputs.add(GeneralUserLogin.data.getUsername());
                ServerConnection.getServerConnector().insertData(inputs, "ssp_F28_Confirm_Stock", 0);
                JOptionPane.showMessageDialog(this, "සාර්ථකයි", "සාර්ථකයි", JOptionPane.INFORMATION_MESSAGE);
                this.dispose();
                CommonJurnalForm.ItemRefresh.doClick();
            } catch (SQLException ex) {
                Logger.getLogger(C14B9.class.getName()).log(Level.SEVERE, null, ex);
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(C14B9.class.getName()).log(Level.SEVERE, null, ex);
            } catch (RemoteException ex) {
                Logger.getLogger(C14B9.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else {
            this.dispose();
            CommonJurnalForm.ItemRefresh.doClick();
        }
    }//GEN-LAST:event_btnApproveActionPerformed

    private void txtStoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtStoresActionPerformed
        jButton7.doClick();
    }//GEN-LAST:event_txtStoresActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        new FindSectionOrOutsider(this, TableHeaders.SUBSECTIONFINDER_TABLE_MODEL, TableHeaders.SUBSECTIONFINDER_TABLE_MODEL2, 47, "අනු අංශය").setVisible(true);
    }//GEN-LAST:event_jButton7ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AB16StoresBuyings.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AB16StoresBuyings.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AB16StoresBuyings.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AB16StoresBuyings.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AB16StoresBuyings().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnApprove;
    private static javax.swing.JButton btnNew;
    private javax.swing.JButton btnSave;
    private javax.swing.JDialog confirmDialog;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private org.jdesktop.swingx.JXStatusBar jXStatusBar1;
    private com.toedter.calendar.JDateChooser jdt14CDate;
    private com.toedter.calendar.JDateChooser jdt16BDate;
    private javax.swing.JLabel statusglCode;
    private javax.swing.JLabel statusglCode1;
    public static javax.swing.JTextField txt16Number;
    private javax.swing.JTextField txtBillNumber;
    private javax.swing.JFormattedTextField txtBillValueForSales;
    private javax.swing.JTextField txtCreditPeriod;
    private javax.swing.JTextField txtNumber;
    public static org.nbs.components.HiddenIDTextField txtSection;
    public static org.nbs.components.HiddenIDTextField txtStores;
    private javax.swing.JFormattedTextField txtStoresValue;
    public static org.nbs.components.HiddenIDTextField txtSupplier;
    private javax.swing.JLabel userName;
    // End of variables declaration//GEN-END:variables

    private void save16BStores() {
        try {
            if (code.equals("01-02")) {
                if (txtSection.getId() != 0 && txtSupplier.getId() != 0 && !txt16Number.getText().trim().equals("")) {
                    doSave();
                    JOptionPane.showMessageDialog(this, "<html><p>ගණුදෙනුව සම්පූර්ණයි.</p></html>", "සාර්ථකයි", JOptionPane.INFORMATION_MESSAGE);
                    this.dispose();
                    CommonJurnalForm.ItemRefresh.doClick();
                } else {
                    JOptionPane.showMessageDialog(this, "අංශය හෝ සැපයුම්කරු ඇතුලත් කර නැත", "අංශය හෝ සැපයුම්කරු ඇතුලත් කර නැත", JOptionPane.ERROR_MESSAGE);
                }
            } else if (code.equals("01-04")) {
                if (txtSection.getId() != 0 && txtStores.getId() != 0 && txtSupplier.getId() != 0 && !txt16Number.getText().trim().equals("")) {
                    doSave();
                    JOptionPane.showMessageDialog(this, "<html><p>ගණුදෙනුව සම්පූර්ණයි.</p></html>", "සාර්ථකයි", JOptionPane.INFORMATION_MESSAGE);
                    this.dispose();
                    CommonJurnalForm.ItemRefresh.doClick();
                } else {
                    JOptionPane.showMessageDialog(this, "අංශය,ගබඩාව හෝ සැපයුම්කරු ඇතුලත් කර නැත", "අංශය,ගබඩාව හෝ සැපයුම්කරු ඇතුලත් කර නැත", JOptionPane.ERROR_MESSAGE);
                }
            }
        } catch (RemoteException ex) {
            Logger.getLogger(AB16StoresBuyings.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(AB16StoresBuyings.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(AB16StoresBuyings.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ParseException ex) {
            Logger.getLogger(AB16StoresBuyings.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void doSave() throws ParseException, RemoteException, SQLException, ClassNotFoundException {
        List<Object> inputs = new ArrayList<>();
        inputs.add(txtNumber.getText());
        inputs.add(FormatConstants.dateFormat.format(jdt16BDate.getDate()));
        inputs.add(txt16Number.getText());
        inputs.add(statusglCode.getText());
        inputs.add(txtSection.getId());
        inputs.add(txtStores.getId());
        inputs.add(txtSupplier.getId());
        inputs.add(txt16Number.getText());
        inputs.add(txtBillNumber.getText());
        inputs.add(FormatConstants.dateFormat.format(jdt14CDate.getDate()));
        inputs.add(FormatConstants.numberFormat1.parse(txtStoresValue.getText()).doubleValue());
        inputs.add(FormatConstants.numberFormat1.parse(txtBillValueForSales.getText()).doubleValue());
        inputs.add(txtCreditPeriod.getText());
        inputs.add(FormatConstants.dateFormat.format(jdt14CDate.getDate()));
        inputs.add(GeneralUserLogin.data.getUsername());
        inputs.add("@recid");

        List<Object> output = ServerConnection.getServerConnector().insertData(inputs, "ssp_F28_Insert_F16B_StkTrn", 1);

        txtNumber.setText(output.get(0).toString());
    }

}
