/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.nbs.view.manager.GL;

import com.nbs.impl.ServerConnection;
import java.awt.Font;
import java.rmi.RemoteException;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultListModel;
import javax.swing.JFrame;
import javax.swing.JList;
import org.nbs.resources.Item;

/**
 * created on Nov 24, 2015
 *
 * @author mmh
 *
 */
public class GLAccountsChange extends javax.swing.JFrame {

//    DefaultTableModel dtm;
    DefaultListModel<Item> dlm1;
    private JList dataList1;
    DefaultListModel<Item> dlm2;
    private JList dataList2;
    private int combo1id = 0;
    private int combo2id = 0;

    /**
     * Creates new form GLAccountsTransfer
     */
    public GLAccountsChange() {
        initComponents();
        setExtendedState(JFrame.MAXIMIZED_BOTH);
//        TableColumnFontChanger.setAmalee(dataTable, 2);
//        TableColumnFontChanger.setAmalee(dataTable, 4);
//        TableColumnFontChanger.setIskolaPotha(dataTable, 3);
//        dtm = (DefaultTableModel) dataTable.getModel();
        dlm1 = new DefaultListModel<>();
        dlm2 = new DefaultListModel<>();
        dataList1 = new JList(dlm1);
        dataList2 = new JList(dlm2);
        dataList1.setFont(new Font("Iskoola Pota", 0, 16));
        dataList2.setFont(new Font("Iskoola Pota", 0, 16));
        jScrollPane2.setViewportView(dataList2);
        jScrollPane3.setViewportView(dataList1);
        loadAcctL4();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        comboAcctL4_2 = new org.nbs.components.HiddenItemComboBox();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        comboAcctL4_1 = new org.nbs.components.HiddenItemComboBox();
        jScrollPane3 = new javax.swing.JScrollPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(java.awt.Color.white);

        comboAcctL4_2.setFont(new java.awt.Font("Iskoola Pota", 0, 18)); // NOI18N
        comboAcctL4_2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboAcctL4_2ActionPerformed(evt);
            }
        });

        jButton1.setText(">>");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("<<");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 153, 255), 1, true));
        jPanel2.setLayout(new java.awt.GridLayout(1, 0));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Iskoola Pota", 1, 21)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icon_reset.gif"))); // NOI18N
        jLabel1.setText("පොදු ලෙජර ගිණුම් මාරු කිරීම");
        jPanel2.add(jLabel1);

        jScrollPane2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 153, 255), 1, true));
        jScrollPane2.setFont(new java.awt.Font("Iskoola Pota", 0, 16)); // NOI18N

        comboAcctL4_1.setFont(new java.awt.Font("Iskoola Pota", 0, 18)); // NOI18N
        comboAcctL4_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboAcctL4_1ActionPerformed(evt);
            }
        });

        jScrollPane3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 153, 255), 1, true));
        jScrollPane3.setFont(new java.awt.Font("Iskoola Pota", 0, 16)); // NOI18N
        jScrollPane3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jScrollPane3MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(comboAcctL4_1, javax.swing.GroupLayout.PREFERRED_SIZE, 355, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 355, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(comboAcctL4_2, javax.swing.GroupLayout.DEFAULT_SIZE, 355, Short.MAX_VALUE)
                            .addComponent(jScrollPane2))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comboAcctL4_2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comboAcctL4_1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 448, Short.MAX_VALUE))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1)
                        .addGap(30, 30, 30)
                        .addComponent(jButton2)
                        .addGap(194, 194, 194))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(805, 601));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        List<Object> inputs = new ArrayList<>();
        try {
            inputs.add(4);
            inputs.add(comboAcctL4_2.getSelectedItem().getId());
            inputs.add(dlm1.get(dataList1.getSelectedIndex()).getId());
            ServerConnection.getServerConnector().insertData(inputs, "ssp_Act_AccountTransfer", 0);
        } catch (SQLException ex) {
            Logger.getLogger(GLAccountsChange.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(GLAccountsChange.class.getName()).log(Level.SEVERE, null, ex);
        } catch (RemoteException ex) {
            Logger.getLogger(GLAccountsChange.class.getName()).log(Level.SEVERE, null, ex);
        }
        list1Load();
        combo2Selected();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        List<Object> inputs = new ArrayList<>();
        try {
            inputs.add(4);
            inputs.add(comboAcctL4_1.getSelectedItem().getId());
            inputs.add(dlm2.get(dataList2.getSelectedIndex()).getId());
            ServerConnection.getServerConnector().insertData(inputs, "ssp_Act_AccountTransfer", 0);
        } catch (SQLException ex) {
            Logger.getLogger(GLAccountsChange.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(GLAccountsChange.class.getName()).log(Level.SEVERE, null, ex);
        } catch (RemoteException ex) {
            Logger.getLogger(GLAccountsChange.class.getName()).log(Level.SEVERE, null, ex);
        }
        list1Load();
        combo2Selected();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void comboAcctL4_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboAcctL4_2ActionPerformed
        combo2Selected();
    }//GEN-LAST:event_comboAcctL4_2ActionPerformed

    private void comboAcctL4_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboAcctL4_1ActionPerformed
        combo1Selected();
    }//GEN-LAST:event_comboAcctL4_1ActionPerformed

    private void jScrollPane3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jScrollPane3MouseClicked
        
    }//GEN-LAST:event_jScrollPane3MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GLAccountsChange.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GLAccountsChange.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GLAccountsChange.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GLAccountsChange.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GLAccountsChange().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private org.nbs.components.HiddenItemComboBox comboAcctL4_1;
    private org.nbs.components.HiddenItemComboBox comboAcctL4_2;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    public javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    // End of variables declaration//GEN-END:variables

    private void loadAcctL4() {
        try {
            List<Object> inputs = new ArrayList<>();
            inputs.add(1);
            inputs.add(0);
            inputs.add(0);
            List<List<Object>> outputs = ServerConnection.getServerConnector().searchMultipleResults(inputs, "ssp_Act_AccountTransfer", 5);
            Vector v = new Vector();
            for (List<Object> output : outputs) {
                v.add(new Item(Integer.parseInt(output.get(0).toString()), output.get(1).toString() + "  " + output.get(3).toString()));
            }
            comboAcctL4_1.setModel(new DefaultComboBoxModel<>(v));
        } catch (RemoteException ex) {
            Logger.getLogger(GLAccountsChange.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(GLAccountsChange.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(GLAccountsChange.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void combo1Selected() {
        list1Load();
        
        List<Object> inputs = new ArrayList<>();
        inputs.add(2);
        inputs.add(comboAcctL4_1.getSelectedItem().getId());
        inputs.add(0);
        try {
            List<List<Object>> outputs = ServerConnection.getServerConnector().searchMultipleResults(inputs, "ssp_Act_AccountTransfer", 5);
            Vector v = new Vector();
            for (List<Object> output : outputs) {
                v.add(new Item(Integer.parseInt(output.get(0).toString()), output.get(1).toString() + "  " + output.get(3).toString()));
            }
            comboAcctL4_2.setModel(new DefaultComboBoxModel<>(v));
            dlm2.clear();
        } catch (RemoteException ex) {
            Logger.getLogger(GLAccountsChange.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(GLAccountsChange.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(GLAccountsChange.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    private void combo2Selected() {
        combo2id = comboAcctL4_2.getSelectedItem().getId();
        List inputs = new ArrayList<>();
        inputs.add(3);
        inputs.add(comboAcctL4_2.getSelectedItem().getId());
        inputs.add(0);

        List<List<Object>> outputs = null;
        try {
            outputs = ServerConnection.getServerConnector().searchMultipleResults(inputs, "ssp_Act_AccountTransfer", 2);
        } catch (RemoteException ex) {
            Logger.getLogger(GLAccountsChange.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(GLAccountsChange.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(GLAccountsChange.class.getName()).log(Level.SEVERE, null, ex);
        }
        Item item = null;
        dlm2.clear();
        for (List<Object> output : outputs) {
            item = new Item(Integer.parseInt(output.get(0).toString()), output.get(1).toString());
            dlm2.add(dlm2.getSize(), item);
        }
    }

    private void list1Load() {
        combo1id = comboAcctL4_1.getSelectedItem().getId();
        List inputs = new ArrayList<>();
        inputs.add(3);
        inputs.add(comboAcctL4_1.getSelectedItem().getId());
        inputs.add(0);
        List<List<Object>> outputs = null;
        try {
            outputs = ServerConnection.getServerConnector().searchMultipleResults(inputs, "ssp_Act_AccountTransfer", 2);
        } catch (RemoteException ex) {
            Logger.getLogger(GLAccountsChange.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(GLAccountsChange.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(GLAccountsChange.class.getName()).log(Level.SEVERE, null, ex);
        }
        Item item = null;
        dlm1.clear();
        for (List<Object> output : outputs) {
            item = new Item(Integer.parseInt(output.get(0).toString()), output.get(1).toString());
            dlm1.add(dlm1.getSize(), item);
        }
    }

}
