/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

 /*
 * frm_F28_CHQ_Module.java
 *
 * Created on Oct 25, 2013, 7:01:26 AM
 */
package com.nbs.view.common;

import Sources.NumberToWords;
import Sources.ReportFileLocator;
import Sources.SinhalaOriginalNumberToLetter;
import Sources.User;
import com.nbs.connection.DB;
import com.nbs.impl.ServerConnection;
import com.nbs.view.manager.CommonJurnalForm;
import java.awt.Frame;
import java.math.BigDecimal;
import java.rmi.RemoteException;
import java.sql.SQLException;
import java.text.ParseException;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author mmh
 */
public class CHQModule extends javax.swing.JDialog {

    /**
     * Creates new form frm_F28_CHQ_Module
     */
//    DecimalFormat formatter = new DecimalFormat("#,##0.00");
    private String id;
    private User user;

    public CHQModule(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
        System.out.println("");
    }

    public CHQModule(Frame parent, boolean modal, String id) {
        this(parent, modal);
        this.id = id;
        List<Object> inputs = new ArrayList<>();

        try {
            inputs.add(id);
            List<Object> output = ServerConnection.getServerConnector().searchSingleResult(inputs, "ssp_F28_LoadCombo_ViewChequePrint", 17);

            txtBillNo.setText(String.valueOf(output.get(2)));
            txtSubSection.setText(String.valueOf(output.get(3)));
            txtOutsider.setText(String.valueOf(output.get(4)));
            txtReason.setText(String.valueOf(output.get(5)));
            txtAmount.setText(String.valueOf(output.get(6)));
            txtAmountView.setText(String.valueOf(output.get(6)));
            txtBank.setText(String.valueOf(output.get(7)));
            txtChequeNo.setText(String.valueOf(output.get(8)));
            jdtChequeDate.setDate(FormatConstants.dateFormat.parse(String.valueOf(output.get(9))));
            txtMaxAmount.setText(String.valueOf(output.get(11)));
            txtOurBillNo.setText(String.valueOf(output.get(12)));
            if (String.valueOf(output.get(13)).equals("1")) {
                optEng.setSelected(true);
            } else if (String.valueOf(output.get(13)).equals("0")) {
                optSin.setSelected(true);
            }
            if (String.valueOf(output.get(14)).equals("1")) {
                optAccountPayeeOnly.setSelected(true);
            } else if (String.valueOf(output.get(14)).equals("0")) {
                optAccountPayeeOnly.setSelected(false);
            }
            if (String.valueOf(output.get(15)).equals("1")) {
                optGMSignature.setSelected(true);
            } else if (String.valueOf(output.get(15)).equals("0")) {
                optGMSignature.setSelected(false);
            }
            jdtF8Date.setDate(FormatConstants.dateFormat.parse(String.valueOf(output.get(16))));
        } catch (SQLException ex) {
            Logger.getLogger(CHQModule.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(CHQModule.class.getName()).log(Level.SEVERE, null, ex);
        } catch (RemoteException ex) {
            Logger.getLogger(CHQModule.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ParseException ex) {
            Logger.getLogger(CHQModule.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    public CHQModule(Frame parent, boolean modal, String id, User user) {
        this(parent, modal, id);
        this.user = user;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        optSin = new javax.swing.JRadioButton();
        optEng = new javax.swing.JRadioButton();
        jPanel4 = new javax.swing.JPanel();
        txtChequeNo = new javax.swing.JTextField();
        txtMaxAmount = new javax.swing.JTextField();
        txtAmount = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        txtBank = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        txtOurBillNo = new javax.swing.JTextField();
        jdtChequeDate = new com.toedter.calendar.JDateChooser();
        jLabel18 = new javax.swing.JLabel();
        jdtF8Date = new com.toedter.calendar.JDateChooser();
        jPanel3 = new javax.swing.JPanel();
        optAccountPayeeOnly = new javax.swing.JCheckBox();
        optGMSignature = new javax.swing.JCheckBox();
        jPanel5 = new javax.swing.JPanel();
        btnCheque = new javax.swing.JButton();
        btnChequeMax = new javax.swing.JButton();
        btnCheque1 = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        txtBillNo = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtSubSection = new javax.swing.JLabel();
        txtOutsider = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        txtReason = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        txtAmountView = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(704, 412));
        setSize(new java.awt.Dimension(704, 412));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jPanel1.setBackground(java.awt.Color.white);

        jPanel2.setBackground(new java.awt.Color(189, 198, 250));

        jLabel1.setFont(new java.awt.Font("Iskoola Pota", 0, 25)); // NOI18N
        jLabel1.setText("චෙක්පත් නිකුත් කිරීම");

        buttonGroup1.add(optSin);
        optSin.setFont(new java.awt.Font("Iskoola Pota", 0, 16)); // NOI18N
        optSin.setForeground(java.awt.Color.blue);
        optSin.setSelected(true);
        optSin.setText("සිංහල");
        optSin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                optSinActionPerformed(evt);
            }
        });

        buttonGroup1.add(optEng);
        optEng.setFont(new java.awt.Font("Iskoola Pota", 0, 16)); // NOI18N
        optEng.setForeground(java.awt.Color.blue);
        optEng.setText("English");
        optEng.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                optEngActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(76, 76, 76)
                .addComponent(optSin, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(optEng, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                    .addComponent(optSin)
                    .addComponent(optEng))
                .addContainerGap())
        );

        jPanel4.setBackground(java.awt.Color.white);
        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(java.awt.Color.blue));

        txtChequeNo.setFont(new java.awt.Font("Tahoma", 1, 17)); // NOI18N
        txtChequeNo.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtChequeNo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtChequeNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtChequeNoActionPerformed(evt);
            }
        });
        txtChequeNo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtChequeNoKeyTyped(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtChequeNoKeyReleased(evt);
            }
        });

        txtMaxAmount.setFont(new java.awt.Font("Tahoma", 1, 17)); // NOI18N
        txtMaxAmount.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtMaxAmount.setText("0.00");
        txtMaxAmount.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtMaxAmount.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtMaxAmountFocusLost(evt);
            }
        });
        txtMaxAmount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMaxAmountActionPerformed(evt);
            }
        });
        txtMaxAmount.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtMaxAmountKeyReleased(evt);
            }
        });

        txtAmount.setEditable(false);
        txtAmount.setFont(new java.awt.Font("Tahoma", 1, 17)); // NOI18N
        txtAmount.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtAmount.setText("0.00");
        txtAmount.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtAmount.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtAmountFocusLost(evt);
            }
        });
        txtAmount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAmountActionPerformed(evt);
            }
        });
        txtAmount.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtAmountKeyReleased(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Iskoola Pota", 0, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(51, 153, 255));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel9.setText("දිනය :");

        jLabel10.setFont(new java.awt.Font("Iskoola Pota", 0, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(51, 153, 255));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel10.setText("අංකය :");

        jLabel11.setFont(new java.awt.Font("Iskoola Pota", 0, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(51, 153, 255));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel11.setText("බැංකුව :");

        jLabel12.setFont(new java.awt.Font("Iskoola Pota", 0, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(51, 153, 255));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel12.setText("වටිනාකම :");

        jLabel13.setFont(new java.awt.Font("Iskoola Pota", 0, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(51, 153, 255));
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel13.setText("උපරිමය :");

        txtBank.setBackground(new java.awt.Color(224, 247, 143));
        txtBank.setFont(new java.awt.Font("Iskoola Pota", 1, 18)); // NOI18N
        txtBank.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtBank.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBankActionPerformed(evt);
            }
        });
        txtBank.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtBankKeyReleased(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Iskoola Pota", 0, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(51, 153, 255));
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel15.setText("වවුචර් අංකය :");

        txtOurBillNo.setFont(new java.awt.Font("Tahoma", 1, 17)); // NOI18N
        txtOurBillNo.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtOurBillNo.setText("0");
        txtOurBillNo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtOurBillNo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtOurBillNoMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txtOurBillNoMouseEntered(evt);
            }
        });
        txtOurBillNo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtOurBillNoKeyReleased(evt);
            }
        });

        jdtChequeDate.setDateFormatString("yyyy-MM-dd");

        jLabel18.setFont(new java.awt.Font("Iskoola Pota", 0, 18)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(51, 153, 255));
        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel18.setText("F8 දිනය :");

        jdtF8Date.setDateFormatString("yyyy-MM-dd");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtChequeNo, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtMaxAmount))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel4Layout.createSequentialGroup()
                                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtOurBillNo)
                            .addComponent(jdtChequeDate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jdtF8Date, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtBank, javax.swing.GroupLayout.PREFERRED_SIZE, 558, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(12, 12, 12))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtBank, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtChequeNo, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jdtChequeDate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txtAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jdtF8Date, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(1, 1, 1)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtMaxAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtOurBillNo, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(32, Short.MAX_VALUE))
        );

        jPanel3.setBackground(java.awt.Color.white);
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(java.awt.Color.blue));

        optAccountPayeeOnly.setBackground(java.awt.Color.white);
        optAccountPayeeOnly.setFont(new java.awt.Font("Iskoola Pota", 0, 18)); // NOI18N
        optAccountPayeeOnly.setText("ආදායකයාගේ ගිණුමට පමණයි");

        optGMSignature.setBackground(java.awt.Color.white);
        optGMSignature.setFont(new java.awt.Font("Iskoola Pota", 0, 18)); // NOI18N
        optGMSignature.setText("සාමාන්‍යාධිකාරි/ගණකාධිකාරී අත්සන");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(optAccountPayeeOnly, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(56, 56, 56)
                .addComponent(optGMSignature, javax.swing.GroupLayout.PREFERRED_SIZE, 321, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(optAccountPayeeOnly)
                    .addComponent(optGMSignature))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        jPanel5.setBackground(new java.awt.Color(189, 198, 250));

        btnCheque.setFont(new java.awt.Font("Iskoola Pota", 0, 18)); // NOI18N
        btnCheque.setForeground(java.awt.Color.blue);
        btnCheque.setText("චෙක්");
        btnCheque.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChequeActionPerformed(evt);
            }
        });

        btnChequeMax.setFont(new java.awt.Font("Iskoola Pota", 0, 18)); // NOI18N
        btnChequeMax.setForeground(java.awt.Color.blue);
        btnChequeMax.setText("චෙක් - උපරිම");
        btnChequeMax.setEnabled(false);
        btnChequeMax.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChequeMaxActionPerformed(evt);
            }
        });

        btnCheque1.setFont(new java.awt.Font("Iskoola Pota", 0, 18)); // NOI18N
        btnCheque1.setForeground(java.awt.Color.blue);
        btnCheque1.setText("සේව්");
        btnCheque1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCheque1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnCheque1, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnCheque, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnChequeMax, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCheque, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnChequeMax, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCheque1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.setBorder(javax.swing.BorderFactory.createLineBorder(java.awt.Color.blue));

        txtBillNo.setFont(new java.awt.Font("Iskoola Pota", 0, 17)); // NOI18N
        txtBillNo.setForeground(java.awt.Color.blue);
        txtBillNo.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        txtBillNo.setText("jLabel2");

        jLabel5.setFont(new java.awt.Font("Iskoola Pota", 0, 18)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel5.setText("බිල් අංකය :");

        jLabel6.setFont(new java.awt.Font("Iskoola Pota", 0, 18)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel6.setText("අංශය :");

        txtSubSection.setFont(new java.awt.Font("Iskoola Pota", 0, 17)); // NOI18N
        txtSubSection.setForeground(java.awt.Color.blue);
        txtSubSection.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        txtSubSection.setText("jLabel2");

        txtOutsider.setFont(new java.awt.Font("Iskoola Pota", 0, 17)); // NOI18N
        txtOutsider.setForeground(java.awt.Color.blue);
        txtOutsider.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        txtOutsider.setText("jLabel2");

        jLabel14.setFont(new java.awt.Font("Iskoola Pota", 0, 18)); // NOI18N
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel14.setText("ණයකරු :");

        jLabel16.setFont(new java.awt.Font("Iskoola Pota", 0, 18)); // NOI18N
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel16.setText("කාරණය :");

        txtReason.setFont(new java.awt.Font("Iskoola Pota", 0, 17)); // NOI18N
        txtReason.setForeground(java.awt.Color.blue);
        txtReason.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        txtReason.setText("jLabel2");

        jLabel17.setFont(new java.awt.Font("Iskoola Pota", 0, 18)); // NOI18N
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel17.setText("මුදල :");

        txtAmountView.setFont(new java.awt.Font("Iskoola Pota", 0, 17)); // NOI18N
        txtAmountView.setForeground(java.awt.Color.blue);
        txtAmountView.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        txtAmountView.setText("jLabel2");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtOutsider, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtBillNo, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtSubSection, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtReason, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtAmountView, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtBillNo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(txtSubSection, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtOutsider, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                    .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtReason, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                    .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtAmountView, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                    .addComponent(jLabel17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

private void txtChequeNoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtChequeNoKeyReleased
    
}//GEN-LAST:event_txtChequeNoKeyReleased

private void txtMaxAmountFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtMaxAmountFocusLost
    try {
        if (txtMaxAmount.getText().trim().isEmpty()) {
            txtMaxAmount.setText("0.00");
        }
        txtMaxAmount.setText(FormatConstants.decimalFormat.format(Double.parseDouble(txtMaxAmount.getText().trim())));
        if (FormatConstants.decimalFormat.parse(txtMaxAmount.getText()).doubleValue() > 0) {
            btnChequeMax.setEnabled(true);
            btnCheque.setEnabled(false);
            txtAmount.setText("0.00");
        } else {
            btnChequeMax.setEnabled(false);
            btnCheque.setEnabled(true);
            txtAmount.setText(txtAmountView.getText());
        }
    } catch (ParseException ex) {
        Logger.getLogger(CHQModule.class.getName()).log(Level.SEVERE, null, ex);
    }
}//GEN-LAST:event_txtMaxAmountFocusLost

private void txtMaxAmountKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtMaxAmountKeyReleased
//    if (evt.getKeyCode() == 10) {
//        txtMaxAmount.setText(FormatConstants.decimalFormat.format(Double.parseDouble(txtMaxAmount.getText())));
//    }
}//GEN-LAST:event_txtMaxAmountKeyReleased

private void txtAmountFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtAmountFocusLost
    try {
        if (txtAmount.getText().trim().isEmpty()) {
            txtAmount.setText("0.00");
        }
        txtAmount.setText(FormatConstants.decimalFormat.parse(txtAmount.getText().trim()).doubleValue() + "");//(formatter.format(Double.parseDouble(txtAmount.getText().trim())));
        if (FormatConstants.decimalFormat.parse(txtAmount.getText()).doubleValue() > 0) {
            btnChequeMax.setEnabled(false);
            btnCheque.setEnabled(true);
            txtMaxAmount.setText("0.00");
        } else {
            btnChequeMax.setEnabled(true);
            btnCheque.setEnabled(false);
        }
    } catch (ParseException ex) {
        Logger.getLogger(CHQModule.class.getName()).log(Level.SEVERE, null, ex);
    }
}//GEN-LAST:event_txtAmountFocusLost

private void txtAmountKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtAmountKeyReleased
    if (evt.getKeyCode() == 10) {
        try {
            txtMaxAmount.grabFocus();
            txtMaxAmount.selectAll();

            txtAmount.setText(FormatConstants.decimalFormat.format(FormatConstants.numberFormat1.parse(txtAmount.getText()).doubleValue()));
        } catch (ParseException ex) {
            Logger.getLogger(CHQModule.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
}//GEN-LAST:event_txtAmountKeyReleased

private void btnChequeMaxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChequeMaxActionPerformed
    if (optSin.isSelected()) {
        try {
            List<Object> inputs = new ArrayList<>();
            inputs.add(id);
            inputs.add(FormatConstants.dateFormat.format(jdtChequeDate.getDate()));
            inputs.add(FormatConstants.dateFormat.format(jdtF8Date.getDate()));
            inputs.add(txtOurBillNo.getText());
            inputs.add(txtChequeNo.getText());
            inputs.add(FormatConstants.decimalFormat.parse(txtAmount.getText()).doubleValue());
            inputs.add(FormatConstants.decimalFormat.parse(txtMaxAmount.getText()).doubleValue());
            inputs.add(optAccountPayeeOnly.isSelected());
            inputs.add(optGMSignature.isSelected());
            inputs.add(GeneralUserLogin.data.getUsername());
            ServerConnection.getServerConnector().insertData(inputs, "ssp_F28_Insert_Oth_TrnHD_Chq_Print", 0);

            Map params = new HashMap<>();
            params.put("Header_ID", Integer.parseInt(id));
            String convertNumberToWords = NumberToWords.convertNumberToWords(new BigDecimal(FormatConstants.decimalFormat.parse(txtAmount.getText().trim()).doubleValue()), true, true);
//            SinhalaOriginalNumberToLetter toLetter = new SinhalaOriginalNumberToLetter();
//            String number = toLetter.getNumber(formatter.parse(txtAmount.getText().trim()).doubleValue() + "");
//            number = "රුපියල් " + number;
//            params.put("Sin_Val", number);
            JasperReport jasperReport = JasperCompileManager.compileReport(ReportFileLocator.locateReportFile("R012_F28_Cheque_Sin_Max.jrxml"));
            JasperPrint jasperPrint = JasperFillManager.fillReport(jasperReport, params, DB.getConnection());
            JasperViewer viewer = new JasperViewer(jasperPrint, false);
            viewer.setModalExclusionType(ModalExclusionType.APPLICATION_EXCLUDE);

            viewer.setExtendedState(JFrame.MAXIMIZED_BOTH);
            viewer.setVisible(true);

        } catch (JRException ex) {
            Logger.getLogger(CHQModule.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(CHQModule.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(CHQModule.class.getName()).log(Level.SEVERE, null, ex);
        } catch (RemoteException ex) {
            Logger.getLogger(CHQModule.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ParseException ex) {
            Logger.getLogger(CHQModule.class.getName()).log(Level.SEVERE, null, ex);
        }
    } else {
        try {
            List<Object> inputs = new ArrayList<>();
            inputs.add(id);
            inputs.add(FormatConstants.dateFormat.format(jdtChequeDate.getDate()));
            inputs.add(txtOurBillNo.getText());
            inputs.add(txtChequeNo.getText());
            inputs.add(FormatConstants.decimalFormat.parse(txtMaxAmount.getText()).doubleValue());
            inputs.add(optAccountPayeeOnly.isSelected());
            inputs.add(optGMSignature.isSelected());
            inputs.add(GeneralUserLogin.data.getUsername());
            ServerConnection.getServerConnector().insertData(inputs, "ssp_F28_Insert_Oth_TrnHD_Chq_Print", 0);

            Map params = new HashMap<>();
            params.put("Header_ID", Integer.parseInt(id));
//            EnglishNumberToLetter toLetter = new EnglishNumberToLetter();
//            String number = toLetter.getNumber(FormatConstants.decimalFormat.parse(txtAmount.getText().trim()).doubleValue() + "");
//            number = "රුපියල් " + number;
//            params.put("Sin_Val", number);
            JasperReport jasperReport = JasperCompileManager.compileReport(ReportFileLocator.locateReportFile("R016_F28_Cheque_Eng_Max.jrxml"));
            JasperPrint jasperPrint = JasperFillManager.fillReport(jasperReport, params, DB.getConnection());
            JasperViewer viewer = new JasperViewer(jasperPrint, false);
            viewer.setModalExclusionType(ModalExclusionType.APPLICATION_EXCLUDE);

            viewer.setExtendedState(JFrame.MAXIMIZED_BOTH);
            viewer.setVisible(true);

        } catch (JRException ex) {
            Logger.getLogger(CHQModule.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(CHQModule.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(CHQModule.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ParseException ex) {
            Logger.getLogger(CHQModule.class.getName()).log(Level.SEVERE, null, ex);
        } catch (RemoteException ex) {
            Logger.getLogger(CHQModule.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    CommonJurnalForm.ItemRefresh.doClick();
}//GEN-LAST:event_btnChequeMaxActionPerformed

private void txtBankActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBankActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_txtBankActionPerformed

private void txtBankKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBankKeyReleased

}//GEN-LAST:event_txtBankKeyReleased

private void txtOurBillNoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtOurBillNoMouseClicked
    txtOurBillNo.selectAll();
}//GEN-LAST:event_txtOurBillNoMouseClicked

private void txtOurBillNoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtOurBillNoMouseEntered
// TODO add your handling code here:
}//GEN-LAST:event_txtOurBillNoMouseEntered

private void txtOurBillNoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtOurBillNoKeyReleased
// TODO add your handling code here:
}//GEN-LAST:event_txtOurBillNoKeyReleased

private void btnChequeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChequeActionPerformed
    if (optSin.isSelected()) {
        try {
            List<Object> inputs = new ArrayList<>();
            inputs.add(id);
            inputs.add(FormatConstants.dateFormat.format(jdtChequeDate.getDate()));
            inputs.add(FormatConstants.dateFormat.format(jdtF8Date.getDate()));
            inputs.add(txtOurBillNo.getText());
            inputs.add(txtChequeNo.getText());
            inputs.add(FormatConstants.decimalFormat.parse(txtAmount.getText()).doubleValue());
            inputs.add(FormatConstants.decimalFormat.parse(txtMaxAmount.getText()).doubleValue());
            inputs.add(optAccountPayeeOnly.isSelected());
            inputs.add(optGMSignature.isSelected());
            inputs.add(GeneralUserLogin.data.getUsername());
            ServerConnection.getServerConnector().insertData(inputs, "ssp_F28_Insert_Oth_TrnHD_Chq_Print", 0);

            Map params = new HashMap<>();
            params.put("Header_ID", Integer.parseInt(id));
            SinhalaOriginalNumberToLetter toLetter = new SinhalaOriginalNumberToLetter();
            String number = toLetter.getNumber(FormatConstants.decimalFormat.parse(txtAmount.getText().trim()).doubleValue() + "");
//            number = "රුපියල් " + number;
            params.put("Sin_Val", number);
            JasperReport jasperReport = JasperCompileManager.compileReport(ReportFileLocator.locateReportFile("R011_F28_Cheque_Sin.jrxml"));
            JasperPrint jasperPrint = JasperFillManager.fillReport(jasperReport, params, DB.getConnection());
            JasperViewer viewer = new JasperViewer(jasperPrint, false);
            viewer.setModalExclusionType(ModalExclusionType.APPLICATION_EXCLUDE);

            viewer.setExtendedState(JFrame.MAXIMIZED_BOTH);
            viewer.setVisible(true);

        } catch (JRException ex) {
            Logger.getLogger(CHQModule.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(CHQModule.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(CHQModule.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ParseException ex) {
            Logger.getLogger(CHQModule.class.getName()).log(Level.SEVERE, null, ex);
        } catch (RemoteException ex) {
            Logger.getLogger(CHQModule.class.getName()).log(Level.SEVERE, null, ex);
        }
    } else {
        try {
            List<Object> inputs = new ArrayList<>();
            inputs.add(id);
            inputs.add(FormatConstants.dateFormat.format(jdtChequeDate.getDate()));
            inputs.add(txtOurBillNo.getText());
            inputs.add(txtChequeNo.getText());
            inputs.add(FormatConstants.decimalFormat.parse(txtMaxAmount.getText()).doubleValue());
            inputs.add(optAccountPayeeOnly.isSelected());
            inputs.add(optGMSignature.isSelected());
            inputs.add(GeneralUserLogin.data.getUsername());
            ServerConnection.getServerConnector().insertData(inputs, "ssp_F28_Insert_Oth_TrnHD_Chq_Print", 0);

            Map params = new HashMap<>();
            params.put("Header_ID", Integer.parseInt(id));
            String convertNumberToWords = NumberToWords.convertNumberToWords(new BigDecimal(FormatConstants.decimalFormat.parse(txtAmount.getText().trim()).doubleValue()), true, true);
//            EnglishNumberToLetter toLetter = new EnglishNumberToLetter();
//            System.out.println(FormatConstants.decimalFormat.parse(txtAmount.getText().trim()).doubleValue());
//            String number = toLetter.getNumber(FormatConstants.decimalFormat.parse(txtAmount.getText().trim()).doubleValue() + "");
////            number = "රුපියල් " + number;
            params.put("Sin_Val", convertNumberToWords);
//            System.out.println("eng "+convertNumberToWords);
            JasperReport jasperReport = JasperCompileManager.compileReport(ReportFileLocator.locateReportFile("R015_F28_Cheque_Eng.jrxml"));
            JasperPrint jasperPrint = JasperFillManager.fillReport(jasperReport, params, DB.getConnection());
            JasperViewer viewer = new JasperViewer(jasperPrint, false);
            viewer.setModalExclusionType(ModalExclusionType.APPLICATION_EXCLUDE);

            viewer.setExtendedState(JFrame.MAXIMIZED_BOTH);
            viewer.setVisible(true);

        } catch (JRException ex) {
            Logger.getLogger(CHQModule.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(CHQModule.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(CHQModule.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ParseException ex) {
            Logger.getLogger(CHQModule.class.getName()).log(Level.SEVERE, null, ex);
        } catch (RemoteException ex) {
            Logger.getLogger(CHQModule.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    CommonJurnalForm.ItemRefresh.doClick();
}//GEN-LAST:event_btnChequeActionPerformed

private void optSinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_optSinActionPerformed

}//GEN-LAST:event_optSinActionPerformed

private void optEngActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_optEngActionPerformed

}//GEN-LAST:event_optEngActionPerformed

    private void txtMaxAmountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMaxAmountActionPerformed
        try {
            if (txtMaxAmount.getText().trim().isEmpty()) {
                txtMaxAmount.setText("0.00");
            }
            txtMaxAmount.setText(FormatConstants.decimalFormat.parse((txtMaxAmount.getText().trim())).doubleValue() + "");
            if (FormatConstants.decimalFormat.parse(txtMaxAmount.getText()).doubleValue() > 0) {
                btnChequeMax.setEnabled(true);
                btnCheque.setEnabled(false);
                txtAmount.setText("0.00");
            } else {
                btnChequeMax.setEnabled(false);
                btnCheque.setEnabled(true);
            }
        } catch (ParseException ex) {
            Logger.getLogger(CHQModule.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_txtMaxAmountActionPerformed

    private void txtAmountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAmountActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAmountActionPerformed

    private void btnCheque1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCheque1ActionPerformed
        try {
            List<Object> inputs = new ArrayList<>();
            inputs.add(id);
            inputs.add(FormatConstants.dateFormat.format(jdtChequeDate.getDate()));
            inputs.add(FormatConstants.dateFormat.format(jdtF8Date.getDate()));
            inputs.add(txtOurBillNo.getText());
            inputs.add(txtChequeNo.getText());
            inputs.add(FormatConstants.decimalFormat.parse(txtAmount.getText()).doubleValue());
            inputs.add(FormatConstants.decimalFormat.parse(txtMaxAmount.getText()).doubleValue());
            inputs.add(optAccountPayeeOnly.isSelected());
            inputs.add(optGMSignature.isSelected());
            inputs.add(GeneralUserLogin.data.getUsername());
            ServerConnection.getServerConnector().insertData(inputs, "ssp_F28_Insert_Oth_TrnHD_Chq_Print", 0);
        } catch (ParseException ex) {
            Logger.getLogger(CHQModule.class.getName()).log(Level.SEVERE, null, ex);
        } catch (RemoteException ex) {
            Logger.getLogger(CHQModule.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(CHQModule.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(CHQModule.class.getName()).log(Level.SEVERE, null, ex);
        }
        CommonJurnalForm.ItemRefresh.doClick();
    }//GEN-LAST:event_btnCheque1ActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        CommonJurnalForm.ItemRefresh.doClick();
    }//GEN-LAST:event_formWindowClosing

    private void txtChequeNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtChequeNoActionPerformed
        txtAmount.grabFocus();
        txtAmount.selectAll();
    }//GEN-LAST:event_txtChequeNoActionPerformed

    private void txtChequeNoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtChequeNoKeyTyped
        if (!Character.isDigit(evt.getKeyChar())) {
            evt.consume();
        }
    }//GEN-LAST:event_txtChequeNoKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CHQModule.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CHQModule.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CHQModule.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CHQModule.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                CHQModule dialog = new CHQModule(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {

                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCheque;
    private javax.swing.JButton btnCheque1;
    private javax.swing.JButton btnChequeMax;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private com.toedter.calendar.JDateChooser jdtChequeDate;
    private com.toedter.calendar.JDateChooser jdtF8Date;
    private javax.swing.JCheckBox optAccountPayeeOnly;
    private javax.swing.JRadioButton optEng;
    private javax.swing.JCheckBox optGMSignature;
    private javax.swing.JRadioButton optSin;
    private javax.swing.JTextField txtAmount;
    private javax.swing.JLabel txtAmountView;
    private javax.swing.JTextField txtBank;
    private javax.swing.JLabel txtBillNo;
    private javax.swing.JTextField txtChequeNo;
    private javax.swing.JTextField txtMaxAmount;
    private javax.swing.JTextField txtOurBillNo;
    private javax.swing.JLabel txtOutsider;
    private javax.swing.JLabel txtReason;
    private javax.swing.JLabel txtSubSection;
    // End of variables declaration//GEN-END:variables

}
