/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.nbs.view.common;

import static Resources.SelectLang.textBundle;
import Resources.SystemParameterList;
import Sources.User;
import com.nbs.admin.ChangeUserPassword;
import com.nbs.impl.ServerConnection;
import com.nbs.xml.Data;
import com.nbs.xml.ReadXML;
import java.io.IOException;
import java.rmi.ConnectException;
import java.rmi.RemoteException;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.xml.parsers.ParserConfigurationException;
import javax.xml.xpath.XPathExpressionException;
import org.jasypt.util.text.BasicTextEncryptor;
import org.xml.sax.SAXException;

/**
 *
 * @author mmh
 */
public class GeneralUserLogin extends javax.swing.JFrame {

    /**
     * Creates new form GeneralUserLogin
     */
    public static String userName = "";
    public static String branchname = "ll";
    public static Data data;
    public static List<Object> userData;

    public GeneralUserLogin() {
        try {
            initComponents();
            setTexts();

            ReadXML XML = new ReadXML();
            Map<String, String> xmlData = XML.getXMLData();
            data = new Data();
            data.setBranchID(Integer.parseInt(xmlData.get("BranchID")));
            data.setDbName(xmlData.get("DBName"));
            data.setIP(xmlData.get("IP"));
            data.setReportPath(xmlData.get("ReportPath"));
            jLabel5.setText(data.getIP());
            BasicTextEncryptor encryptor = new BasicTextEncryptor();
            encryptor.setPassword("123");
            data.setPassword(encryptor.decrypt(xmlData.get("Password")));
            System.out.println(data.getPassword());
            data.setPort(xmlData.get("Port"));
            data.setServiceName(xmlData.get("ServiceName"));
        } catch (ParserConfigurationException ex) {
            Logger.getLogger(GeneralUserLogin.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SAXException ex) {
            Logger.getLogger(GeneralUserLogin.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(GeneralUserLogin.class.getName()).log(Level.SEVERE, null, ex);
        } catch (XPathExpressionException ex) {
            Logger.getLogger(GeneralUserLogin.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtUserCode = new javax.swing.JTextField();
        txtUserName = new javax.swing.JTextField();
        txtPw = new javax.swing.JPasswordField();
        btnLogIn = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        jPanel1.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentResized(java.awt.event.ComponentEvent evt) {
                jPanel1ComponentResized(evt);
            }
        });
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtUserCode.setBackground(new java.awt.Color(74, 138, 240));
        txtUserCode.setFont(new java.awt.Font("Ubuntu", 1, 24)); // NOI18N
        txtUserCode.setForeground(java.awt.Color.white);
        txtUserCode.setBorder(null);
        txtUserCode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUserCodeActionPerformed(evt);
            }
        });
        jPanel1.add(txtUserCode, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 250, 560, 60));

        txtUserName.setBackground(new java.awt.Color(74, 138, 240));
        txtUserName.setFont(new java.awt.Font("Ubuntu", 1, 24)); // NOI18N
        txtUserName.setForeground(java.awt.Color.white);
        txtUserName.setBorder(null);
        jPanel1.add(txtUserName, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 350, 560, 60));

        txtPw.setBackground(new java.awt.Color(74, 138, 240));
        txtPw.setFont(new java.awt.Font("Ubuntu", 1, 24)); // NOI18N
        txtPw.setForeground(java.awt.Color.white);
        txtPw.setBorder(null);
        txtPw.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPwActionPerformed(evt);
            }
        });
        jPanel1.add(txtPw, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 450, 560, 60));

        btnLogIn.setBackground(new java.awt.Color(74, 138, 240));
        btnLogIn.setFont(new java.awt.Font("Iskoola Pota", 1, 24)); // NOI18N
        btnLogIn.setForeground(java.awt.Color.white);
        btnLogIn.setText("Login");
        btnLogIn.setBorder(null);
        btnLogIn.setBorderPainted(false);
        btnLogIn.setContentAreaFilled(false);
        btnLogIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogInActionPerformed(evt);
            }
        });
        jPanel1.add(btnLogIn, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 550, 210, 60));

        btnExit.setBackground(new java.awt.Color(74, 138, 240));
        btnExit.setFont(new java.awt.Font("Iskoola Pota", 1, 24)); // NOI18N
        btnExit.setForeground(java.awt.Color.white);
        btnExit.setText("Exit");
        btnExit.setBorder(null);
        btnExit.setBorderPainted(false);
        btnExit.setContentAreaFilled(false);
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });
        jPanel1.add(btnExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(1070, 550, 220, 60));

        jLabel14.setFont(new java.awt.Font("Iskoola Pota", 0, 18)); // NOI18N
        jLabel14.setForeground(java.awt.Color.white);
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel14.setText("jLabel4");
        jLabel14.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 250, 200, 60));

        jLabel11.setFont(new java.awt.Font("Iskoola Pota", 0, 18)); // NOI18N
        jLabel11.setForeground(java.awt.Color.white);
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel11.setText("jLabel2");
        jLabel11.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 340, 200, 70));

        jLabel12.setFont(new java.awt.Font("Iskoola Pota", 0, 18)); // NOI18N
        jLabel12.setForeground(java.awt.Color.white);
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel12.setText("jLabel2");
        jLabel12.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 440, 200, 70));

        jLabel4.setFont(new java.awt.Font("Iskoola Pota", 1, 36)); // NOI18N
        jLabel4.setForeground(java.awt.Color.white);
        jLabel4.setText("jLabel2");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 570, 70));

        jLabel3.setFont(new java.awt.Font("Iskoola Pota", 0, 18)); // NOI18N
        jLabel3.setForeground(java.awt.Color.white);
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel3.setText("jLabel3");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 20, 580, 40));

        jLabel5.setForeground(java.awt.Color.white);
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel5.setText("jLabel5");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(1150, 670, 190, 30));

        jButton1.setBackground(new java.awt.Color(74, 138, 240));
        jButton1.setFont(new java.awt.Font("Iskoola Pota", 0, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/private-xl.png"))); // NOI18N
        jButton1.setText("       මුර පදය වෙනස් කරගන්න");
        jButton1.setContentAreaFilled(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 556, 330, 70));

        jLabel1.setFont(new java.awt.Font("Ubuntu", 1, 24)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/login_screen1-min.png"))); // NOI18N
        jLabel1.setBorder(null);
        jLabel1.setIconTextGap(0);
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1386, 701));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jPanel1ComponentResized(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jPanel1ComponentResized
//        try {
//            Dimension size = jPanel1.getSize();
//            
//            jLabel1.setSize(size);
//            
//            jLabel1.setIcon(new ImageIcon(ImageIO.read(getClass().getResource("/Image/login_screen1-min.png")).getScaledInstance(jPanel1.getWidth(), jPanel1.getHeight(), Image.SCALE_SMOOTH)));
//        } catch (IOException ex) {
//            Logger.getLogger(GeneralUserLogin.class.getName()).log(Level.SEVERE, null, ex);
//        }
    }//GEN-LAST:event_jPanel1ComponentResized

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnExitActionPerformed
    public static Map<Integer, User> userLevel;
    private void txtUserCodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUserCodeActionPerformed
        try {
            List<Object> inputs = new ArrayList<>();
            inputs.add(txtUserCode.getText());
            inputs.add(data.getBranchID());
            inputs.add("@password");
            inputs.add("@username");
            inputs.add("@userid");
            userData = ServerConnection.getServerConnector().searchResultsWithOutputs(inputs, "ssp_F28_LoadCombo_UserLoging", 3);
            if (userData.isEmpty()) {;
                JOptionPane.showMessageDialog(this, textBundle.getTextBundle().getString("noSuchUser"));
            } else if (userData.get(0) == null) {
                JOptionPane.showMessageDialog(this, textBundle.getTextBundle().getString("noSuchUser"), textBundle.getTextBundle().getString("notFound"), JOptionPane.WARNING_MESSAGE);
            } else {
                txtUserName.setText(userData.get(1).toString());
                data.setUserCode(txtUserCode.getText());
                data.setUsername(txtUserName.getText());
                data.setUserID(Integer.parseInt(userData.get(2).toString()));
                txtPw.setEditable(true);
                txtPw.grabFocus();
            }

            List<Object> uid = new ArrayList<>();
            uid.add(data.getUserID());
            List<List<Object>> outputs = ServerConnection.getServerConnector().searchMultipleResults(uid, "ssp_F28_LoadCombo_ViewPermission", 7);
            userLevel = new HashMap<Integer, User>();
            for (List<Object> list : outputs) {
                int levelID = Integer.parseInt(String.valueOf(list.get(0)));
                boolean b1 = Integer.parseInt(String.valueOf(list.get(1))) != 0;
                boolean b2 = Integer.parseInt(String.valueOf(list.get(2))) != 0;
                boolean b3 = Integer.parseInt(String.valueOf(list.get(3))) != 0;
                boolean b4 = Integer.parseInt(String.valueOf(list.get(4))) != 0;
                boolean b5 = Integer.parseInt(String.valueOf(list.get(5))) != 0;
                boolean b6 = Integer.parseInt(String.valueOf(list.get(6))) != 0;
                User user = new User(levelID, b1, b2, b3, b4, b5, b6);
                userLevel.put(levelID, user);
                System.out.println(levelID);
            }
//            for (Map.Entry<Integer, User> entry : userLevel.entrySet()) {
//                Integer key = entry.getKey();
//                User value = entry.getValue();
//                System.out.println("key"+key);
//                for (Map.Entry<Integer, User> entry1 : userLevel.entrySet()) {
//                    Integer key1 = entry1.getKey();
//                    User value1 = entry1.getValue();
//                    System.out.println(key1+" : "+value1);
//                }
//            }

        } catch (ConnectException ex) {
            JOptionPane.showMessageDialog(this, textBundle.getTextBundle().getString("connRefused"));
            ex.printStackTrace();
        } catch (RemoteException ex) {
            JOptionPane.showMessageDialog(this, textBundle.getTextBundle().getString("connRefused"));
        } catch (SQLException ex) {
            Logger.getLogger(GeneralUserLogin.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(GeneralUserLogin.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_txtUserCodeActionPerformed

    private void txtPwActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPwActionPerformed
        logIn();
    }//GEN-LAST:event_txtPwActionPerformed

    private void btnLogInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogInActionPerformed
        logIn();
    }//GEN-LAST:event_btnLogInActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        new ChangeUserPassword(this, true).setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GeneralUserLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GeneralUserLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GeneralUserLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GeneralUserLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GeneralUserLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnLogIn;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField txtPw;
    private javax.swing.JTextField txtUserCode;
    private javax.swing.JTextField txtUserName;
    // End of variables declaration//GEN-END:variables
private void logIn() {
        char[] password = txtPw.getPassword();
        String userCode = txtUserCode.getText();

        String txtpassword = "";
        for (char pw : password) {
            txtpassword += pw;
        }
        if ("".equals(txtpassword)) {
            JOptionPane.showMessageDialog(this, textBundle.getTextBundle().getString("enterPassword"), "No Password", JOptionPane.WARNING_MESSAGE);
        } else if (txtpassword.equals(userData.get(0).toString())) {
            SystemParameterList.getParameterList();
            if (Integer.parseInt(String.valueOf(SystemParameterList.parameters.get("n9B_FormatType"))) != 1) {
                data.setB9old(true);
            } else {
                data.setB9old(false);
            }
            if (Integer.parseInt(String.valueOf(SystemParameterList.parameters.get("nPayment16BCheck"))) != 1) {
                data.setB16(false);
            } else {
                data.setB16(true);
            }
            if (Integer.parseInt(String.valueOf(SystemParameterList.parameters.get("n16BAutoAddFroPayments"))) == 1) {
                data.setB16AutoAddFroPayments(true);
            } else {
                data.setB16AutoAddFroPayments(false);
            }
            if (Integer.parseInt(String.valueOf(SystemParameterList.parameters.get("nHostingType"))) == 0) {
                data.setWebHosted(true);
            } else {
                data.setWebHosted(false);
            }
            new GeneralDateSettingsBackground().setVisible(true);
            this.dispose();
        }
    }

    private void setTexts() {
        jLabel4.setText(textBundle.getTextBundle().getString("LoginTitle"));
        jLabel3.setText(textBundle.getTextBundle().getString("bussinessName"));
        jLabel14.setText(textBundle.getTextBundle().getString("usercode"));
        jLabel11.setText(textBundle.getTextBundle().getString("username"));
        jLabel12.setText(textBundle.getTextBundle().getString("password"));
        btnLogIn.setText(textBundle.getTextBundle().getString("login"));
        btnExit.setText(textBundle.getTextBundle().getString("exit"));
    }
}
