/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.nbs.view.common;

import Sources.KeyBoard;
import Sources.User;
import com.nbs.admin.ParameterList;
import com.nbs.constants.AccessLevels;
import com.nbs.impl.ServerConnection;
import com.nbs.view.Member.MemberOperational;
import static com.nbs.view.common.GeneralUserLogin.data;
import com.nbs.view.common.search.GeneralCheckGLTransactions;
import com.nbs.view.manager.GLTree;
import com.nbs.view.manager.ManagerOperational;
import java.awt.Cursor;
import java.rmi.RemoteException;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.BorderFactory;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.border.BevelBorder;

/**
 *
 * @author mmh
 */
public class GeneralHomeView extends javax.swing.JFrame {

    /**
     * Creates new form HomeView
     *
     */
    public GeneralHomeView() {

        initComponents();
        
        setTitle("Server on " + data.getIP());
        List<Object> inputs = new ArrayList<>();
        try {
            inputs.add(1);
            inputs.add(0);
            List<Object> output = ServerConnection.getServerConnector().searchSingleResult(inputs, "ssp_F28_LoadCombo_SysParameter", 7);

            lable1Name.setText(String.valueOf(output.get(0)) + " - ");
            lable1Value.setText(String.valueOf(output.get(1)));
            lable2Name.setText(String.valueOf(output.get(2)) + " - ");
            lable2Value.setText(String.valueOf(output.get(3)));
            lable3Name.setText(String.valueOf(output.get(4)) + " - ");
            lable3Value.setText(String.valueOf(output.get(5)));

            GeneralUserLogin.data.setBranchName(String.valueOf(output.get(6)));
        } catch (SQLException ex) {
            Logger.getLogger(GeneralHomeView.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(GeneralHomeView.class.getName()).log(Level.SEVERE, null, ex);
        } catch (RemoteException ex) {
            Logger.getLogger(GeneralHomeView.class.getName()).log(Level.SEVERE, null, ex);
        }

        time();
        this.setExtendedState(this.getExtendedState() | JFrame.MAXIMIZED_BOTH);
        GeneralUserLogin.data.setFromHome(true);
//        jButton1.setUI(new VerticalButtonUI(90));
//        jButton1.setText("<html>m%d<br>foa<br>Ys<br>l<br>$<br>.<br>n<br>vd<br>f;d<br>.<br>md<br>,<br>k<br>h</html>");
    }

    public void time() {
        new Thread() {
            public void run() {
            }
        }.start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar2 = new javax.swing.JMenuBar();
        teller = new javax.swing.JMenu();
        daily_collection = new javax.swing.JMenu();
        jPanel1 = new org.jdesktop.swingx.JXImagePanel();
        btnPawnOprator = new javax.swing.JButton();
        btnGLOperator = new javax.swing.JButton();
        btnSavingsOperat = new javax.swing.JButton();
        btnAdmin = new javax.swing.JButton();
        btnAuditor = new javax.swing.JButton();
        btnCashier = new javax.swing.JButton();
        btnManager = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btnStock = new javax.swing.JButton();
        CLOCK = new javax.swing.JLabel();
        btnPayments = new javax.swing.JButton();
        btnManager1 = new javax.swing.JButton();
        lable3Name = new javax.swing.JLabel();
        lable3Value = new javax.swing.JLabel();
        lable2Name = new javax.swing.JLabel();
        lable2Value = new javax.swing.JLabel();
        lable1Value = new javax.swing.JLabel();
        lable1Name = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem10 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem9 = new javax.swing.JMenuItem();

        teller.setText("File");
        teller.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tellerActionPerformed(evt);
            }
        });
        jMenuBar2.add(teller);

        daily_collection.setText("Edit");
        jMenuBar2.add(daily_collection);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAutoRequestFocus(false);

        jPanel1.setBackground(new java.awt.Color(100, 22, 84));
        jPanel1.setImage(new javax.swing.ImageIcon(getClass().getResource("/Image/home-min.png")).getImage());

        btnPawnOprator.setBackground(new java.awt.Color(30, 101, 58));
        btnPawnOprator.setFont(new java.awt.Font("AMALEE", 1, 24)); // NOI18N
        btnPawnOprator.setForeground(java.awt.Color.white);
        btnPawnOprator.setText("c¾k, igyka");
        btnPawnOprator.setBorder(null);
        btnPawnOprator.setBorderPainted(false);
        btnPawnOprator.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnPawnOpratorMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnPawnOpratorMouseEntered(evt);
            }
        });
        btnPawnOprator.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPawnOpratorActionPerformed(evt);
            }
        });

        btnGLOperator.setBackground(new java.awt.Color(127, 42, 25));
        btnGLOperator.setFont(new java.awt.Font("Iskoola Pota", 1, 18)); // NOI18N
        btnGLOperator.setForeground(java.awt.Color.white);
        btnGLOperator.setText("GL");
        btnGLOperator.setBorder(null);
        btnGLOperator.setBorderPainted(false);
        btnGLOperator.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnGLOperatorMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnGLOperatorMouseEntered(evt);
            }
        });
        btnGLOperator.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGLOperatorActionPerformed(evt);
            }
        });

        btnSavingsOperat.setBackground(new java.awt.Color(74, 138, 240));
        btnSavingsOperat.setFont(new java.awt.Font("AMALEE", 1, 24)); // NOI18N
        btnSavingsOperat.setForeground(java.awt.Color.white);
        btnSavingsOperat.setText(".%dóh nexl= wxYh");
        btnSavingsOperat.setBorder(null);
        btnSavingsOperat.setBorderPainted(false);
        btnSavingsOperat.setInheritsPopupMenu(true);
        btnSavingsOperat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnSavingsOperatMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnSavingsOperatMouseEntered(evt);
            }
        });
        btnSavingsOperat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSavingsOperatActionPerformed(evt);
            }
        });

        btnAdmin.setBackground(new java.awt.Color(36, 71, 17));
        btnAdmin.setFont(new java.awt.Font("Iskoola Pota", 1, 18)); // NOI18N
        btnAdmin.setForeground(java.awt.Color.white);
        btnAdmin.setText("ADMIN");
        btnAdmin.setBorder(null);
        btnAdmin.setBorderPainted(false);
        btnAdmin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnAdminMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnAdminMouseEntered(evt);
            }
        });
        btnAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdminActionPerformed(evt);
            }
        });

        btnAuditor.setBackground(new java.awt.Color(78, 15, 110));
        btnAuditor.setFont(new java.awt.Font("Iskoola Pota", 1, 18)); // NOI18N
        btnAuditor.setForeground(java.awt.Color.white);
        btnAuditor.setText("AUDIT");
        btnAuditor.setBorder(null);
        btnAuditor.setBorderPainted(false);
        btnAuditor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnAuditorMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnAuditorMouseEntered(evt);
            }
        });
        btnAuditor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAuditorActionPerformed(evt);
            }
        });

        btnCashier.setBackground(new java.awt.Color(229, 161, 30));
        btnCashier.setFont(new java.awt.Font("AMALEE", 1, 24)); // NOI18N
        btnCashier.setForeground(java.awt.Color.white);
        btnCashier.setText("<html><center>uqo,a whleñ<br>,eîï</center></html>");
        btnCashier.setBorder(null);
        btnCashier.setBorderPainted(false);
        btnCashier.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnCashier.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnCashierMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnCashierMouseEntered(evt);
            }
        });
        btnCashier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCashierActionPerformed(evt);
            }
        });

        btnManager.setBackground(new java.awt.Color(232, 138, 5));
        btnManager.setFont(new java.awt.Font("AMALEE", 0, 24)); // NOI18N
        btnManager.setForeground(java.awt.Color.white);
        btnManager.setText("l<uKdlre");
        btnManager.setBorder(null);
        btnManager.setBorderPainted(false);
        btnManager.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnManagerMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnManagerMouseEntered(evt);
            }
        });
        btnManager.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManagerActionPerformed(evt);
            }
        });

        jLabel1.setBackground(new java.awt.Color(53, 81, 126));
        jLabel1.setFont(new java.awt.Font("Bell MT", 3, 36)); // NOI18N
        jLabel1.setForeground(java.awt.Color.white);
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel1.setText("nbsERP - Accounting System - F28");

        btnStock.setBackground(new java.awt.Color(45, 45, 20));
        btnStock.setFont(new java.awt.Font("AMALEE", 1, 24)); // NOI18N
        btnStock.setForeground(java.awt.Color.white);
        btnStock.setText("<html><center>m%dfoaYsl$<br>.nvd f;d.<br> md,kh</center></html>");
        btnStock.setBorderPainted(false);
        btnStock.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnStockMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnStockMouseEntered(evt);
            }
        });
        btnStock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStockActionPerformed(evt);
            }
        });

        CLOCK.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 15)); // NOI18N
        CLOCK.setForeground(new java.awt.Color(254, 247, 247));

        btnPayments.setBackground(new java.awt.Color(194, 148, 79));
        btnPayments.setFont(new java.awt.Font("AMALEE", 1, 24)); // NOI18N
        btnPayments.setForeground(java.awt.Color.white);
        btnPayments.setText("f.ùï");
        btnPayments.setBorder(null);
        btnPayments.setBorderPainted(false);
        btnPayments.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/lableicon/pawing.png"))); // NOI18N
        btnPayments.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnPaymentsMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnPaymentsMouseEntered(evt);
            }
        });
        btnPayments.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPaymentsActionPerformed(evt);
            }
        });

        btnManager1.setBackground(java.awt.Color.blue);
        btnManager1.setFont(new java.awt.Font("AMALEE", 0, 24)); // NOI18N
        btnManager1.setForeground(java.awt.Color.white);
        btnManager1.setText("idudðl kduf,aLKh");
        btnManager1.setBorder(null);
        btnManager1.setBorderPainted(false);
        btnManager1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnManager1MouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnManager1MouseEntered(evt);
            }
        });
        btnManager1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManager1ActionPerformed(evt);
            }
        });

        lable3Name.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 15)); // NOI18N
        lable3Name.setForeground(java.awt.Color.white);
        lable3Name.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lable3Name.setText("BRANCH CODE   -");

        lable3Value.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 15)); // NOI18N
        lable3Value.setForeground(java.awt.Color.white);
        lable3Value.setText("CODE");

        lable2Name.setBackground(java.awt.Color.white);
        lable2Name.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 15)); // NOI18N
        lable2Name.setForeground(java.awt.Color.white);
        lable2Name.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lable2Name.setText("RURAL BANK     -");

        lable2Value.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 15)); // NOI18N
        lable2Value.setForeground(java.awt.Color.white);
        lable2Value.setText("LUNUGALA");

        lable1Value.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 15)); // NOI18N
        lable1Value.setForeground(java.awt.Color.white);
        lable1Value.setText("PASSARA");

        lable1Name.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 15)); // NOI18N
        lable1Name.setForeground(java.awt.Color.white);
        lable1Name.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lable1Name.setText("M.P.C.S.            -");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnStock, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnCashier, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnSavingsOperat, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(10, 10, 10)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnPayments, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnPawnOprator, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(100, 100, 100)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnManager1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnManager, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(40, 40, 40)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnGLOperator, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnAuditor, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 737, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(CLOCK, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lable1Name, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lable3Name, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lable2Name, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lable2Value, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lable1Value, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lable3Value, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(4, 4, 4)
                        .addComponent(CLOCK, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lable1Value, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lable1Name))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lable2Value, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lable2Name, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lable3Name, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lable3Value, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(86, 86, 86)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnPayments, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                            .addComponent(btnManager, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnPawnOprator, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                            .addComponent(btnManager1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btnAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(20, 20, 20)
                                .addComponent(btnGLOperator, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(20, 20, 20)
                                .addComponent(btnAuditor, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(btnStock, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 366, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(btnCashier, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(btnSavingsOperat, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        jMenuBar1.setBackground(new java.awt.Color(123, 10, 82));
        jMenuBar1.setForeground(new java.awt.Color(254, 254, 254));

        jMenu1.setBackground(new java.awt.Color(123, 10, 82));
        jMenu1.setForeground(new java.awt.Color(254, 254, 254));
        jMenu1.setText("Home");

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F1, 0));
        jMenuItem1.setBackground(new java.awt.Color(123, 10, 82));
        jMenuItem1.setForeground(new java.awt.Color(254, 254, 254));
        jMenuItem1.setText("Teller");
        jMenuItem1.setFocusPainted(true);
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem10.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F2, 0));
        jMenuItem10.setBackground(new java.awt.Color(123, 10, 82));
        jMenuItem10.setForeground(new java.awt.Color(254, 254, 254));
        jMenuItem10.setText("Daily C0llection");
        jMenuItem10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem10ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem10);

        jMenuItem2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F3, 0));
        jMenuItem2.setBackground(new java.awt.Color(123, 10, 82));
        jMenuItem2.setForeground(new java.awt.Color(254, 254, 254));
        jMenuItem2.setText("Saving");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuItem3.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, 0));
        jMenuItem3.setBackground(new java.awt.Color(123, 10, 82));
        jMenuItem3.setForeground(new java.awt.Color(254, 254, 254));
        jMenuItem3.setText("Loan");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem3);

        jMenuItem4.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F5, 0));
        jMenuItem4.setBackground(new java.awt.Color(123, 10, 82));
        jMenuItem4.setForeground(new java.awt.Color(254, 254, 254));
        jMenuItem4.setText("Pawing");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem4);

        jMenuItem5.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F6, 0));
        jMenuItem5.setBackground(new java.awt.Color(123, 10, 82));
        jMenuItem5.setForeground(new java.awt.Color(254, 254, 254));
        jMenuItem5.setText("Manager");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem5);

        jMenuItem6.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F7, 0));
        jMenuItem6.setBackground(new java.awt.Color(123, 10, 82));
        jMenuItem6.setForeground(new java.awt.Color(254, 254, 254));
        jMenuItem6.setText("Admin");
        jMenu1.add(jMenuItem6);

        jMenuItem7.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F8, 0));
        jMenuItem7.setBackground(new java.awt.Color(123, 10, 82));
        jMenuItem7.setForeground(new java.awt.Color(254, 254, 254));
        jMenuItem7.setText("GL");
        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem7ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem7);

        jMenuItem8.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F9, 0));
        jMenuItem8.setBackground(new java.awt.Color(123, 10, 82));
        jMenuItem8.setForeground(new java.awt.Color(254, 254, 254));
        jMenuItem8.setText("Audit");
        jMenu1.add(jMenuItem8);

        jMenuBar1.add(jMenu1);

        jMenu2.setBackground(new java.awt.Color(123, 10, 82));
        jMenu2.setForeground(new java.awt.Color(254, 254, 254));
        jMenu2.setText("Sign Out");

        jMenuItem9.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem9.setBackground(new java.awt.Color(123, 10, 82));
        jMenuItem9.setForeground(new java.awt.Color(254, 254, 254));
        jMenuItem9.setText("Sign Out");
        jMenuItem9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem9ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem9);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPawnOpratorMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPawnOpratorMouseEntered
        setCursor(Cursor.HAND_CURSOR);

        btnPawnOprator.setBorder(BorderFactory.createBevelBorder(BevelBorder.RAISED));
    }//GEN-LAST:event_btnPawnOpratorMouseEntered

    private void btnPawnOpratorMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPawnOpratorMouseExited
        setCursor(Cursor.DEFAULT_CURSOR);

        btnPawnOprator.setBorder(null);
    }//GEN-LAST:event_btnPawnOpratorMouseExited

    private void btnPawnOpratorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPawnOpratorActionPerformed

        if (GeneralUserLogin.userLevel.containsKey(AccessLevels.JOURNAL)) {
            User user = GeneralUserLogin.userLevel.get(AccessLevels.JOURNAL);
            if (user.isAddable() || user.isCheckable() || user.isConfirmable() || user.isEditable() || user.isSupevisable() || user.isViewable()) {
                new ManagerOperational(btnSavingsOperat.getText(), AccessLevels.JOURNAL,user).setVisible(true);
            } else {
                JOptionPane.showMessageDialog(this, "ඔබට අවසර නොමැත ... !!!");
            }
        } else {
            JOptionPane.showMessageDialog(this, "ඔබට අවසර නොමැත ... !!!");
        }

    }//GEN-LAST:event_btnPawnOpratorActionPerformed

    private void btnGLOperatorMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGLOperatorMouseEntered
        setCursor(Cursor.HAND_CURSOR);
        btnGLOperator.setBorder(BorderFactory.createBevelBorder(BevelBorder.RAISED));
    }//GEN-LAST:event_btnGLOperatorMouseEntered

    private void btnGLOperatorMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGLOperatorMouseExited
        setCursor(Cursor.DEFAULT_CURSOR);
        btnGLOperator.setBorder(null);
    }//GEN-LAST:event_btnGLOperatorMouseExited

    private void btnGLOperatorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGLOperatorActionPerformed
        if (GeneralUserLogin.userLevel.containsKey(AccessLevels.GL)) {
            User user = GeneralUserLogin.userLevel.get(AccessLevels.GL);
            if (user.isAddable() || user.isCheckable() || user.isConfirmable() || user.isEditable() || user.isSupevisable() || user.isViewable()) {
                new GLTree(AccessLevels.GL).setVisible(true);
            } else {
                JOptionPane.showMessageDialog(this, "ඔබට අවසර නොමැත ... !!!");
            }
        } else {
            JOptionPane.showMessageDialog(this, "ඔබට අවසර නොමැත ... !!!");
        }
        
    }//GEN-LAST:event_btnGLOperatorActionPerformed

    private void btnSavingsOperatMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSavingsOperatMouseEntered
        setCursor(Cursor.HAND_CURSOR);
        btnSavingsOperat.setBorder(BorderFactory.createBevelBorder(BevelBorder.RAISED));
    }//GEN-LAST:event_btnSavingsOperatMouseEntered

    private void btnSavingsOperatMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSavingsOperatMouseExited
        setCursor(Cursor.DEFAULT_CURSOR);
        btnSavingsOperat.setBorder(null);
    }//GEN-LAST:event_btnSavingsOperatMouseExited

    private void btnSavingsOperatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSavingsOperatActionPerformed
        if (GeneralUserLogin.userLevel.containsKey(AccessLevels.RURALBANKS)) {
            User user = GeneralUserLogin.userLevel.get(AccessLevels.RURALBANKS);
            if (user.isAddable() || user.isCheckable() || user.isConfirmable() || user.isEditable() || user.isSupevisable() || user.isViewable()) {
                new ManagerOperational(btnSavingsOperat.getText(), AccessLevels.RURALBANKS,user).setVisible(true);
            } else {
                JOptionPane.showMessageDialog(this, "ඔබට අවසර නොමැත ... !!!");
            }
        } else {
            JOptionPane.showMessageDialog(this, "ඔබට අවසර නොමැත ... !!!");
        }

    }//GEN-LAST:event_btnSavingsOperatActionPerformed

    private void btnAdminMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAdminMouseEntered
        setCursor(Cursor.HAND_CURSOR);
        btnAdmin.setBorder(BorderFactory.createBevelBorder(BevelBorder.RAISED));
    }//GEN-LAST:event_btnAdminMouseEntered

    private void btnAdminMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAdminMouseExited
        setCursor(Cursor.DEFAULT_CURSOR);
        btnAdmin.setBorder(null);
    }//GEN-LAST:event_btnAdminMouseExited

    private void btnAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdminActionPerformed
        if (GeneralUserLogin.userLevel.containsKey(AccessLevels.ADMIN)) {
            User user = GeneralUserLogin.userLevel.get(AccessLevels.ADMIN);
            if (user.isAddable() || user.isCheckable() || user.isConfirmable() || user.isEditable() || user.isSupevisable() || user.isViewable()) {
                new ParameterList().setVisible(true);
            } else {
                JOptionPane.showMessageDialog(this, "ඔබට අවසර නොමැත ... !!!");
            }
        } else {
            JOptionPane.showMessageDialog(this, "ඔබට අවසර නොමැත ... !!!");
        }
        
    }//GEN-LAST:event_btnAdminActionPerformed

    private void btnAuditorMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAuditorMouseEntered
        setCursor(Cursor.HAND_CURSOR);
        btnAuditor.setBorder(BorderFactory.createBevelBorder(BevelBorder.RAISED));
    }//GEN-LAST:event_btnAuditorMouseEntered

    private void btnAuditorMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAuditorMouseExited
        setCursor(Cursor.DEFAULT_CURSOR);
        btnAuditor.setBorder(null);
    }//GEN-LAST:event_btnAuditorMouseExited

    private void btnAuditorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAuditorActionPerformed

    }//GEN-LAST:event_btnAuditorActionPerformed

    private void btnCashierMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCashierMouseEntered
        setCursor(Cursor.HAND_CURSOR);
        btnCashier.setBorder(BorderFactory.createBevelBorder(BevelBorder.RAISED));
    }//GEN-LAST:event_btnCashierMouseEntered

    private void btnCashierMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCashierMouseExited
        setCursor(Cursor.DEFAULT_CURSOR);
        btnCashier.setBorder(null);
    }//GEN-LAST:event_btnCashierMouseExited

    private void btnCashierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCashierActionPerformed
        if (GeneralUserLogin.userLevel.containsKey(AccessLevels.CHASHIER)) {
            User user = GeneralUserLogin.userLevel.get(AccessLevels.CHASHIER);
            if (user.isAddable() || user.isCheckable() || user.isConfirmable() || user.isEditable() || user.isSupevisable() || user.isViewable()) {
                new ManagerOperational(btnCashier.getText(), AccessLevels.CHASHIER,user).setVisible(true);
            } else {
                JOptionPane.showMessageDialog(this, "ඔබට අවසර නොමැත ... !!!");
            }
        } else {
            JOptionPane.showMessageDialog(this, "ඔබට අවසර නොමැත ... !!!");
        }
    }//GEN-LAST:event_btnCashierActionPerformed

    private void btnManagerMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnManagerMouseEntered
        setCursor(Cursor.HAND_CURSOR);
        btnManager.setBorder(BorderFactory.createBevelBorder(BevelBorder.RAISED));
    }//GEN-LAST:event_btnManagerMouseEntered

    private void btnManagerMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnManagerMouseExited
        setCursor(Cursor.DEFAULT_CURSOR);
        btnManager.setBorder(null);
    }//GEN-LAST:event_btnManagerMouseExited

    private void btnManagerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManagerActionPerformed
        if (GeneralUserLogin.userLevel.containsKey(AccessLevels.MANAGER)) {
            User user = GeneralUserLogin.userLevel.get(AccessLevels.MANAGER);
            if (user.isAddable() || user.isCheckable() || user.isConfirmable() || user.isEditable() || user.isSupevisable() || user.isViewable()) {
                new ManagerOperational(AccessLevels.MANAGER,user).setVisible(true);
            } else {
                JOptionPane.showMessageDialog(this, "ඔබට අවසර නොමැත ... !!!");
            }
        } else {
            JOptionPane.showMessageDialog(this, "ඔබට අවසර නොමැත ... !!!");
        }        
        
    }//GEN-LAST:event_btnManagerActionPerformed

    private void btnStockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStockActionPerformed
        if (GeneralUserLogin.userLevel.containsKey(AccessLevels.STOCK)) {
            User user = GeneralUserLogin.userLevel.get(AccessLevels.STOCK);
            if (user.isAddable() || user.isCheckable() || user.isConfirmable() || user.isEditable() || user.isSupevisable() || user.isViewable()) {
                new ManagerOperational(btnStock.getText(), AccessLevels.STOCK,user).setVisible(true);
            } else {
                JOptionPane.showMessageDialog(this, "ඔබට අවසර නොමැත ... !!!");
            }
        } else {
            JOptionPane.showMessageDialog(this, "ඔබට අවසර නොමැත ... !!!");
        }
    }//GEN-LAST:event_btnStockActionPerformed

    private void btnStockMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnStockMouseEntered
        btnStock.setBorder(BorderFactory.createBevelBorder(BevelBorder.RAISED));

    }//GEN-LAST:event_btnStockMouseEntered

    private void btnStockMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnStockMouseExited
        btnStock.setBorder(null);
    }//GEN-LAST:event_btnStockMouseExited

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed

    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed

    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed

    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed

    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed

    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed

    }//GEN-LAST:event_jMenuItem7ActionPerformed

    private void btnPaymentsMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPaymentsMouseExited
        setCursor(Cursor.DEFAULT_CURSOR);
        btnPayments.setBorder(null);
    }//GEN-LAST:event_btnPaymentsMouseExited

    private void btnPaymentsMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPaymentsMouseEntered
        setCursor(Cursor.HAND_CURSOR);
        btnPayments.setBorder(BorderFactory.createBevelBorder(BevelBorder.RAISED));


    }//GEN-LAST:event_btnPaymentsMouseEntered

    private void btnPaymentsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPaymentsActionPerformed
//        if (GeneralUserLogin.userLevel.containsKey(AccessLevels.PAYMENTS) && GeneralUserLogin.userLevel.containsKey(AccessLevels.CHEQUE)) {
//            User user = GeneralUserLogin.userLevel.get(AccessLevels.CHEQUE);
//            if (user.isAddable() || user.isCheckable() || user.isConfirmable() || user.isEditable() || user.isSupevisable() || user.isViewable()) {
//                new ManagerOperational(btnPayments.getText(), AccessLevels.PAYMENTS,user).setVisible(true);
//            } else {
//                JOptionPane.showMessageDialog(this, "ඔබට අවසර නොමැත ... !!!");
//                System.out.println("lol");
//            }
//        }else
            if (GeneralUserLogin.userLevel.containsKey(AccessLevels.PAYMENTS)) {
            User user = GeneralUserLogin.userLevel.get(AccessLevels.PAYMENTS);
            if (user.isAddable() || user.isCheckable() || user.isConfirmable() || user.isEditable() || user.isSupevisable() || user.isViewable()) {
                new ManagerOperational(btnPayments.getText(), AccessLevels.PAYMENTS,user).setVisible(true);
            } else {
                JOptionPane.showMessageDialog(this, "ඔබට අවසර නොමැත ... !!!");
            }
        }  else {
            JOptionPane.showMessageDialog(this, "ඔබට අවසර නොමැත ... !!!");
        }
    }//GEN-LAST:event_btnPaymentsActionPerformed

    private void jMenuItem10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem10ActionPerformed

    }//GEN-LAST:event_jMenuItem10ActionPerformed

    private void jMenuItem9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem9ActionPerformed
        new GeneralUserLogin().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jMenuItem9ActionPerformed

    private void tellerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tellerActionPerformed

    }//GEN-LAST:event_tellerActionPerformed

    private void btnManager1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnManager1MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_btnManager1MouseExited

    private void btnManager1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnManager1MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btnManager1MouseEntered

    private void btnManager1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManager1ActionPerformed
        if (GeneralUserLogin.userLevel.containsKey(AccessLevels.MEMBER)) {
            User user = GeneralUserLogin.userLevel.get(AccessLevels.MEMBER);
            if (user.isAddable() || user.isCheckable() || user.isConfirmable() || user.isEditable() || user.isSupevisable() || user.isViewable()) {
                new MemberOperational(AccessLevels.MEMBER,user).setVisible(true);
            } else {
                JOptionPane.showMessageDialog(this, "ඔබට අවසර නොමැත ... !!!");
            }
        } else {
            JOptionPane.showMessageDialog(this, "ඔබට අවසර නොමැත ... !!!");
        }        
    }//GEN-LAST:event_btnManager1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */

        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {

                new GeneralHomeView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel CLOCK;
    private javax.swing.JButton btnAdmin;
    private javax.swing.JButton btnAuditor;
    private javax.swing.JButton btnCashier;
    private javax.swing.JButton btnGLOperator;
    private javax.swing.JButton btnManager;
    private javax.swing.JButton btnManager1;
    private javax.swing.JButton btnPawnOprator;
    private javax.swing.JButton btnPayments;
    private javax.swing.JButton btnSavingsOperat;
    private javax.swing.JButton btnStock;
    private javax.swing.JMenu daily_collection;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem9;
    private org.jdesktop.swingx.JXImagePanel jPanel1;
    private javax.swing.JLabel lable1Name;
    private javax.swing.JLabel lable1Value;
    private javax.swing.JLabel lable2Name;
    private javax.swing.JLabel lable2Value;
    private javax.swing.JLabel lable3Name;
    private javax.swing.JLabel lable3Value;
    private javax.swing.JMenu teller;
    // End of variables declaration//GEN-END:variables
}
