/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

 /*
 * frm_Check_Double_Entry.java
 *
 * Created on Jun 30, 2012, 11:19:46 AM
 */
package com.nbs.view.common.search;

import Sources.TableColumnFontChanger;
import Sources.TableColumnRightAlign;
import com.nbs.impl.ServerConnection;
import java.awt.Rectangle;
import java.awt.Toolkit;
import java.rmi.RemoteException;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author mmh
 */
public class GeneralCheckGLTransactions extends javax.swing.JDialog {

    private DefaultTableModel dtm1;
    private DefaultTableModel dtm2;
    private DefaultTableModel dtm3;

    public GeneralCheckGLTransactions(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setBounds(new Rectangle(Toolkit.getDefaultToolkit().getScreenSize()));
        dtm1 = (DefaultTableModel) HDTable.getModel();
        dtm2 = (DefaultTableModel) DTTable.getModel();
        dtm3 = (DefaultTableModel) GLTable.getModel();
        int t1AmaleeIndexes[] = {5};
        int t2IskoolaPotaIndexes[] = {9};
        int t2AmaleeIndexes[] = {4, 6};
        int t3IskoolaPotaIndexes[] = {11};
        int t3AmaleeIndexes[] = {7, 10};
        int t1AlignIndexes[] = {7};
        int t2AlignIndexes[] = {10, 11};
        int t3AlignIndexes[] = {13, 14, 15, 16};
        TableColumnRightAlign.alignMany(HDTable, t1AlignIndexes);
        TableColumnRightAlign.alignMany(DTTable, t2AlignIndexes);
        TableColumnRightAlign.alignMany(GLTable, t3AlignIndexes);
        for (int t1AmaleeIndex : t1AmaleeIndexes) {
            TableColumnFontChanger.setAmalee(HDTable, t1AmaleeIndex);
        }
        for (int t2AmaleeIndex : t2AmaleeIndexes) {
            TableColumnFontChanger.setAmalee(DTTable, t2AmaleeIndex);
        }
        for (int t2IskoolaPotaIndex : t2IskoolaPotaIndexes) {
            TableColumnFontChanger.setIskolaPotha(DTTable, t2IskoolaPotaIndex);
        }
        for (int t3AmaleeIndex : t3AmaleeIndexes) {
            TableColumnFontChanger.setAmalee(GLTable, t3AmaleeIndex);
        }
        for (int t3IskoolaPotaIndex : t3IskoolaPotaIndexes) {
            TableColumnFontChanger.setIskolaPotha(GLTable, t3IskoolaPotaIndex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        HDTable = new org.jdesktop.swingx.JXTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        GLTable = new org.jdesktop.swingx.JXTable();
        jPanel5 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jDateChooser2 = new com.toedter.calendar.JDateChooser();
        txtMainID = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        DTTable = new org.jdesktop.swingx.JXTable();
        jButton1 = new javax.swing.JButton();
        optHDID = new javax.swing.JRadioButton();
        optDTID = new javax.swing.JRadioButton();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        DRCRHDTable = new org.jdesktop.swingx.JXTable();
        jScrollPane5 = new javax.swing.JScrollPane();
        DRCRDTTable = new org.jdesktop.swingx.JXTable();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane6 = new javax.swing.JScrollPane();
        E9HDTable = new org.jdesktop.swingx.JXTable();
        jScrollPane7 = new javax.swing.JScrollPane();
        E9DTTable = new org.jdesktop.swingx.JXTable();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane8 = new javax.swing.JScrollPane();
        B16HDTable = new org.jdesktop.swingx.JXTable();
        jScrollPane9 = new javax.swing.JScrollPane();
        B16DTTable = new org.jdesktop.swingx.JXTable();
        jPanel7 = new javax.swing.JPanel();
        jScrollPane10 = new javax.swing.JScrollPane();
        B9HDTable = new org.jdesktop.swingx.JXTable();
        jScrollPane11 = new javax.swing.JScrollPane();
        B9DTTable = new org.jdesktop.swingx.JXTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(java.awt.Color.white);
        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel3.setFont(new java.awt.Font("Arial", 1, 22)); // NOI18N
        jLabel3.setText("CHECK GL TRANSACTION");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(89, 89, 89)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 685, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        HDTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "nJournalHDID", "cJournalHDID", "nGLTrnID", "dTrnDate", "nSubSectionID", "cSubSectionNameSin", "nJournalStatusID", "nAmount"
            }
        ));
        HDTable.getTableHeader().setReorderingAllowed(false);
        jScrollPane2.setViewportView(HDTable);

        GLTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "nGLID", "nGLTrnID", "dTrnDate", "nJournalHDID", "nJournalDTID", "cJournalHDID", "nSubSectionID", "cSubSectionNameSin", "nOutsiderMFID", "cOutsiderNameSin", "nAcctLevelID5", "cCAAcctNo_L5", "cDescriptionUni_L5", "nCashBookDr", "nCashBookCr", "nJournalDr", "nJournalCr"
            }
        ));
        GLTable.getTableHeader().setReorderingAllowed(false);
        jScrollPane3.setViewportView(GLTable);

        jPanel5.setBackground(java.awt.Color.white);
        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(java.awt.Color.blue));

        jLabel1.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel1.setText("FROM D:");

        jLabel2.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel2.setText("TO D:");

        jButton2.setBackground(new java.awt.Color(11, 85, 189));
        jButton2.setForeground(java.awt.Color.white);
        jButton2.setText("PRINT");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(11, 85, 189));
        jButton3.setForeground(java.awt.Color.white);
        jButton3.setText("FIND OUT TRNS");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jDateChooser2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(57, 57, 57)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, 205, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jDateChooser2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );

        txtMainID.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N

        DTTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "nJournalDTID", "nJournalHDID", "cJournalHDID", "nSubSectionID", "cSubSectionNameSin", "nOutsiderMFID", "cOutsiderNameSin", "nAcctLevelID5", "cCAAcctNo_L5", "cDescriptionUni_L5", "nGLTrnID", "nDrAmount", "nCrAmount"
            }
        ));
        DTTable.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(DTTable);

        jButton1.setBackground(new java.awt.Color(11, 85, 189));
        jButton1.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        jButton1.setForeground(java.awt.Color.white);
        jButton1.setText("FIND");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        buttonGroup1.add(optHDID);
        optHDID.setSelected(true);
        optHDID.setText("HDID");

        buttonGroup1.add(optDTID);
        optDTID.setText("DTID");

        jButton10.setFont(new java.awt.Font("Iskoola Pota", 0, 18)); // NOI18N
        jButton10.setText("Update");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });

        jButton11.setFont(new java.awt.Font("Iskoola Pota", 0, 18)); // NOI18N
        jButton11.setText("Close");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(txtMainID, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(optHDID)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(optDTID)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 1057, Short.MAX_VALUE)
                    .addComponent(jScrollPane1)
                    .addComponent(jScrollPane2)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton10, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton11, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(optHDID)
                            .addComponent(optDTID))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtMainID, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton10)
                    .addComponent(jButton11))
                .addContainerGap(53, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Find GL Out", jPanel2);

        DRCRHDTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5", "Title 6", "Title 7", "Title 8"
            }
        ));
        DRCRHDTable.getTableHeader().setReorderingAllowed(false);
        jScrollPane4.setViewportView(DRCRHDTable);

        DRCRDTTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5", "Title 6", "Title 7", "Title 8", "Title 9", "Title 10", "Title 11", "Title 12", "Title 13"
            }
        ));
        DRCRDTTable.getTableHeader().setReorderingAllowed(false);
        jScrollPane5.setViewportView(DRCRDTTable);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane5)
                    .addComponent(jScrollPane4))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(391, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("DR/CR Type", jPanel3);

        E9HDTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5", "Title 6", "Title 7", "Title 8"
            }
        ));
        E9HDTable.getTableHeader().setReorderingAllowed(false);
        jScrollPane6.setViewportView(E9HDTable);

        E9DTTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5", "Title 6", "Title 7", "Title 8", "Title 9", "Title 10", "Title 11", "Title 12", "Title 13"
            }
        ));
        E9DTTable.getTableHeader().setReorderingAllowed(false);
        jScrollPane7.setViewportView(E9DTTable);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane7)
                    .addComponent(jScrollPane6))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(391, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("9E Corrections", jPanel4);

        B16HDTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5", "Title 6", "Title 7", "Title 8"
            }
        ));
        B16HDTable.getTableHeader().setReorderingAllowed(false);
        jScrollPane8.setViewportView(B16HDTable);

        B16DTTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5", "Title 6", "Title 7", "Title 8", "Title 9", "Title 10", "Title 11", "Title 12", "Title 13"
            }
        ));
        B16DTTable.getTableHeader().setReorderingAllowed(false);
        jScrollPane9.setViewportView(B16DTTable);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane9)
                    .addComponent(jScrollPane8))
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(391, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("16B Corrections", jPanel6);

        B9HDTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5", "Title 6", "Title 7", "Title 8"
            }
        ));
        B9HDTable.getTableHeader().setReorderingAllowed(false);
        jScrollPane10.setViewportView(B9HDTable);

        B9DTTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5", "Title 6", "Title 7", "Title 8", "Title 9", "Title 10", "Title 11", "Title 12", "Title 13"
            }
        ));
        B9DTTable.getTableHeader().setReorderingAllowed(false);
        jScrollPane11.setViewportView(B9DTTable);

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane11)
                    .addComponent(jScrollPane10))
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane10, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane11, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(391, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("9B Corrections", jPanel7);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    loadHDTable();
}//GEN-LAST:event_jButton1ActionPerformed

private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

}//GEN-LAST:event_jButton2ActionPerformed

private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed

}//GEN-LAST:event_jButton3ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        updateHD();
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton11ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GeneralCheckGLTransactions.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GeneralCheckGLTransactions.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GeneralCheckGLTransactions.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GeneralCheckGLTransactions.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                GeneralCheckGLTransactions dialog = new GeneralCheckGLTransactions(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {

                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private org.jdesktop.swingx.JXTable B16DTTable;
    private org.jdesktop.swingx.JXTable B16HDTable;
    private org.jdesktop.swingx.JXTable B9DTTable;
    private org.jdesktop.swingx.JXTable B9HDTable;
    private org.jdesktop.swingx.JXTable DRCRDTTable;
    private org.jdesktop.swingx.JXTable DRCRHDTable;
    private org.jdesktop.swingx.JXTable DTTable;
    private org.jdesktop.swingx.JXTable E9DTTable;
    private org.jdesktop.swingx.JXTable E9HDTable;
    private org.jdesktop.swingx.JXTable GLTable;
    private org.jdesktop.swingx.JXTable HDTable;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private com.toedter.calendar.JDateChooser jDateChooser2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane10;
    private javax.swing.JScrollPane jScrollPane11;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JRadioButton optDTID;
    private javax.swing.JRadioButton optHDID;
    private javax.swing.JTextField txtMainID;
    // End of variables declaration//GEN-END:variables

    private void loadHDTable() {
        try {
            dtm1.setRowCount(0);
            List<Object> inputs = new ArrayList<>();
            inputs.add(1);
            if (optHDID.isSelected()) {
                inputs.add(1);
            } else if (optDTID.isSelected()) {
                inputs.add(2);
            }
            inputs.add(txtMainID.getText());
            List<List<Object>> HDOutPuts = ServerConnection.getServerConnector().searchMultipleResults(inputs, "ssp_F28_GL_Error", 8);
            for (List<Object> HDOutPut : HDOutPuts) {
                Vector v = new Vector();
                for (Object object : HDOutPut) {
                    v.add(object);
                }
                dtm1.addRow(v);
            }
        } catch (SQLException ex) {
            Logger.getLogger(GeneralCheckGLTransactions.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(GeneralCheckGLTransactions.class.getName()).log(Level.SEVERE, null, ex);
        } catch (RemoteException ex) {
            Logger.getLogger(GeneralCheckGLTransactions.class.getName()).log(Level.SEVERE, null, ex);
        }
        loadDTTable();
    }

    private void loadDTTable() {
        try {
            dtm2.setRowCount(0);
            List<Object> inputs = new ArrayList<>();
            inputs.add(2);
            if (optHDID.isSelected()) {
                inputs.add(1);
            } else if (optDTID.isSelected()) {
                inputs.add(2);
            }
            inputs.add(txtMainID.getText());
            List<List<Object>> DTOutputs = ServerConnection.getServerConnector().searchMultipleResults(inputs, "ssp_F28_GL_Error", 13);
            for (List<Object> DTOutput : DTOutputs) {
                Vector v = new Vector();
                for (Object object : DTOutput) {
                    v.add(object);
                }
                dtm2.addRow(v);
            }
        } catch (SQLException ex) {
            Logger.getLogger(GeneralCheckGLTransactions.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(GeneralCheckGLTransactions.class.getName()).log(Level.SEVERE, null, ex);
        } catch (RemoteException ex) {
            Logger.getLogger(GeneralCheckGLTransactions.class.getName()).log(Level.SEVERE, null, ex);
        }
        loadGLTable();
    }

    private void loadGLTable() {
        try {
            dtm3.setRowCount(0);
            List<Object> inputs = new ArrayList<>();
            inputs.add(3);
            if (optHDID.isSelected()) {
                inputs.add(1);
            } else if (optDTID.isSelected()) {
                inputs.add(2);
            }
            inputs.add(txtMainID.getText());
            List<List<Object>> GLOutPuts = ServerConnection.getServerConnector().searchMultipleResults(inputs, "ssp_F28_GL_Error", 17);
            for (List<Object> GLOutPut : GLOutPuts) {
                Vector v = new Vector();
                for (Object object : GLOutPut) {
                    v.add(object);
                }
                dtm3.addRow(v);
            }
        } catch (SQLException ex) {
            Logger.getLogger(GeneralCheckGLTransactions.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(GeneralCheckGLTransactions.class.getName()).log(Level.SEVERE, null, ex);
        } catch (RemoteException ex) {
            Logger.getLogger(GeneralCheckGLTransactions.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void updateHD() {
        try {
            List<Object> inputs;
            for (int i = 0; i < HDTable.getRowCount(); i++) {
                inputs = new ArrayList<>();
                inputs.add(String.valueOf(HDTable.getValueAt(i, 0)));
                inputs.add(String.valueOf(HDTable.getValueAt(i, 4)));
                inputs.add(String.valueOf(HDTable.getValueAt(i, 2)));
                inputs.add(String.valueOf(HDTable.getValueAt(i, 7)));
                ServerConnection.getServerConnector().insertData(inputs, "ssp_F28_GL_Error_Update_JHD", 0);
            }
            updateDT();
        } catch (SQLException ex) {
            Logger.getLogger(GeneralCheckGLTransactions.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(GeneralCheckGLTransactions.class.getName()).log(Level.SEVERE, null, ex);
        } catch (RemoteException ex) {
            Logger.getLogger(GeneralCheckGLTransactions.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void updateDT() {
        List<Object> inputs;
        for (int i = 0; i < DTTable.getRowCount(); i++) {
            try {
                inputs = new ArrayList<>();
                inputs.add(String.valueOf(DTTable.getValueAt(i, 0)));
                inputs.add(String.valueOf(DTTable.getValueAt(i, 1)));
                inputs.add(String.valueOf(DTTable.getValueAt(i, 3)));
                inputs.add(String.valueOf(DTTable.getValueAt(i, 5)));
                inputs.add(String.valueOf(DTTable.getValueAt(i, 10)));
                inputs.add(String.valueOf(DTTable.getValueAt(i, 7)));
                inputs.add(String.valueOf(DTTable.getValueAt(i, 11)));
                inputs.add(String.valueOf(DTTable.getValueAt(i, 12)));
                ServerConnection.getServerConnector().insertData(inputs, "ssp_F28_GL_Error_Update_JDT", 0);
            } catch (SQLException ex) {
                Logger.getLogger(GeneralCheckGLTransactions.class.getName()).log(Level.SEVERE, null, ex);
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(GeneralCheckGLTransactions.class.getName()).log(Level.SEVERE, null, ex);
            } catch (RemoteException ex) {
                Logger.getLogger(GeneralCheckGLTransactions.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        updateGL();
    }

    private void updateGL() {
        List<Object> inputs;
        for (int i = 0; i < GLTable.getRowCount(); i++) {
            try {
                inputs = new ArrayList<>();
                inputs.add(String.valueOf(GLTable.getValueAt(i, 0)));
                inputs.add(String.valueOf(GLTable.getValueAt(i, 1)));
                inputs.add(String.valueOf(GLTable.getValueAt(i, 3)));
                inputs.add(String.valueOf(GLTable.getValueAt(i, 4)));
                inputs.add(String.valueOf(GLTable.getValueAt(i, 6)));
                inputs.add(String.valueOf(GLTable.getValueAt(i, 8)));
                inputs.add(String.valueOf(GLTable.getValueAt(i, 10)));
                inputs.add(String.valueOf(GLTable.getValueAt(i, 13)));
                inputs.add(String.valueOf(GLTable.getValueAt(i, 14)));
                inputs.add(String.valueOf(GLTable.getValueAt(i, 15)));
                inputs.add(String.valueOf(GLTable.getValueAt(i, 16)));
                
                ServerConnection.getServerConnector().insertData(inputs, "ssp_F28_GL_Error_Update_ActGL", 0);
            } catch (SQLException ex) {
                Logger.getLogger(GeneralCheckGLTransactions.class.getName()).log(Level.SEVERE, null, ex);
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(GeneralCheckGLTransactions.class.getName()).log(Level.SEVERE, null, ex);
            } catch (RemoteException ex) {
                Logger.getLogger(GeneralCheckGLTransactions.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        JOptionPane.showMessageDialog(this, "නිවැරදි කිරීම සාර්ථකයි", "සාර්ථකයි", JOptionPane.INFORMATION_MESSAGE);
    }

}
