/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.nbs.view.common.search;

import Sources.HiddenItemComboBoxSelector;
import Sources.JTextFieldRemoveNull;
import Sources.KeyBoard;
import com.nbs.impl.ServerConnection;
import com.nbs.view.common.AmaliKeyBoard;
import com.nbs.view.common.UnicodeKeyBoard;
import static com.nbs.view.common.search.FindSectionOrOutsider.creditorID;
import java.awt.Color;
import java.awt.event.FocusEvent;
import java.awt.event.KeyEvent;
import java.rmi.RemoteException;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JDialog;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import org.nbs.resources.Item;

/**
 *
 * @author mmh
 */
public class OutsiderDialog extends javax.swing.JDialog {

    /**
     * Creates new form OutsiderDialog
     */
    public OutsiderDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
        loadCombo();
    }

    public OutsiderDialog(JDialog parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
        loadCombo();
    }

    OutsiderDialog(JDialog parent, boolean modal, String id) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
        setCreditorDataEdit(id);
        setAllEditable(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel7 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtOutsiderName = new javax.swing.JTextField();
        txtContactPerson = new javax.swing.JTextField();
        cmbOutsiderType = new org.nbs.components.HiddenItemComboBox();
        txtOutsiderNameAmali = new javax.swing.JTextField();
        txtOutsiderCode = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        txtRefNo = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jPanel10 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        txtOutsiderAddress1 = new javax.swing.JTextField();
        txtOutsiderAddress3 = new javax.swing.JTextField();
        txtOutsiderAddress2 = new javax.swing.JTextField();
        txtOutsiderAddress4 = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        txtOutsiderTP1 = new javax.swing.JTextField();
        txtOutsiderTP2 = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        txtOutsiderEmail = new javax.swing.JTextField();
        jPanel11 = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        txtDebtorDayCount = new javax.swing.JTextField();
        txtDebtorCreditLimit = new javax.swing.JTextField();
        jPanel12 = new javax.swing.JPanel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        txtCreditorDayCount = new javax.swing.JTextField();
        txtCreditorCreditLimit = new javax.swing.JTextField();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jPanel7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 255), 2));

        jPanel8.setBackground(new java.awt.Color(0, 88, 136));
        jPanel8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 255), 2));

        jLabel7.setFont(new java.awt.Font("Iskoola Pota", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("ණය ගැතියන්/ණය හිමියන් ඇතුලත් කිරීම");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        jPanel9.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 255), 2));

        jLabel8.setFont(new java.awt.Font("Iskoola Pota", 0, 16)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel8.setText("නම(යුනිකෝඩ්) :");

        jLabel9.setFont(new java.awt.Font("Iskoola Pota", 0, 16)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel9.setText("නම(සිංහල) :");

        jLabel10.setFont(new java.awt.Font("Iskoola Pota", 0, 16)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel10.setText("අදාළ පුද්ගලයා :");

        jLabel11.setFont(new java.awt.Font("Iskoola Pota", 0, 16)); // NOI18N
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel11.setText("වර්ගය :");

        txtOutsiderName.setEditable(false);
        txtOutsiderName.setFont(new java.awt.Font("Iskoola Pota", 0, 15)); // NOI18N
        txtOutsiderName.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtOutsiderName.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtOutsiderNameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtOutsiderNameFocusLost(evt);
            }
        });
        txtOutsiderName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtOutsiderNameActionPerformed(evt);
            }
        });
        txtOutsiderName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtOutsiderNameKeyTyped(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtOutsiderNameKeyReleased(evt);
            }
        });

        txtContactPerson.setEditable(false);
        txtContactPerson.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtContactPerson.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtContactPersonFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtContactPersonFocusLost(evt);
            }
        });
        txtContactPerson.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtContactPersonActionPerformed(evt);
            }
        });

        cmbOutsiderType.setFont(new java.awt.Font("Iskoola Pota", 0, 16)); // NOI18N

        txtOutsiderNameAmali.setEditable(false);
        txtOutsiderNameAmali.setFont(new java.awt.Font("AMALEE", 0, 15)); // NOI18N
        txtOutsiderNameAmali.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtOutsiderNameAmali.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtOutsiderNameAmaliFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtOutsiderNameAmaliFocusLost(evt);
            }
        });
        txtOutsiderNameAmali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtOutsiderNameAmaliActionPerformed(evt);
            }
        });
        txtOutsiderNameAmali.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtOutsiderNameAmaliKeyTyped(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtOutsiderNameAmaliKeyReleased(evt);
            }
        });

        txtOutsiderCode.setEditable(false);
        txtOutsiderCode.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtOutsiderCode.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtOutsiderCodeFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtOutsiderCodeFocusLost(evt);
            }
        });
        txtOutsiderCode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtOutsiderCodeActionPerformed(evt);
            }
        });

        jLabel16.setFont(new java.awt.Font("Iskoola Pota", 0, 16)); // NOI18N
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel16.setText("කේතය :");

        txtRefNo.setEditable(false);
        txtRefNo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtRefNo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtRefNoFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtRefNoFocusLost(evt);
            }
        });
        txtRefNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRefNoActionPerformed(evt);
            }
        });

        jLabel17.setFont(new java.awt.Font("Iskoola Pota", 0, 16)); // NOI18N
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel17.setText("ලියාපදිංචි අංකය :");

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtOutsiderName)
                    .addComponent(txtOutsiderNameAmali)
                    .addComponent(txtContactPerson)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtRefNo, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cmbOutsiderType, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtOutsiderCode))
                        .addGap(195, 195, 195)))
                .addContainerGap())
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtRefNo, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                    .addComponent(jLabel17, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                    .addComponent(cmbOutsiderType, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                    .addComponent(txtOutsiderCode, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                    .addComponent(txtOutsiderName, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtOutsiderNameAmali, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtContactPerson, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE))
                .addContainerGap())
        );

        jButton5.setFont(new java.awt.Font("Iskoola Pota", 1, 18)); // NOI18N
        jButton5.setText("ඉවත් වන්න");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jPanel10.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 255), 2));

        jLabel12.setFont(new java.awt.Font("Iskoola Pota", 0, 15)); // NOI18N
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel12.setText("ලිපිනය 1 :");

        jLabel13.setFont(new java.awt.Font("Iskoola Pota", 0, 15)); // NOI18N
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel13.setText("ලිපිනය 2 :");

        jLabel14.setFont(new java.awt.Font("Iskoola Pota", 0, 15)); // NOI18N
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel14.setText("ලිපිනය 3 :");

        jLabel15.setFont(new java.awt.Font("Iskoola Pota", 0, 15)); // NOI18N
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel15.setText("ලිපිනය 4 :");

        txtOutsiderAddress1.setEditable(false);
        txtOutsiderAddress1.setFont(new java.awt.Font("Iskoola Pota", 0, 15)); // NOI18N
        txtOutsiderAddress1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtOutsiderAddress1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtOutsiderAddress1FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtOutsiderAddress1FocusLost(evt);
            }
        });
        txtOutsiderAddress1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtOutsiderAddress1ActionPerformed(evt);
            }
        });

        txtOutsiderAddress3.setEditable(false);
        txtOutsiderAddress3.setFont(new java.awt.Font("Iskoola Pota", 0, 15)); // NOI18N
        txtOutsiderAddress3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtOutsiderAddress3.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtOutsiderAddress3FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtOutsiderAddress3FocusLost(evt);
            }
        });
        txtOutsiderAddress3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtOutsiderAddress3ActionPerformed(evt);
            }
        });

        txtOutsiderAddress2.setEditable(false);
        txtOutsiderAddress2.setFont(new java.awt.Font("Iskoola Pota", 0, 15)); // NOI18N
        txtOutsiderAddress2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtOutsiderAddress2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtOutsiderAddress2FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtOutsiderAddress2FocusLost(evt);
            }
        });
        txtOutsiderAddress2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtOutsiderAddress2ActionPerformed(evt);
            }
        });

        txtOutsiderAddress4.setEditable(false);
        txtOutsiderAddress4.setFont(new java.awt.Font("Iskoola Pota", 0, 15)); // NOI18N
        txtOutsiderAddress4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtOutsiderAddress4.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtOutsiderAddress4FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtOutsiderAddress4FocusLost(evt);
            }
        });
        txtOutsiderAddress4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtOutsiderAddress4ActionPerformed(evt);
            }
        });

        jLabel18.setFont(new java.awt.Font("Iskoola Pota", 0, 15)); // NOI18N
        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel18.setText("දු.අංකයන් :");

        txtOutsiderTP1.setEditable(false);
        txtOutsiderTP1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtOutsiderTP1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtOutsiderTP1FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtOutsiderTP1FocusLost(evt);
            }
        });
        txtOutsiderTP1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtOutsiderTP1ActionPerformed(evt);
            }
        });

        txtOutsiderTP2.setEditable(false);
        txtOutsiderTP2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtOutsiderTP2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtOutsiderTP2FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtOutsiderTP2FocusLost(evt);
            }
        });
        txtOutsiderTP2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtOutsiderTP2ActionPerformed(evt);
            }
        });

        jLabel19.setFont(new java.awt.Font("Iskoola Pota", 0, 15)); // NOI18N
        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel19.setText("ඊ-මේල් :");

        txtOutsiderEmail.setEditable(false);
        txtOutsiderEmail.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtOutsiderEmail.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtOutsiderEmailFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtOutsiderEmailFocusLost(evt);
            }
        });
        txtOutsiderEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtOutsiderEmailActionPerformed(evt);
            }
        });

        jPanel11.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 255), 2), "ණයගැති සීමාව", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Iskoola Pota", 0, 15), new java.awt.Color(51, 51, 255))); // NOI18N

        jLabel20.setFont(new java.awt.Font("Iskoola Pota", 0, 15)); // NOI18N
        jLabel20.setText("දින ගණන");

        jLabel21.setFont(new java.awt.Font("Iskoola Pota", 0, 15)); // NOI18N
        jLabel21.setText("ණය සීමාව");

        txtDebtorDayCount.setEditable(false);
        txtDebtorDayCount.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtDebtorDayCount.setText("0");
        txtDebtorDayCount.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtDebtorDayCount.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtDebtorDayCountFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtDebtorDayCountFocusLost(evt);
            }
        });
        txtDebtorDayCount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDebtorDayCountActionPerformed(evt);
            }
        });

        txtDebtorCreditLimit.setEditable(false);
        txtDebtorCreditLimit.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        txtDebtorCreditLimit.setText("0.00");
        txtDebtorCreditLimit.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtDebtorCreditLimit.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtDebtorCreditLimitFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtDebtorCreditLimitFocusLost(evt);
            }
        });
        txtDebtorCreditLimit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDebtorCreditLimitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel20, javax.swing.GroupLayout.DEFAULT_SIZE, 111, Short.MAX_VALUE)
                    .addComponent(txtDebtorDayCount))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel21, javax.swing.GroupLayout.DEFAULT_SIZE, 113, Short.MAX_VALUE)
                    .addComponent(txtDebtorCreditLimit))
                .addGap(20, 20, 20))
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel21, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDebtorDayCount, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDebtorCreditLimit, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(3, 3, 3))
        );

        jPanel12.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 255), 2), "ණයහිමි සීමාව", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Iskoola Pota", 0, 15), new java.awt.Color(51, 51, 255))); // NOI18N

        jLabel22.setFont(new java.awt.Font("Iskoola Pota", 0, 15)); // NOI18N
        jLabel22.setText("දින ගණන");

        jLabel23.setFont(new java.awt.Font("Iskoola Pota", 0, 15)); // NOI18N
        jLabel23.setText("ණය සීමාව");

        txtCreditorDayCount.setEditable(false);
        txtCreditorDayCount.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtCreditorDayCount.setText("0");
        txtCreditorDayCount.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtCreditorDayCount.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtCreditorDayCountFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtCreditorDayCountFocusLost(evt);
            }
        });
        txtCreditorDayCount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCreditorDayCountActionPerformed(evt);
            }
        });

        txtCreditorCreditLimit.setEditable(false);
        txtCreditorCreditLimit.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        txtCreditorCreditLimit.setText("0.00");
        txtCreditorCreditLimit.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtCreditorCreditLimit.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtCreditorCreditLimitFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtCreditorCreditLimitFocusLost(evt);
            }
        });
        txtCreditorCreditLimit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCreditorCreditLimitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel22, javax.swing.GroupLayout.DEFAULT_SIZE, 111, Short.MAX_VALUE)
                    .addComponent(txtCreditorDayCount))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel23, javax.swing.GroupLayout.DEFAULT_SIZE, 113, Short.MAX_VALUE)
                    .addComponent(txtCreditorCreditLimit))
                .addGap(20, 20, 20))
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel23, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCreditorDayCount, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCreditorCreditLimit, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(3, 3, 3))
        );

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel19, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtOutsiderAddress3)
                    .addComponent(txtOutsiderAddress2)
                    .addComponent(txtOutsiderAddress4, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addComponent(txtOutsiderTP1, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtOutsiderTP2, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txtOutsiderEmail)
                    .addComponent(txtOutsiderAddress1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtOutsiderAddress1, javax.swing.GroupLayout.DEFAULT_SIZE, 27, Short.MAX_VALUE)
                            .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtOutsiderAddress2, javax.swing.GroupLayout.DEFAULT_SIZE, 27, Short.MAX_VALUE)
                            .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtOutsiderAddress3, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel10Layout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(3, 3, 3)
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtOutsiderAddress4, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtOutsiderTP1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtOutsiderTP2, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtOutsiderEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(20, 20, 20))
        );

        jButton7.setFont(new java.awt.Font("Iskoola Pota", 1, 18)); // NOI18N
        jButton7.setText("සේව්");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jButton8.setFont(new java.awt.Font("Iskoola Pota", 1, 18)); // NOI18N
        jButton8.setText("නව");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                        .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(189, 189, 189)
                        .addComponent(jButton5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jPanel10, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton5)
                    .addComponent(jButton7)
                    .addComponent(jButton8))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtOutsiderNameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtOutsiderNameFocusGained
        focusGained(evt);
    }//GEN-LAST:event_txtOutsiderNameFocusGained

    private void txtOutsiderNameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtOutsiderNameFocusLost
        focusLost(evt);
    }//GEN-LAST:event_txtOutsiderNameFocusLost

    private void txtOutsiderNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtOutsiderNameActionPerformed
        new UnicodeKeyBoard(this, true, txtOutsiderNameAmali, txtOutsiderName,false).setVisible(true);
        txtOutsiderNameAmali.grabFocus();
    }//GEN-LAST:event_txtOutsiderNameActionPerformed

    private void txtContactPersonFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtContactPersonFocusGained
        focusGained(evt);
    }//GEN-LAST:event_txtContactPersonFocusGained

    private void txtContactPersonFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtContactPersonFocusLost
        focusLost(evt);
    }//GEN-LAST:event_txtContactPersonFocusLost

    private void txtContactPersonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtContactPersonActionPerformed
        txtOutsiderAddress1.grabFocus();
    }//GEN-LAST:event_txtContactPersonActionPerformed

    private void txtOutsiderNameAmaliFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtOutsiderNameAmaliFocusGained
        focusGained(evt);
    }//GEN-LAST:event_txtOutsiderNameAmaliFocusGained

    private void txtOutsiderNameAmaliFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtOutsiderNameAmaliFocusLost
        focusLost(evt);
    }//GEN-LAST:event_txtOutsiderNameAmaliFocusLost

    private void txtOutsiderNameAmaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtOutsiderNameAmaliActionPerformed
        new AmaliKeyBoard(this, true, txtOutsiderNameAmali, txtOutsiderName,false).setVisible(true);
        txtContactPerson.grabFocus();
    }//GEN-LAST:event_txtOutsiderNameAmaliActionPerformed

    private void txtOutsiderCodeFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtOutsiderCodeFocusGained
        focusGained(evt);
    }//GEN-LAST:event_txtOutsiderCodeFocusGained

    private void txtOutsiderCodeFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtOutsiderCodeFocusLost
        focusLost(evt);
    }//GEN-LAST:event_txtOutsiderCodeFocusLost

    private void txtOutsiderCodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtOutsiderCodeActionPerformed
        txtOutsiderName.grabFocus();
    }//GEN-LAST:event_txtOutsiderCodeActionPerformed

    private void txtRefNoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtRefNoFocusGained
        focusGained(evt);
    }//GEN-LAST:event_txtRefNoFocusGained

    private void txtRefNoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtRefNoFocusLost
        focusLost(evt);
    }//GEN-LAST:event_txtRefNoFocusLost

    private void txtRefNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRefNoActionPerformed
        cmbOutsiderType.grabFocus();
    }//GEN-LAST:event_txtRefNoActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        FindSectionOrOutsider.refreshItem.doClick();
        dispose();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void txtOutsiderAddress1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtOutsiderAddress1FocusGained
        focusGained(evt);
    }//GEN-LAST:event_txtOutsiderAddress1FocusGained

    private void txtOutsiderAddress1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtOutsiderAddress1FocusLost
        focusLost(evt);
    }//GEN-LAST:event_txtOutsiderAddress1FocusLost

    private void txtOutsiderAddress1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtOutsiderAddress1ActionPerformed
        txtOutsiderAddress2.grabFocus();
    }//GEN-LAST:event_txtOutsiderAddress1ActionPerformed

    private void txtOutsiderAddress3FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtOutsiderAddress3FocusGained
        focusGained(evt);
    }//GEN-LAST:event_txtOutsiderAddress3FocusGained

    private void txtOutsiderAddress3FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtOutsiderAddress3FocusLost
        focusLost(evt);
    }//GEN-LAST:event_txtOutsiderAddress3FocusLost

    private void txtOutsiderAddress3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtOutsiderAddress3ActionPerformed
        txtOutsiderAddress4.grabFocus();
    }//GEN-LAST:event_txtOutsiderAddress3ActionPerformed

    private void txtOutsiderAddress2FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtOutsiderAddress2FocusGained
        focusGained(evt);
    }//GEN-LAST:event_txtOutsiderAddress2FocusGained

    private void txtOutsiderAddress2FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtOutsiderAddress2FocusLost
        focusLost(evt);
    }//GEN-LAST:event_txtOutsiderAddress2FocusLost

    private void txtOutsiderAddress2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtOutsiderAddress2ActionPerformed
        txtOutsiderAddress3.grabFocus();
    }//GEN-LAST:event_txtOutsiderAddress2ActionPerformed

    private void txtOutsiderAddress4FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtOutsiderAddress4FocusGained
        focusGained(evt);
    }//GEN-LAST:event_txtOutsiderAddress4FocusGained

    private void txtOutsiderAddress4FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtOutsiderAddress4FocusLost
        focusLost(evt);
    }//GEN-LAST:event_txtOutsiderAddress4FocusLost

    private void txtOutsiderAddress4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtOutsiderAddress4ActionPerformed
        txtOutsiderTP1.grabFocus();
    }//GEN-LAST:event_txtOutsiderAddress4ActionPerformed

    private void txtOutsiderTP1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtOutsiderTP1FocusGained
        focusGained(evt);
    }//GEN-LAST:event_txtOutsiderTP1FocusGained

    private void txtOutsiderTP1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtOutsiderTP1FocusLost
        focusLost(evt);
    }//GEN-LAST:event_txtOutsiderTP1FocusLost

    private void txtOutsiderTP1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtOutsiderTP1ActionPerformed
        txtOutsiderTP2.grabFocus();
    }//GEN-LAST:event_txtOutsiderTP1ActionPerformed

    private void txtOutsiderTP2FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtOutsiderTP2FocusGained
        focusGained(evt);
    }//GEN-LAST:event_txtOutsiderTP2FocusGained

    private void txtOutsiderTP2FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtOutsiderTP2FocusLost
        focusLost(evt);
    }//GEN-LAST:event_txtOutsiderTP2FocusLost

    private void txtOutsiderTP2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtOutsiderTP2ActionPerformed
        txtOutsiderEmail.grabFocus();
    }//GEN-LAST:event_txtOutsiderTP2ActionPerformed

    private void txtOutsiderEmailFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtOutsiderEmailFocusGained
        focusGained(evt);
    }//GEN-LAST:event_txtOutsiderEmailFocusGained

    private void txtOutsiderEmailFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtOutsiderEmailFocusLost
        focusLost(evt);
    }//GEN-LAST:event_txtOutsiderEmailFocusLost

    private void txtOutsiderEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtOutsiderEmailActionPerformed
        txtDebtorDayCount.grabFocus();
    }//GEN-LAST:event_txtOutsiderEmailActionPerformed

    private void txtDebtorDayCountFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtDebtorDayCountFocusGained
        focusGained(evt);
    }//GEN-LAST:event_txtDebtorDayCountFocusGained

    private void txtDebtorDayCountFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtDebtorDayCountFocusLost
        focusLost(evt);
    }//GEN-LAST:event_txtDebtorDayCountFocusLost

    private void txtDebtorDayCountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDebtorDayCountActionPerformed
        txtDebtorCreditLimit.grabFocus();
    }//GEN-LAST:event_txtDebtorDayCountActionPerformed

    private void txtDebtorCreditLimitFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtDebtorCreditLimitFocusGained
        focusGained(evt);
    }//GEN-LAST:event_txtDebtorCreditLimitFocusGained

    private void txtDebtorCreditLimitFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtDebtorCreditLimitFocusLost
        focusLost(evt);
    }//GEN-LAST:event_txtDebtorCreditLimitFocusLost

    private void txtDebtorCreditLimitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDebtorCreditLimitActionPerformed
        txtCreditorDayCount.grabFocus();
    }//GEN-LAST:event_txtDebtorCreditLimitActionPerformed

    private void txtCreditorDayCountFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCreditorDayCountFocusGained
        focusGained(evt);
    }//GEN-LAST:event_txtCreditorDayCountFocusGained

    private void txtCreditorDayCountFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCreditorDayCountFocusLost
        focusLost(evt);
    }//GEN-LAST:event_txtCreditorDayCountFocusLost

    private void txtCreditorDayCountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCreditorDayCountActionPerformed
        txtCreditorCreditLimit.grabFocus();
    }//GEN-LAST:event_txtCreditorDayCountActionPerformed

    private void txtCreditorCreditLimitFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCreditorCreditLimitFocusGained
        focusGained(evt);
    }//GEN-LAST:event_txtCreditorCreditLimitFocusGained

    private void txtCreditorCreditLimitFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCreditorCreditLimitFocusLost
        focusLost(evt);
    }//GEN-LAST:event_txtCreditorCreditLimitFocusLost

    private void txtCreditorCreditLimitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCreditorCreditLimitActionPerformed
        jButton7.grabFocus();
    }//GEN-LAST:event_txtCreditorCreditLimitActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        saveCreditorData();
        int i = JOptionPane.showConfirmDialog(this, "සේව් කිරීම සම්පූර්ණයි. නැවත ඇතුලත් කිරීමක් අවශ්‍යද?", "නැවත ඇතුලත් කිරීමක් අවශ්‍යද?", JOptionPane.YES_NO_OPTION, JOptionPane.INFORMATION_MESSAGE);
        if (i == JOptionPane.YES_OPTION) {
            clearOutsiderDialog();
        } else {
            clearOutsiderDialog();
            dispose();
        }
        FindSectionOrOutsider.refreshItem.doClick();
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        creditorID = "0";
        setAllEditable(true);
        saveCreditorData();
    }//GEN-LAST:event_jButton8ActionPerformed

    private void txtOutsiderNameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtOutsiderNameKeyTyped

    }//GEN-LAST:event_txtOutsiderNameKeyTyped

    private void txtOutsiderNameAmaliKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtOutsiderNameAmaliKeyTyped

    }//GEN-LAST:event_txtOutsiderNameAmaliKeyTyped

    private void txtOutsiderNameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtOutsiderNameKeyReleased
        if (evt.getKeyCode() == KeyEvent.VK_F2) {
            new KeyBoard(true, txtOutsiderName).setVisible(true);
        }
    }//GEN-LAST:event_txtOutsiderNameKeyReleased

    private void txtOutsiderNameAmaliKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtOutsiderNameAmaliKeyReleased
        if (evt.getKeyCode() == KeyEvent.VK_F2) {
            new KeyBoard(false, txtOutsiderNameAmali).setVisible(true);
        }
    }//GEN-LAST:event_txtOutsiderNameAmaliKeyReleased

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        FindSectionOrOutsider.refreshItem.doClick();
    }//GEN-LAST:event_formWindowClosing

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OutsiderDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OutsiderDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OutsiderDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OutsiderDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                OutsiderDialog dialog = new OutsiderDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static org.nbs.components.HiddenItemComboBox cmbOutsiderType;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    public static javax.swing.JLabel jLabel10;
    public static javax.swing.JLabel jLabel11;
    public static javax.swing.JLabel jLabel12;
    public static javax.swing.JLabel jLabel13;
    public static javax.swing.JLabel jLabel14;
    public static javax.swing.JLabel jLabel15;
    public static javax.swing.JLabel jLabel16;
    public static javax.swing.JLabel jLabel17;
    public static javax.swing.JLabel jLabel18;
    public static javax.swing.JLabel jLabel19;
    public static javax.swing.JLabel jLabel20;
    public static javax.swing.JLabel jLabel21;
    public static javax.swing.JLabel jLabel22;
    public static javax.swing.JLabel jLabel23;
    public static javax.swing.JLabel jLabel7;
    public static javax.swing.JLabel jLabel8;
    public static javax.swing.JLabel jLabel9;
    public static javax.swing.JPanel jPanel10;
    public static javax.swing.JPanel jPanel11;
    public static javax.swing.JPanel jPanel12;
    public static javax.swing.JPanel jPanel7;
    public static javax.swing.JPanel jPanel8;
    public static javax.swing.JPanel jPanel9;
    public static javax.swing.JTextField txtContactPerson;
    public static javax.swing.JTextField txtCreditorCreditLimit;
    public static javax.swing.JTextField txtCreditorDayCount;
    public static javax.swing.JTextField txtDebtorCreditLimit;
    public static javax.swing.JTextField txtDebtorDayCount;
    public static javax.swing.JTextField txtOutsiderAddress1;
    public static javax.swing.JTextField txtOutsiderAddress2;
    public static javax.swing.JTextField txtOutsiderAddress3;
    public static javax.swing.JTextField txtOutsiderAddress4;
    public static javax.swing.JTextField txtOutsiderCode;
    public static javax.swing.JTextField txtOutsiderEmail;
    public static javax.swing.JTextField txtOutsiderName;
    public static javax.swing.JTextField txtOutsiderNameAmali;
    public static javax.swing.JTextField txtOutsiderTP1;
    public static javax.swing.JTextField txtOutsiderTP2;
    public static javax.swing.JTextField txtRefNo;
    // End of variables declaration//GEN-END:variables
private void focusGained(FocusEvent evt) {
        evt.getComponent().setBackground(Color.YELLOW);
    }

    private void focusLost(FocusEvent evt) {
        evt.getComponent().setBackground(Color.WHITE);
    }

    private void saveCreditorData() {
        try {
            List<Object> inputs = new ArrayList<>();

            inputs.add(creditorID);
            inputs.add(cmbOutsiderType.getSelectedItem().getId());
            inputs.add(txtOutsiderCode.getText());
            inputs.add(txtRefNo.getText());
            inputs.add(txtOutsiderNameAmali.getText());
            inputs.add(txtOutsiderName.getText());
            inputs.add(txtContactPerson.getText());
            inputs.add(txtOutsiderAddress1.getText());
            inputs.add(txtOutsiderAddress2.getText());
            inputs.add(txtOutsiderAddress3.getText());
            inputs.add(txtOutsiderAddress4.getText());
            inputs.add(txtOutsiderTP1.getText());
            inputs.add(txtOutsiderTP2.getText());
            inputs.add(txtOutsiderEmail.getText());
            inputs.add(txtDebtorDayCount.getText());
            inputs.add(txtDebtorCreditLimit.getText());
            inputs.add(txtCreditorDayCount.getText());
            inputs.add(txtCreditorCreditLimit.getText());
            inputs.add("@recid");

            List<Object> output = ServerConnection.getServerConnector().insertData(inputs, "ssp_Act_Insert_Act_OutsiderMaster", 1);
            creditorID = String.valueOf(output.get(0));
            removeNull();
        } catch (SQLException ex) {
            Logger.getLogger(FindSectionOrOutsider.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(FindSectionOrOutsider.class.getName()).log(Level.SEVERE, null, ex);
        } catch (RemoteException ex) {
            Logger.getLogger(FindSectionOrOutsider.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void clearOutsiderDialog() {
        creditorID = "0";
        cmbOutsiderType.setSelectedIndex(0);
        JTextField fields1[] = {txtOutsiderCode, txtRefNo, txtDebtorDayCount, txtDebtorCreditLimit, txtCreditorDayCount, txtCreditorCreditLimit};
        JTextField fields2[] = {txtOutsiderNameAmali, txtOutsiderName, txtContactPerson, txtOutsiderAddress1, txtOutsiderAddress2, txtOutsiderAddress3, txtOutsiderAddress4, txtOutsiderTP1, txtOutsiderTP2, txtOutsiderEmail};
        for (JTextField jTextField : fields2) {
            jTextField.setText("");
        }
        for (JTextField jTextField : fields1) {
            jTextField.setText("0");
        }
        removeNull();
    }

    private void removeNull() {
        JTextField textFields[] = {txtContactPerson, txtCreditorCreditLimit, txtCreditorDayCount, txtDebtorCreditLimit, txtDebtorDayCount, txtOutsiderAddress1, txtOutsiderAddress2, txtOutsiderAddress3, txtOutsiderAddress4, txtOutsiderCode, txtOutsiderEmail, txtOutsiderName, txtOutsiderNameAmali, txtOutsiderTP1, txtOutsiderTP2, txtRefNo,};
        for (JTextField textField : textFields) {
            JTextFieldRemoveNull.removeNull(textField);
        }
    }

    private void loadCombo() {
        List<Object> inputs1 = new ArrayList<>();
        try {
            inputs1.add(4);
            inputs1.add(null);
            inputs1.add(null);
            inputs1.add(0);
            inputs1.add(0);

            List<List<Object>> outputs1 = ServerConnection.getServerConnector().searchMultipleResults(inputs1, "ssp_F28_LoadCombo_ViewStock", 2);
            Vector v = new Vector();
            for (List<Object> output : outputs1) {
                v.add(new Item(Integer.parseInt(String.valueOf(output.get(0))), String.valueOf(output.get(1))));
            }
            cmbOutsiderType.setModel(new DefaultComboBoxModel<>(v));

        } catch (RemoteException ex) {
            Logger.getLogger(FindSectionOrOutsider.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(FindSectionOrOutsider.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(FindSectionOrOutsider.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void setCreditorDataEdit(String id) {
        try {
            List<Object> inputs = new ArrayList<>();
            inputs.add(id);
            List<Object> output = ServerConnection.getServerConnector().searchSingleResult(inputs, "ssp_Act_Edit_Act_OutsiderMaster", 20);
            for (Object object : output) {
                System.out.println(object + " out");
            }
            creditorID = String.valueOf(output.get(0));
            HiddenItemComboBoxSelector.setSelectedItem(cmbOutsiderType, Integer.parseInt(String.valueOf(output.get(1))), String.valueOf(output.get(2)));
            txtOutsiderCode.setText(String.valueOf(output.get(3)));
            txtRefNo.setText(String.valueOf(output.get(4)));
            txtOutsiderNameAmali.setText(String.valueOf(output.get(5)));
            txtOutsiderName.setText(String.valueOf(output.get(6)));
            txtContactPerson.setText(String.valueOf(output.get(7)));
            txtOutsiderAddress1.setText(String.valueOf(output.get(8)));
            txtOutsiderAddress2.setText(String.valueOf(output.get(9)));
            txtOutsiderAddress3.setText(String.valueOf(output.get(10)));
            txtOutsiderAddress4.setText(String.valueOf(output.get(11)));
            txtOutsiderTP1.setText(String.valueOf(output.get(12)));
            txtOutsiderTP2.setText(String.valueOf(output.get(13)));
            txtOutsiderEmail.setText(String.valueOf(output.get(14)));
            txtDebtorDayCount.setText(String.valueOf(output.get(15)));
            txtDebtorCreditLimit.setText(String.valueOf(output.get(16)));
            txtCreditorDayCount.setText(String.valueOf(output.get(17)));
            txtCreditorCreditLimit.setText(String.valueOf(output.get(18)));
            removeNullInOutSider();
        } catch (SQLException ex) {
            Logger.getLogger(OutsiderDialog.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(OutsiderDialog.class.getName()).log(Level.SEVERE, null, ex);
        } catch (RemoteException ex) {
            Logger.getLogger(OutsiderDialog.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void removeNullInOutSider() {
        JTextField textFields[] = {txtContactPerson, txtCreditorCreditLimit, txtCreditorDayCount, txtDebtorCreditLimit, txtDebtorDayCount, txtOutsiderAddress1, txtOutsiderAddress2, txtOutsiderAddress3, txtOutsiderAddress4, txtOutsiderCode, txtOutsiderEmail, txtOutsiderName, txtOutsiderNameAmali, txtOutsiderTP1, txtOutsiderTP2, txtRefNo,};
        for (JTextField textField : textFields) {
            JTextFieldRemoveNull.removeNull(textField);
        }
    }

    private void setAllEditable(boolean editable) {
        JTextField fields[]=  {txtContactPerson,txtCreditorCreditLimit,txtCreditorDayCount,txtDebtorCreditLimit,txtDebtorDayCount,txtOutsiderAddress1,txtOutsiderAddress2,txtOutsiderAddress3,txtOutsiderAddress4,txtOutsiderCode,txtOutsiderEmail,txtOutsiderName,txtOutsiderNameAmali,txtOutsiderTP1,txtOutsiderTP2,txtRefNo};
        for (JTextField field : fields) {
            field.setEditable(editable);
        }
    }
}
