/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.nbs.view.common.search;

import Sources.HiddenItemComboBoxSelector;
import Sources.JTextFieldRemoveNull;
import com.nbs.impl.ServerConnection;
import com.nbs.view.common.AmaliKeyBoard;
import com.nbs.view.common.TableHeaders;
import com.nbs.view.common.UnicodeKeyBoard;
import static com.nbs.view.common.search.FindSectionOrOutsider.subSectionMFID;
import java.awt.Color;
import java.awt.Component;
import java.awt.event.FocusEvent;
import java.awt.event.KeyEvent;
import java.rmi.RemoteException;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JCheckBox;
import javax.swing.JDialog;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import org.nbs.components.HiddenIDTextField;
import org.nbs.resources.Item;

/**
 *
 * @author mmh
 */
public class SubSectionDialog extends javax.swing.JDialog {

    /**
     * Creates new form SubSectionDialog
     */
    public SubSectionDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
        loadCombo();
        setAllEditable(false);
    }

    public SubSectionDialog(JDialog parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
        loadCombo();
        setAllEditable(false);
    }

    public SubSectionDialog(JDialog parent, boolean modal, String id) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
        setAllEditable(true);
        setSubSectionDataEdit(id);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel13 = new javax.swing.JPanel();
        jPanel14 = new javax.swing.JPanel();
        jLabel24 = new javax.swing.JLabel();
        jPanel15 = new javax.swing.JPanel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        txtSubName = new javax.swing.JTextField();
        txtSubContactPerson = new org.nbs.components.HiddenIDTextField();
        cmbSubType = new org.nbs.components.HiddenItemComboBox();
        txtSubNameAmali = new javax.swing.JTextField();
        txtSubCode = new javax.swing.JTextField();
        jLabel29 = new javax.swing.JLabel();
        txtSubRefNo = new javax.swing.JTextField();
        jLabel30 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        txtGLAcct = new org.nbs.components.HiddenIDTextField();
        jButton9 = new javax.swing.JButton();
        jPanel16 = new javax.swing.JPanel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        txtSubAddress1 = new javax.swing.JTextField();
        txtSubAddress3 = new javax.swing.JTextField();
        txtSubAddress2 = new javax.swing.JTextField();
        txtSubAddress4 = new javax.swing.JTextField();
        jLabel35 = new javax.swing.JLabel();
        txtSubTP1 = new javax.swing.JTextField();
        txtSubTP2 = new javax.swing.JTextField();
        jLabel36 = new javax.swing.JLabel();
        txtSubEmail = new javax.swing.JTextField();
        jPanel17 = new javax.swing.JPanel();
        jLabel38 = new javax.swing.JLabel();
        txtSubCreditLimit = new javax.swing.JTextField();
        jPanel18 = new javax.swing.JPanel();
        optF7 = new javax.swing.JCheckBox();
        jPanel20 = new javax.swing.JPanel();
        optF10 = new javax.swing.JCheckBox();
        jButton11 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jPanel13.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 255), 2));
        jPanel13.setMinimumSize(new java.awt.Dimension(742, 622));

        jPanel14.setBackground(new java.awt.Color(0, 88, 136));
        jPanel14.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 255), 2));

        jLabel24.setFont(new java.awt.Font("Iskoola Pota", 1, 24)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(255, 255, 255));
        jLabel24.setText("අනු අංශයන් ඇතුලත් කිරීම");

        javax.swing.GroupLayout jPanel14Layout = new javax.swing.GroupLayout(jPanel14);
        jPanel14.setLayout(jPanel14Layout);
        jPanel14Layout.setHorizontalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel24)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel14Layout.setVerticalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        jPanel15.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 255), 2));

        jLabel25.setFont(new java.awt.Font("Iskoola Pota", 0, 16)); // NOI18N
        jLabel25.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel25.setText("නම(English) :");

        jLabel26.setFont(new java.awt.Font("Iskoola Pota", 0, 16)); // NOI18N
        jLabel26.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel26.setText("නම(සිංහල) :");

        jLabel27.setFont(new java.awt.Font("Iskoola Pota", 0, 16)); // NOI18N
        jLabel27.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel27.setText("කළමණාකරු :");

        jLabel28.setFont(new java.awt.Font("Iskoola Pota", 0, 16)); // NOI18N
        jLabel28.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel28.setText("ප්‍රධාන අංශය :");

        txtSubName.setFont(new java.awt.Font("Iskoola Pota", 0, 18)); // NOI18N
        txtSubName.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtSubName.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtSubNameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtSubNameFocusLost(evt);
            }
        });
        txtSubName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSubNameActionPerformed(evt);
            }
        });
        txtSubName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtSubNameKeyReleased(evt);
            }
        });

        txtSubContactPerson.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtSubContactPerson.setFont(new java.awt.Font("AMALEE", 0, 18)); // NOI18N
        txtSubContactPerson.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtSubContactPersonFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtSubContactPersonFocusLost(evt);
            }
        });
        txtSubContactPerson.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSubContactPersonActionPerformed(evt);
            }
        });

        cmbSubType.setFont(new java.awt.Font("Iskoola Pota", 0, 18)); // NOI18N

        txtSubNameAmali.setFont(new java.awt.Font("AMALEE", 0, 18)); // NOI18N
        txtSubNameAmali.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtSubNameAmali.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtSubNameAmaliFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtSubNameAmaliFocusLost(evt);
            }
        });
        txtSubNameAmali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSubNameAmaliActionPerformed(evt);
            }
        });
        txtSubNameAmali.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtSubNameAmaliKeyReleased(evt);
            }
        });

        txtSubCode.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtSubCode.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtSubCodeFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtSubCodeFocusLost(evt);
            }
        });
        txtSubCode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSubCodeActionPerformed(evt);
            }
        });

        jLabel29.setFont(new java.awt.Font("Iskoola Pota", 0, 16)); // NOI18N
        jLabel29.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel29.setText("කේතය :");

        txtSubRefNo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtSubRefNo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtSubRefNoFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtSubRefNoFocusLost(evt);
            }
        });
        txtSubRefNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSubRefNoActionPerformed(evt);
            }
        });

        jLabel30.setFont(new java.awt.Font("Iskoola Pota", 0, 16)); // NOI18N
        jLabel30.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel30.setText("අංකය :");

        jLabel39.setFont(new java.awt.Font("Iskoola Pota", 0, 16)); // NOI18N
        jLabel39.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel39.setText("ජංගම ගිණුම :");

        txtGLAcct.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtGLAcct.setFont(new java.awt.Font("Iskoola Pota", 0, 18)); // NOI18N
        txtGLAcct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtGLAcctActionPerformed(evt);
            }
        });
        txtGLAcct.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtGLAcctFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtGLAcctFocusLost(evt);
            }
        });

        javax.swing.GroupLayout jPanel15Layout = new javax.swing.GroupLayout(jPanel15);
        jPanel15.setLayout(jPanel15Layout);
        jPanel15Layout.setHorizontalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel15Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel30, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel28, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel27, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel25, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel26, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel39, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtSubName)
                    .addComponent(txtSubNameAmali)
                    .addComponent(txtSubContactPerson, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtGLAcct, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel15Layout.createSequentialGroup()
                        .addComponent(txtSubRefNo, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel29, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtSubCode, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(cmbSubType, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel15Layout.setVerticalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel15Layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtSubRefNo, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                    .addComponent(jLabel30, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                    .addComponent(jLabel29, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                    .addComponent(txtSubCode, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel28, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                    .addComponent(cmbSubType, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel25, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                    .addComponent(txtSubName, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtSubNameAmali, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                    .addComponent(jLabel26, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtSubContactPerson, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                    .addComponent(jLabel27, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtGLAcct, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                    .addComponent(jLabel39, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE))
                .addGap(5, 5, 5))
        );

        jButton9.setFont(new java.awt.Font("Iskoola Pota", 1, 18)); // NOI18N
        jButton9.setText("ඉවත් වන්න");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        jPanel16.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 255), 2));

        jLabel31.setFont(new java.awt.Font("Iskoola Pota", 0, 15)); // NOI18N
        jLabel31.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel31.setText("ලිපිනය 1 :");

        jLabel32.setFont(new java.awt.Font("Iskoola Pota", 0, 15)); // NOI18N
        jLabel32.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel32.setText("ලිපිනය 2 :");

        jLabel33.setFont(new java.awt.Font("Iskoola Pota", 0, 15)); // NOI18N
        jLabel33.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel33.setText("ලිපිනය 3 :");

        jLabel34.setFont(new java.awt.Font("Iskoola Pota", 0, 15)); // NOI18N
        jLabel34.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel34.setText("ලිපිනය 4 :");

        txtSubAddress1.setFont(new java.awt.Font("AMALEE", 0, 18)); // NOI18N
        txtSubAddress1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtSubAddress1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtSubAddress1FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtSubAddress1FocusLost(evt);
            }
        });
        txtSubAddress1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSubAddress1ActionPerformed(evt);
            }
        });

        txtSubAddress3.setFont(new java.awt.Font("AMALEE", 0, 18)); // NOI18N
        txtSubAddress3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtSubAddress3.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtSubAddress3FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtSubAddress3FocusLost(evt);
            }
        });
        txtSubAddress3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSubAddress3ActionPerformed(evt);
            }
        });

        txtSubAddress2.setFont(new java.awt.Font("AMALEE", 0, 18)); // NOI18N
        txtSubAddress2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtSubAddress2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtSubAddress2FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtSubAddress2FocusLost(evt);
            }
        });
        txtSubAddress2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSubAddress2ActionPerformed(evt);
            }
        });

        txtSubAddress4.setFont(new java.awt.Font("AMALEE", 0, 18)); // NOI18N
        txtSubAddress4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtSubAddress4.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtSubAddress4FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtSubAddress4FocusLost(evt);
            }
        });
        txtSubAddress4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSubAddress4ActionPerformed(evt);
            }
        });

        jLabel35.setFont(new java.awt.Font("Iskoola Pota", 0, 15)); // NOI18N
        jLabel35.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel35.setText("දු.අංකයන් :");

        txtSubTP1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtSubTP1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtSubTP1FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtSubTP1FocusLost(evt);
            }
        });
        txtSubTP1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSubTP1ActionPerformed(evt);
            }
        });

        txtSubTP2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtSubTP2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtSubTP2FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtSubTP2FocusLost(evt);
            }
        });
        txtSubTP2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSubTP2ActionPerformed(evt);
            }
        });

        jLabel36.setFont(new java.awt.Font("Iskoola Pota", 0, 15)); // NOI18N
        jLabel36.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel36.setText("ඊ-මේල් :");

        txtSubEmail.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtSubEmail.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtSubEmailFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtSubEmailFocusLost(evt);
            }
        });
        txtSubEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSubEmailActionPerformed(evt);
            }
        });

        jPanel17.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 255), 2), "අනුමත මුදලට ගැනුම් සීමාව", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Iskoola Pota", 0, 15), new java.awt.Color(51, 51, 255))); // NOI18N

        jLabel38.setFont(new java.awt.Font("Iskoola Pota", 0, 15)); // NOI18N
        jLabel38.setText("ණය සීමාව");

        txtSubCreditLimit.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        txtSubCreditLimit.setText("0.00");
        txtSubCreditLimit.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtSubCreditLimit.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtSubCreditLimitFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtSubCreditLimitFocusLost(evt);
            }
        });
        txtSubCreditLimit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSubCreditLimitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel17Layout = new javax.swing.GroupLayout(jPanel17);
        jPanel17.setLayout(jPanel17Layout);
        jPanel17Layout.setHorizontalGroup(
            jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel17Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel38, javax.swing.GroupLayout.DEFAULT_SIZE, 142, Short.MAX_VALUE)
                    .addComponent(txtSubCreditLimit))
                .addGap(20, 20, 20))
        );
        jPanel17Layout.setVerticalGroup(
            jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel17Layout.createSequentialGroup()
                .addComponent(jLabel38, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtSubCreditLimit, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(3, 3, 3))
        );

        jPanel18.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 255), 2), "F7", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Iskoola Pota", 0, 15), new java.awt.Color(51, 51, 255))); // NOI18N

        optF7.setFont(new java.awt.Font("Iskoola Pota", 0, 15)); // NOI18N
        optF7.setText("F7 වාර්තාවට");

        javax.swing.GroupLayout jPanel18Layout = new javax.swing.GroupLayout(jPanel18);
        jPanel18.setLayout(jPanel18Layout);
        jPanel18Layout.setHorizontalGroup(
            jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel18Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(optF7)
                .addContainerGap(62, Short.MAX_VALUE))
        );
        jPanel18Layout.setVerticalGroup(
            jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel18Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(optF7)
                .addGap(0, 0, 0))
        );

        jPanel20.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 255), 2), "F10", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Iskoola Pota", 0, 15), new java.awt.Color(51, 51, 255))); // NOI18N

        optF10.setFont(new java.awt.Font("Iskoola Pota", 0, 15)); // NOI18N
        optF10.setText("<html><p>F10 සඳහා ජංගම ගිණුම වෙනස් කිරීම</p></html>");

        javax.swing.GroupLayout jPanel20Layout = new javax.swing.GroupLayout(jPanel20);
        jPanel20.setLayout(jPanel20Layout);
        jPanel20Layout.setHorizontalGroup(
            jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel20Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(optF10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel20Layout.setVerticalGroup(
            jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel20Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(optF10, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout jPanel16Layout = new javax.swing.GroupLayout(jPanel16);
        jPanel16.setLayout(jPanel16Layout);
        jPanel16Layout.setHorizontalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel16Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel36, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel35, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel33, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel31, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel32, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel34, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtSubAddress3)
                    .addComponent(txtSubAddress2)
                    .addComponent(txtSubAddress4, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel16Layout.createSequentialGroup()
                        .addComponent(txtSubTP1, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtSubTP2, javax.swing.GroupLayout.DEFAULT_SIZE, 216, Short.MAX_VALUE))
                    .addComponent(txtSubEmail)
                    .addComponent(txtSubAddress1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jPanel20, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel18, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel16Layout.setVerticalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel16Layout.createSequentialGroup()
                .addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel16Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtSubAddress1, javax.swing.GroupLayout.DEFAULT_SIZE, 27, Short.MAX_VALUE)
                            .addComponent(jLabel31, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtSubAddress2, javax.swing.GroupLayout.DEFAULT_SIZE, 27, Short.MAX_VALUE)
                            .addComponent(jLabel32, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtSubAddress3, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel16Layout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addComponent(jLabel33, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(3, 3, 3)
                        .addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtSubAddress4, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel34, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel35, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtSubTP1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txtSubTP2, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtSubEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel36, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel16Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jPanel17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(3, 3, 3)
                        .addComponent(jPanel18, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel20, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );

        jButton11.setFont(new java.awt.Font("Iskoola Pota", 1, 18)); // NOI18N
        jButton11.setText("සේව්");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });

        jButton12.setFont(new java.awt.Font("Iskoola Pota", 1, 18)); // NOI18N
        jButton12.setText("නව");
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Iskoola Pota", 0, 18)); // NOI18N
        jLabel1.setText("F2 = යතුරුපුවරුව                            F3 = පරිවර්තකය");

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel15, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel14, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel13Layout.createSequentialGroup()
                        .addComponent(jButton12, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton11, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(189, 189, 189)
                        .addComponent(jButton9, javax.swing.GroupLayout.DEFAULT_SIZE, 167, Short.MAX_VALUE))
                    .addComponent(jPanel16, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton9)
                    .addComponent(jButton11)
                    .addComponent(jButton12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtSubNameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtSubNameFocusGained
        focusGained(evt);
    }//GEN-LAST:event_txtSubNameFocusGained

    private void txtSubNameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtSubNameFocusLost
        focusLost(evt);
    }//GEN-LAST:event_txtSubNameFocusLost

    private void txtSubNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSubNameActionPerformed

    }//GEN-LAST:event_txtSubNameActionPerformed

    private void txtSubContactPersonFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtSubContactPersonFocusGained
        focusGained(evt);
    }//GEN-LAST:event_txtSubContactPersonFocusGained

    private void txtSubContactPersonFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtSubContactPersonFocusLost
        focusLost(evt);
    }//GEN-LAST:event_txtSubContactPersonFocusLost

    private void txtSubContactPersonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSubContactPersonActionPerformed
        new FindSectionOrOutsider(this, true, TableHeaders.OUTSIDERFINDER_TABLE_MODEL, TableHeaders.OUTSIDERFINDER_TABLE_MODEL2, 35, "කළමණාකරු").setVisible(true);
    }//GEN-LAST:event_txtSubContactPersonActionPerformed

    private void txtSubNameAmaliFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtSubNameAmaliFocusGained
        focusGained(evt);
    }//GEN-LAST:event_txtSubNameAmaliFocusGained

    private void txtSubNameAmaliFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtSubNameAmaliFocusLost
        focusLost(evt);
    }//GEN-LAST:event_txtSubNameAmaliFocusLost

    private void txtSubNameAmaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSubNameAmaliActionPerformed

    }//GEN-LAST:event_txtSubNameAmaliActionPerformed

    private void txtSubCodeFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtSubCodeFocusGained
        focusGained(evt);
    }//GEN-LAST:event_txtSubCodeFocusGained

    private void txtSubCodeFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtSubCodeFocusLost
        focusLost(evt);
    }//GEN-LAST:event_txtSubCodeFocusLost

    private void txtSubCodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSubCodeActionPerformed
        txtSubName.grabFocus();
    }//GEN-LAST:event_txtSubCodeActionPerformed

    private void txtSubRefNoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtSubRefNoFocusGained
        focusGained(evt);
    }//GEN-LAST:event_txtSubRefNoFocusGained

    private void txtSubRefNoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtSubRefNoFocusLost
        focusLost(evt);
    }//GEN-LAST:event_txtSubRefNoFocusLost

    private void txtSubRefNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSubRefNoActionPerformed
        cmbSubType.grabFocus();
    }//GEN-LAST:event_txtSubRefNoActionPerformed

    private void txtGLAcctActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtGLAcctActionPerformed
        new FindAccount5Data(this, true, 11, 2).setVisible(true);
    }//GEN-LAST:event_txtGLAcctActionPerformed

    private void txtGLAcctFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtGLAcctFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_txtGLAcctFocusGained

    private void txtGLAcctFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtGLAcctFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_txtGLAcctFocusLost

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        FindSectionOrOutsider.refreshItem.doClick();
        dispose();
    }//GEN-LAST:event_jButton9ActionPerformed

    private void txtSubAddress1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtSubAddress1FocusGained
        focusGained(evt);
    }//GEN-LAST:event_txtSubAddress1FocusGained

    private void txtSubAddress1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtSubAddress1FocusLost
        focusLost(evt);
    }//GEN-LAST:event_txtSubAddress1FocusLost

    private void txtSubAddress1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSubAddress1ActionPerformed
        new UnicodeKeyBoard(this, true, txtSubAddress1).setVisible(true);
        txtSubAddress2.grabFocus();
    }//GEN-LAST:event_txtSubAddress1ActionPerformed

    private void txtSubAddress3FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtSubAddress3FocusGained
        focusGained(evt);
    }//GEN-LAST:event_txtSubAddress3FocusGained

    private void txtSubAddress3FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtSubAddress3FocusLost
        focusLost(evt);
    }//GEN-LAST:event_txtSubAddress3FocusLost

    private void txtSubAddress3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSubAddress3ActionPerformed
        new UnicodeKeyBoard(this, true, txtSubAddress3).setVisible(true);
        txtSubAddress4.grabFocus();
    }//GEN-LAST:event_txtSubAddress3ActionPerformed

    private void txtSubAddress2FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtSubAddress2FocusGained
        focusGained(evt);
    }//GEN-LAST:event_txtSubAddress2FocusGained

    private void txtSubAddress2FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtSubAddress2FocusLost
        focusLost(evt);
    }//GEN-LAST:event_txtSubAddress2FocusLost

    private void txtSubAddress2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSubAddress2ActionPerformed
        new UnicodeKeyBoard(this, true, txtSubAddress2).setVisible(true);
        txtSubAddress3.grabFocus();
    }//GEN-LAST:event_txtSubAddress2ActionPerformed

    private void txtSubAddress4FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtSubAddress4FocusGained
        focusGained(evt);
    }//GEN-LAST:event_txtSubAddress4FocusGained

    private void txtSubAddress4FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtSubAddress4FocusLost
        focusLost(evt);
    }//GEN-LAST:event_txtSubAddress4FocusLost

    private void txtSubAddress4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSubAddress4ActionPerformed
        new UnicodeKeyBoard(this, true, txtSubAddress4).setVisible(true);
        txtSubTP1.grabFocus();
    }//GEN-LAST:event_txtSubAddress4ActionPerformed

    private void txtSubTP1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtSubTP1FocusGained
        focusGained(evt);
    }//GEN-LAST:event_txtSubTP1FocusGained

    private void txtSubTP1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtSubTP1FocusLost
        focusLost(evt);
    }//GEN-LAST:event_txtSubTP1FocusLost

    private void txtSubTP1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSubTP1ActionPerformed
        txtSubTP2.grabFocus();
    }//GEN-LAST:event_txtSubTP1ActionPerformed

    private void txtSubTP2FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtSubTP2FocusGained
        focusGained(evt);
    }//GEN-LAST:event_txtSubTP2FocusGained

    private void txtSubTP2FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtSubTP2FocusLost
        focusLost(evt);
    }//GEN-LAST:event_txtSubTP2FocusLost

    private void txtSubTP2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSubTP2ActionPerformed
        txtSubEmail.grabFocus();
    }//GEN-LAST:event_txtSubTP2ActionPerformed

    private void txtSubEmailFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtSubEmailFocusGained
        focusGained(evt);
    }//GEN-LAST:event_txtSubEmailFocusGained

    private void txtSubEmailFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtSubEmailFocusLost
        focusLost(evt);
    }//GEN-LAST:event_txtSubEmailFocusLost

    private void txtSubEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSubEmailActionPerformed
        txtSubCreditLimit.grabFocus();
    }//GEN-LAST:event_txtSubEmailActionPerformed

    private void txtSubCreditLimitFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtSubCreditLimitFocusGained
        focusGained(evt);
    }//GEN-LAST:event_txtSubCreditLimitFocusGained

    private void txtSubCreditLimitFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtSubCreditLimitFocusLost
        focusLost(evt);
    }//GEN-LAST:event_txtSubCreditLimitFocusLost

    private void txtSubCreditLimitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSubCreditLimitActionPerformed
        jButton11.grabFocus();
    }//GEN-LAST:event_txtSubCreditLimitActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        if (saveSubSection()) {
            int i = JOptionPane.showConfirmDialog(this, "සේව් කිරීම සම්පූර්ණයි. නැවත ඇතුලත් කිරීමක් අවශ්‍යද?", "නැවත ඇතුලත් කිරීමක් අවශ්‍යද?", JOptionPane.YES_NO_OPTION, JOptionPane.INFORMATION_MESSAGE);
            if (i == JOptionPane.YES_OPTION) {
                clearSubSectionDialog();
            } else {
                clearSubSectionDialog();
                dispose();
            }
            FindSectionOrOutsider.refreshItem.doClick();
        }

    }//GEN-LAST:event_jButton11ActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        saveSubSection();
        setAllEditable(true);
    }//GEN-LAST:event_jButton12ActionPerformed

    private void txtSubNameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSubNameKeyReleased
        if (evt.getKeyCode() == KeyEvent.VK_F2) {
            new UnicodeKeyBoard(this, true, txtSubNameAmali, txtSubName, false).setVisible(true);
            txtSubNameAmali.grabFocus();
        } else if (evt.getKeyCode() == KeyEvent.VK_F3) {
            new UnicodeKeyBoard(this, true, txtSubName).setVisible(true);
        }
    }//GEN-LAST:event_txtSubNameKeyReleased

    private void txtSubNameAmaliKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSubNameAmaliKeyReleased
        if (evt.getKeyCode() == KeyEvent.VK_F2) {
            new AmaliKeyBoard(this, true, txtSubNameAmali, txtSubName, false).setVisible(true);
            txtSubContactPerson.grabFocus();
        } else if (evt.getKeyCode() == KeyEvent.VK_F3) {
            new UnicodeKeyBoard(this, true, txtSubNameAmali).setVisible(true);
        }
    }//GEN-LAST:event_txtSubNameAmaliKeyReleased

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        FindSectionOrOutsider.refreshItem.doClick();
    }//GEN-LAST:event_formWindowClosing

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SubSectionDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SubSectionDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SubSectionDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SubSectionDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                SubSectionDialog dialog = new SubSectionDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    org.nbs.components.HiddenItemComboBox cmbSubType;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    public static javax.swing.JLabel jLabel24;
    public static javax.swing.JLabel jLabel25;
    public static javax.swing.JLabel jLabel26;
    public static javax.swing.JLabel jLabel27;
    public static javax.swing.JLabel jLabel28;
    public static javax.swing.JLabel jLabel29;
    public static javax.swing.JLabel jLabel30;
    public static javax.swing.JLabel jLabel31;
    public static javax.swing.JLabel jLabel32;
    public static javax.swing.JLabel jLabel33;
    public static javax.swing.JLabel jLabel34;
    public static javax.swing.JLabel jLabel35;
    public static javax.swing.JLabel jLabel36;
    public static javax.swing.JLabel jLabel38;
    public static javax.swing.JLabel jLabel39;
    public static javax.swing.JPanel jPanel13;
    public static javax.swing.JPanel jPanel14;
    public static javax.swing.JPanel jPanel15;
    public static javax.swing.JPanel jPanel16;
    public static javax.swing.JPanel jPanel17;
    public static javax.swing.JPanel jPanel18;
    public static javax.swing.JPanel jPanel20;
    javax.swing.JCheckBox optF10;
    javax.swing.JCheckBox optF7;
    static org.nbs.components.HiddenIDTextField txtGLAcct;
    javax.swing.JTextField txtSubAddress1;
    javax.swing.JTextField txtSubAddress2;
    javax.swing.JTextField txtSubAddress3;
    javax.swing.JTextField txtSubAddress4;
    javax.swing.JTextField txtSubCode;
    static org.nbs.components.HiddenIDTextField txtSubContactPerson;
    javax.swing.JTextField txtSubCreditLimit;
    javax.swing.JTextField txtSubEmail;
    javax.swing.JTextField txtSubName;
    javax.swing.JTextField txtSubNameAmali;
    javax.swing.JTextField txtSubRefNo;
    javax.swing.JTextField txtSubTP1;
    javax.swing.JTextField txtSubTP2;
    // End of variables declaration//GEN-END:variables

    private void focusGained(FocusEvent evt) {
        evt.getComponent().setBackground(Color.YELLOW);
    }

    private void focusLost(FocusEvent evt) {
        evt.getComponent().setBackground(Color.WHITE);
    }

    private boolean saveSubSection() {
        if (!subSectionMFID.equals("0") && (txtSubName.getText().trim().isEmpty() || txtSubNameAmali.getText().trim().isEmpty())) {
            JOptionPane.showMessageDialog(this, "යුනිකෝඩ් හෝ අමාලි නාමය ඇතුලත් කර නොමැත. සේව් නොවේ.", "සේව් නොවේ.", JOptionPane.ERROR_MESSAGE);
            return false;
        } else {
            try {
                List<Object> inputs = new ArrayList<>();
                inputs.add(subSectionMFID);
                inputs.add(cmbSubType.getSelectedItem().getId());
                inputs.add(txtSubCode.getText());
                inputs.add(txtSubNameAmali.getText());
                inputs.add(txtSubName.getText());
                inputs.add(txtSubAddress1.getText());
                inputs.add(txtSubAddress2.getText());
                inputs.add(txtSubAddress3.getText());
                inputs.add(txtSubAddress4.getText());
                inputs.add(txtSubTP1.getText());
                inputs.add(txtSubTP2.getText());
                inputs.add(txtSubEmail.getText());
                inputs.add(txtSubContactPerson.getId());
                inputs.add(txtSubCreditLimit.getText());
                inputs.add(optF7.isSelected());
                inputs.add(txtGLAcct.getId());
                inputs.add(optF10.isSelected());
                inputs.add("@recid");

                List<Object> output = ServerConnection.getServerConnector().insertData(inputs, "ssp_Act_Insert_Act_Sections_Sub", 1);
                subSectionMFID = String.valueOf(output.get(0));
                txtSubRefNo.setText(subSectionMFID);
                removeNull();
                return true;
            } catch (SQLException ex) {
                Logger.getLogger(FindSectionOrOutsider.class.getName()).log(Level.SEVERE, null, ex);
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(FindSectionOrOutsider.class.getName()).log(Level.SEVERE, null, ex);
            } catch (RemoteException ex) {
                Logger.getLogger(FindSectionOrOutsider.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        return false;
    }

    private void clearSubSectionDialog() {
        subSectionMFID = "0";
        Component fields1[] = {cmbSubType, txtSubCode, txtSubNameAmali, txtSubName, txtSubAddress1, txtSubAddress2, txtSubAddress3, txtSubAddress4, txtSubTP1, txtSubTP2, txtSubEmail, txtSubContactPerson, txtSubCreditLimit, optF7};
        for (Component component : fields1) {
            if (component instanceof JTextField) {
                ((JTextField) component).setText("");
                if (component instanceof HiddenIDTextField) {
                    ((HiddenIDTextField) component).setId(0);
                }
            } else if (component instanceof JCheckBox) {
                ((JCheckBox) component).setSelected(false);
            }
//            else if (component instanceof JComboBox) {
//                ((JComboBox) component).setSelectedIndex(0);
//            }
        }
        txtSubCreditLimit.setText("0.00");
        removeNull();
    }

    private void removeNull() {
        JTextField textFields[] = {txtGLAcct, txtSubAddress1, txtSubAddress2, txtSubAddress3, txtSubAddress4, txtSubCode, txtSubContactPerson, txtSubCreditLimit, txtSubEmail, txtSubName, txtSubNameAmali, txtSubRefNo, txtSubTP1, txtSubTP2};
        for (JTextField textField : textFields) {
            JTextFieldRemoveNull.removeNull(textField);
        }
    }

    private void setSubSectionDataEdit(String id) {
        try {
            List<Object> inputs = new ArrayList<>();
            inputs.add(id);
            List<Object> output = ServerConnection.getServerConnector().searchSingleResult(inputs, "ssp_Act_Edit_Act_Sections_Sub", 19);

            txtSubRefNo.setText(String.valueOf(output.get(0)));
            subSectionMFID = txtSubRefNo.getText();
            HiddenItemComboBoxSelector.setSelectedItem(cmbSubType, Integer.parseInt(String.valueOf(output.get(1))), String.valueOf(output.get(2)));
            txtSubCode.setText(String.valueOf(output.get(3)));
            txtSubNameAmali.setText(String.valueOf(output.get(4)));
            txtSubName.setText(String.valueOf(output.get(5)));
            txtSubAddress1.setText(String.valueOf(output.get(6)));
            txtSubAddress2.setText(String.valueOf(output.get(7)));
            txtSubAddress3.setText(String.valueOf(output.get(8)));
            txtSubAddress4.setText(String.valueOf(output.get(9)));
            txtSubTP1.setText(String.valueOf(output.get(10)));
            txtSubTP2.setText(String.valueOf(output.get(11)));
            txtSubEmail.setText(String.valueOf(output.get(12)));
            txtSubContactPerson.setText(String.valueOf(output.get(13)));
            txtSubCreditLimit.setText(String.valueOf(output.get(14)));
            optF7.setSelected(Boolean.valueOf(String.valueOf(output.get(15))));
            txtGLAcct.setId(Integer.parseInt(String.valueOf(output.get(16))));
            txtGLAcct.setText(String.valueOf(output.get(17)));
            if (output.get(18).equals("0")) {
                optF10.setSelected(false);
            } else {
                optF10.setSelected(true);
            }
            removeNull();
//            System.out.println(txtSubRefNo.getText());
        } catch (SQLException ex) {
            Logger.getLogger(SubSectionDialog.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(SubSectionDialog.class.getName()).log(Level.SEVERE, null, ex);
        } catch (RemoteException ex) {
            Logger.getLogger(SubSectionDialog.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void loadCombo() {

        List<Object> inputs2 = new ArrayList<>();
        try {
            inputs2.add(5);
            inputs2.add(null);
            inputs2.add(null);
            inputs2.add(0);
            inputs2.add(0);
            List<List<Object>> outputs2 = ServerConnection.getServerConnector().searchMultipleResults(inputs2, "ssp_F28_LoadCombo_ViewStock", 4);
            Vector v = new Vector();
            for (List<Object> output : outputs2) {
                v.add(new Item(Integer.parseInt(String.valueOf(output.get(0))), String.valueOf(output.get(2))));
            }
            cmbSubType.setModel(new DefaultComboBoxModel<>(v));
            removeNull();
        } catch (RemoteException ex) {
            Logger.getLogger(FindSectionOrOutsider.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(FindSectionOrOutsider.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(FindSectionOrOutsider.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void setAllEditable(boolean editable) {
        JTextField fields[] = {txtGLAcct, txtSubAddress1, txtSubAddress2, txtSubAddress3, txtSubAddress4, txtSubCode, txtSubContactPerson, txtSubCreditLimit, txtSubEmail, txtSubName, txtSubNameAmali, txtSubRefNo, txtSubTP1, txtSubTP2};
        for (JTextField field : fields) {
            field.setEditable(true);
        }
    }
}
