/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.nbs.view.Reports;

import Sources.ReportFileLocator;
import Sources.TextPrompt;
import com.jidesoft.plaf.aqua.AquaJideTabbedPaneUI;
import com.jidesoft.plaf.office2007.Office2007JideTabbedPaneUI;
import com.nbs.connection.DB;
import com.nbs.view.common.GeneralUserLogin;
import com.nbs.view.common.TableHeaders;
import com.nbs.view.common.search.FindSectionOrOutsider;
import com.nbs.view.manager.AuditReportDetails;
import com.nbs.view.manager.FinancialYearCompletedMonths;
import static com.nbs.view.manager.ManagerOperational.jPanel7;
import com.nbs.view.manager.ManagerOperationalNavigation;
import com.sun.java.swing.plaf.motif.MotifTabbedPaneUI;
import com.sun.java.swing.plaf.windows.WindowsTabbedPaneUI;
import java.awt.Cursor;
import java.awt.Font;
import java.sql.SQLException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.HashMap;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.plaf.metal.MetalTabbedPaneUI;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperPrintManager;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author mmh
 */
public class AuditReportPanel extends javax.swing.JPanel {

    private int selectedMonth;
    private int yearID;
    private int completed;
    private int screenType;

    /**
     * Creates new form AuditReportPanel
     */
    public AuditReportPanel() {
        initComponents();
//        jTabbedPane2.setUI(new MetalTabbedPaneUI());
        TextPrompt promptMain = new TextPrompt("මූලික අංශය තෝරාගන්න", txtSection);
        promptMain.setFont(new Font("Iskoola Pota", Font.PLAIN, 18));
        TextPrompt promptSub = new TextPrompt("අනු අංශය තෝරාගන්න", txtSubSection);
        promptSub.setFont(new Font("Iskoola Pota", Font.PLAIN, 18));
        setVisible(true);
    }

    public AuditReportPanel(int selectedMonth, int yearID) {
        this();
        this.selectedMonth = selectedMonth-1;
        this.yearID = yearID;
        jdtMonth.setMonth(this.selectedMonth);
    }

    public AuditReportPanel(int selectedMonth, int yearID, int completed,String selectedMonthStartedDate,String selectedMonthEndedDate) {
        this(selectedMonth, yearID);
        try {
            this.completed = completed;
            System.out.println(selectedMonthStartedDate+"Aaa");
            SimpleDateFormat df=new SimpleDateFormat("yyyy-MM-dd");
            Date stDate=df.parse(selectedMonthStartedDate);
            Date enDate=df.parse(selectedMonthEndedDate);
            jdtFrom.setDate(stDate);
            jdtTo.setDate(enDate);
            if (completed == 1) {
                jRadioButton2.setEnabled(false);
                jLabel7.setVisible(false);
            } else {
                jRadioButton2.setEnabled(true);
                jRadioButton2.setSelected(true);
            }
        } catch (ParseException ex) {
            Logger.getLogger(AuditReportPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jdtFrom = new com.toedter.calendar.JDateChooser();
        jdtTo = new com.toedter.calendar.JDateChooser();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jdtMonth = new com.toedter.calendar.JMonthChooser();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel4 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton41 = new javax.swing.JButton();
        lblTitle = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jButton11 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        jButton14 = new javax.swing.JButton();
        jButton15 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        lblTitle1 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jButton25 = new javax.swing.JButton();
        jButton26 = new javax.swing.JButton();
        jButton27 = new javax.swing.JButton();
        jButton28 = new javax.swing.JButton();
        jButton47 = new javax.swing.JButton();
        lblTitle2 = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        jButton29 = new javax.swing.JButton();
        jButton30 = new javax.swing.JButton();
        jButton31 = new javax.swing.JButton();
        jButton32 = new javax.swing.JButton();
        jButton33 = new javax.swing.JButton();
        jButton34 = new javax.swing.JButton();
        txtSection = new org.nbs.components.HiddenIDTextField();
        lblTitle3 = new javax.swing.JLabel();
        jPanel12 = new javax.swing.JPanel();
        txtSubSection = new org.nbs.components.HiddenIDTextField();
        jButton35 = new javax.swing.JButton();
        jButton36 = new javax.swing.JButton();
        jButton37 = new javax.swing.JButton();
        jButton38 = new javax.swing.JButton();
        jButton39 = new javax.swing.JButton();
        jButton40 = new javax.swing.JButton();
        lblTitle4 = new javax.swing.JLabel();
        jPanel13 = new javax.swing.JPanel();
        jButton42 = new javax.swing.JButton();
        jButton43 = new javax.swing.JButton();
        jButton44 = new javax.swing.JButton();
        jButton45 = new javax.swing.JButton();
        jButton46 = new javax.swing.JButton();
        lblTitle5 = new javax.swing.JLabel();
        jPanel15 = new javax.swing.JPanel();
        jButton56 = new javax.swing.JButton();
        jButton57 = new javax.swing.JButton();
        lblTitle6 = new javax.swing.JLabel();
        jPanel16 = new javax.swing.JPanel();
        lblTitle7 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();

        setMinimumSize(new java.awt.Dimension(976, 545));

        jPanel1.setBackground(java.awt.Color.white);

        jPanel2.setBackground(java.awt.Color.white);

        jPanel3.setBackground(java.awt.Color.white);
        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(51, 204, 255), new java.awt.Color(51, 204, 255)));

        jLabel1.setFont(new java.awt.Font("Iskoola Pota", 0, 15)); // NOI18N
        jLabel1.setText("දින");

        jdtFrom.setDateFormatString("yyyy-MM-dd");
        jdtFrom.setEnabled(false);

        jdtTo.setDateFormatString("yyyy-MM-dd");
        jdtTo.setEnabled(false);

        jLabel2.setFont(new java.awt.Font("Iskoola Pota", 0, 15)); // NOI18N
        jLabel2.setText("සිට");

        jLabel3.setFont(new java.awt.Font("Iskoola Pota", 0, 15)); // NOI18N
        jLabel3.setText("දක්වා");

        jdtMonth.setEnabled(false);

        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setFont(new java.awt.Font("DL-Manel-bold.-x", 0, 15)); // NOI18N
        jRadioButton1.setSelected(true);
        jRadioButton1.setText("uqo%Kh");

        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setFont(new java.awt.Font("DL-Manel-bold.-x", 0, 15)); // NOI18N
        jRadioButton2.setText("fjkia lsÍu");

        jLabel6.setFont(new java.awt.Font("Iskoola Pota", 0, 15)); // NOI18N
        jLabel6.setText("මස");

        jLabel7.setFont(new java.awt.Font("Iskoola Pota", 0, 18)); // NOI18N
        jLabel7.setForeground(java.awt.Color.red);
        jLabel7.setText("සම්පූර්ණ කර නොමැත");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jdtFrom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jdtTo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jdtMonth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jdtTo, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                    .addComponent(jdtFrom, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jdtMonth, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jRadioButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jRadioButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jTabbedPane2.setFont(new java.awt.Font("Iskoola Pota", 0, 18)); // NOI18N

        jPanel4.setBackground(java.awt.Color.white);

        jButton1.setFont(new java.awt.Font("Iskoola Pota", 0, 18)); // NOI18N
        jButton1.setText("01.වෙලඳාම අඩු වැඩි මුදල් මාරුකිරීම");

        jButton2.setFont(new java.awt.Font("Iskoola Pota", 0, 18)); // NOI18N
        jButton2.setText("02.පොදු අංශ ආදායම් වියදම් මාරු කිරීම්");

        jButton3.setFont(new java.awt.Font("Iskoola Pota", 0, 18)); // NOI18N
        jButton3.setText("03.පොදු පරිපාලන අංශ ආදායම් වියදම් මාරු කිරීම්");

        jButton41.setFont(new java.awt.Font("Iskoola Pota", 0, 18)); // NOI18N
        jButton41.setText("04. අංශ ගත මූලික තොරතුරු අතුලත් කිරීම");
        jButton41.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton41ActionPerformed(evt);
            }
        });

        lblTitle.setBackground(new java.awt.Color(0, 114, 198));
        lblTitle.setFont(new java.awt.Font("Iskoola Pota", 0, 18)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(255, 255, 255));
        lblTitle.setText("  01. F28 වාර්තා සඳහා මුලික වෙන්කිරීම්");
        lblTitle.setOpaque(true);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, 450, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(23, 23, 23)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton41, javax.swing.GroupLayout.DEFAULT_SIZE, 449, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addComponent(lblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton3)
                    .addComponent(jButton41))
                .addContainerGap(227, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("පියවර 1", jPanel4);

        jPanel6.setBackground(java.awt.Color.white);

        jButton11.setFont(new java.awt.Font("DL-Manel-bold.-x", 0, 18)); // NOI18N
        jButton11.setText("<html><font face=\"DL-Manel-bold.-x\" size=\"5\"> 02'3 wdxYsl nexl= cx.u .sKqï fIaY l<ukdlrKh </font></html>");
        jButton11.setToolTipText("<html><font face=\"DL-Manel-bold.-x\" size=\"5\">\n02'3 wdxYsl nexl= cx.u .sKqï fIaY l<ukdlrKh\n</font></html>");
        jButton11.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);

        jButton13.setFont(new java.awt.Font("DL-Manel-bold.-x", 0, 18)); // NOI18N
        jButton13.setText("<html><font face=\"DL-Manel-bold.-x\" size=\"5\"> 04 fiajl wNsfm%rKh i|yd .;a l%shdud¾. </font></html>");
        jButton13.setToolTipText("<html><font face=\"DL-Manel-bold.-x\" size=\"5\"> 04 fiajl wNsfm%rKh i|yd .;a l%shdud¾. </font></html>");
        jButton13.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);

        jButton14.setFont(new java.awt.Font("DL-Manel-bold.-x", 0, 18)); // NOI18N
        jButton14.setText("<html><font face=\"DL-Manel-bold.-x\" size=\"5\"> 05 idudðl iqNidOkh </font></html> ");
        jButton14.setToolTipText("<html><font face=\"DL-Manel-bold.-x\" size=\"5\"> 05 idudðl iqNidOkh </font></html> ");
        jButton14.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);

        jButton15.setFont(new java.awt.Font("DL-Manel-bold.-x", 0, 18)); // NOI18N
        jButton15.setText("06 iudc j.lSï");
        jButton15.setToolTipText("<html><font face=\"DL-Manel-bold.-x\" size=\"5\"> 06 iudc j.lSï </font></html> ");
        jButton15.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButton15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton15ActionPerformed(evt);
            }
        });

        jButton7.setFont(new java.awt.Font("DL-Manel-bold.-x", 0, 18)); // NOI18N
        jButton7.setText("01'wdxYsl ld¾hidOkh 1)2");
        jButton7.setToolTipText("<html><font face=\"DL-Manel-bold.-x\" size=\"5\"> 01'wdxYsl ld¾hidOkh 1)2 </font></html>");
        jButton7.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);

        jButton8.setFont(new java.awt.Font("DL-Manel-bold.-x", 0, 18)); // NOI18N
        jButton8.setText("<html><font face=\"DL-Manel-bold.-x\" size=\"5\">02'ld¾hidOkh\"uQ,H ;;ajh yd uqo,a m%jdyh</font></html> ");
        jButton8.setToolTipText("<html><font face=\"DL-Manel-bold.-x\" size=\"5\">02'ld¾hidOkh\"uQ,H ;;ajh yd uqo,a m%jdyh</font></html>\n");
        jButton8.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);

        jButton10.setFont(new java.awt.Font("DL-Manel-bold.-x", 0, 18)); // NOI18N
        jButton10.setText(".%dóh nexl= wxYfha uqo,a fjk;a wxY j,g udre lsÍu");
        jButton10.setToolTipText("<html><font face=\"DL-Manel-bold.-x\" size=\"5\">\n02'2 .%dóh nexl= wxYfha uqo,a fjk;a wxY j,g udrelsÍï\n</font></html>");
        jButton10.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);

        jButton9.setFont(new java.awt.Font("DL-Manel-bold.-x", 0, 18)); // NOI18N
        jButton9.setText("<html><font face=\"DL-Manel-bold.-x\" size=\"5\"> 02'1 .%dóh nexl= wxYfha uQ,H ;;ajh^l%shdldÍ& </font></html>");
        jButton9.setToolTipText("<html><font face=\"DL-Manel-bold.-x\" size=\"5\">\n02'1 .%dóh nexl= wxYfha uQ,H ;;ajh^l%shdldÍ&\n</font></html>");
        jButton9.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);

        jButton12.setFont(new java.awt.Font("DL-Manel-bold.-x", 0, 18)); // NOI18N
        jButton12.setText("<html><font face=\"DL-Manel-bold.-x\" size=\"5\"> 03 fiajl uKav, ixj¾Okh </font></html>");
        jButton12.setToolTipText("<html><font face=\"DL-Manel-bold.-x\" size=\"5\"> 03 fiajl uKav, ixj¾Okh </font></html>");
        jButton12.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });

        lblTitle1.setBackground(new java.awt.Color(0, 114, 198));
        lblTitle1.setFont(new java.awt.Font("Iskoola Pota", 0, 18)); // NOI18N
        lblTitle1.setForeground(new java.awt.Color(255, 255, 255));
        lblTitle1.setText("  02. විධායක සාරාංශය හා මූලික තොරතුරු");
        lblTitle1.setOpaque(true);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblTitle1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton13)
                    .addComponent(jButton11)
                    .addComponent(jButton9, javax.swing.GroupLayout.DEFAULT_SIZE, 450, Short.MAX_VALUE)
                    .addComponent(jButton7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton14, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton12, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton10, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 448, Short.MAX_VALUE)
                    .addComponent(jButton8))
                .addGap(18, 18, 18))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addComponent(lblTitle1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton7)
                    .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton10))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButton15)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("පියවර  2", jPanel6);

        jPanel8.setBackground(java.awt.Color.white);

        jButton25.setFont(new java.awt.Font("DL-Manel-bold.-x", 0, 18)); // NOI18N
        jButton25.setText("uQ,H ;;aj jd¾;dj");
        jButton25.setToolTipText("<html><font face=\"DL-Manel-bold.-x\" size=\"5\"> 01'wdxYsl ld¾hidOkh 1)2 </font></html>");
        jButton25.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);

        jButton26.setFont(new java.awt.Font("DL-Manel-bold.-x", 0, 18)); // NOI18N
        jButton26.setText("úia;SrK fmdÿ wdodhï m%ldYh uQ,sl wxY");
        jButton26.setToolTipText("<html><font face=\"DL-Manel-bold.-x\" size=\"5\"> 01'wdxYsl ld¾hidOkh 1)2 </font></html>");
        jButton26.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButton26.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton26ActionPerformed(evt);
            }
        });

        jButton27.setFont(new java.awt.Font("DL-Manel-bold.-x", 0, 18)); // NOI18N
        jButton27.setText("úia;SrK fmdÿ wdodhï m%ldYh wkq wxY");
        jButton27.setToolTipText("<html><font face=\"DL-Manel-bold.-x\" size=\"5\"> 01'wdxYsl ld¾hidOkh 1)2 </font></html>");
        jButton27.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButton27.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton27ActionPerformed(evt);
            }
        });

        jButton28.setFont(new java.awt.Font("DL-Manel-bold.-x", 0, 18)); // NOI18N
        jButton28.setText("taldnoaO fYaI msßlaiqu");
        jButton28.setToolTipText("<html><font face=\"DL-Manel-bold.-x\" size=\"5\"> 01'wdxYsl ld¾hidOkh 1)2 </font></html>");
        jButton28.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);

        jButton47.setFont(new java.awt.Font("DL-Manel-bold.-x", 0, 18)); // NOI18N
        jButton47.setText("uQ,H ;;aj jd¾;dj");
        jButton47.setToolTipText("<html><font face=\"DL-Manel-bold.-x\" size=\"5\"> 01'wdxYsl ld¾hidOkh 1)2 </font></html>");
        jButton47.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);

        lblTitle2.setBackground(new java.awt.Color(0, 114, 198));
        lblTitle2.setFont(new java.awt.Font("Iskoola Pota", 0, 18)); // NOI18N
        lblTitle2.setForeground(new java.awt.Color(255, 255, 255));
        lblTitle2.setText("   පොදු වාර්තාව");
        lblTitle2.setOpaque(true);

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTitle2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButton28, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton25, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton26, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 446, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton47, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton27, javax.swing.GroupLayout.DEFAULT_SIZE, 458, Short.MAX_VALUE))))
                .addContainerGap())
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addComponent(lblTitle2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton25)
                    .addComponent(jButton47))
                .addGap(18, 18, 18)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton26)
                    .addComponent(jButton27))
                .addGap(18, 18, 18)
                .addComponent(jButton28)
                .addContainerGap(182, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("පියවර  3", jPanel8);

        jPanel10.setBackground(java.awt.Color.white);

        jButton29.setFont(new java.awt.Font("DL-Manel-bold.-x", 0, 18)); // NOI18N
        jButton29.setText("wdodhï m%ldYkh ksIamdok");
        jButton29.setToolTipText("<html><font face=\"DL-Manel-bold.-x\" size=\"5\"> 01'wdxYsl ld¾hidOkh 1)2 </font></html>");
        jButton29.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton29ActionPerformed(evt);
            }
        });

        jButton30.setFont(new java.awt.Font("DL-Manel-bold.-x", 0, 18)); // NOI18N
        jButton30.setText("wdodhï m%ldYkh fjk;a");
        jButton30.setToolTipText("<html><font face=\"DL-Manel-bold.-x\" size=\"5\"> 01'wdxYsl ld¾hidOkh 1)2 </font></html>");
        jButton30.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton30ActionPerformed(evt);
            }
        });

        jButton31.setFont(new java.awt.Font("DL-Manel-bold.-x", 0, 18)); // NOI18N
        jButton31.setText("wdodhï m%ldYkh nexl=");
        jButton31.setToolTipText("<html><font face=\"DL-Manel-bold.-x\" size=\"5\"> 01'wdxYsl ld¾hidOkh 1)2 </font></html>");
        jButton31.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton31ActionPerformed(evt);
            }
        });

        jButton32.setFont(new java.awt.Font("DL-Manel-bold.-x", 0, 18)); // NOI18N
        jButton32.setText("fufyhqï ;;aj jd¾;dj");
        jButton32.setToolTipText("<html><font face=\"DL-Manel-bold.-x\" size=\"5\"> 01'wdxYsl ld¾hidOkh 1)2 </font></html>");

        jButton33.setFont(new java.awt.Font("DL-Manel-bold.-x", 0, 18)); // NOI18N
        jButton33.setText("wfmalaIs; o< ,dN .e,mSu");
        jButton33.setToolTipText("<html><font face=\"DL-Manel-bold.-x\" size=\"5\"> 01'wdxYsl ld¾hidOkh 1)2 </font></html>");

        jButton34.setFont(new java.awt.Font("DL-Manel-bold.-x", 0, 18)); // NOI18N
        jButton34.setText("nexl= úIaf,aYK jd¾;dj");
        jButton34.setToolTipText("<html><font face=\"DL-Manel-bold.-x\" size=\"5\"> 01'wdxYsl ld¾hidOkh 1)2 </font></html>");

        txtSection.setFont(new java.awt.Font("AMALEE", 0, 18)); // NOI18N
        txtSection.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSectionActionPerformed(evt);
            }
        });

        lblTitle3.setBackground(new java.awt.Color(0, 114, 198));
        lblTitle3.setFont(new java.awt.Font("Iskoola Pota", 0, 18)); // NOI18N
        lblTitle3.setForeground(new java.awt.Color(255, 255, 255));
        lblTitle3.setText("   මූලික අංශගත වාර්තා");
        lblTitle3.setOpaque(true);

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtSection, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton30, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton31, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton29, javax.swing.GroupLayout.DEFAULT_SIZE, 445, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton32, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton33, javax.swing.GroupLayout.DEFAULT_SIZE, 459, Short.MAX_VALUE)
                            .addComponent(jButton34, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(lblTitle3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitle3, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txtSection, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton30)
                    .addComponent(jButton32))
                .addGap(18, 18, 18)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton31)
                    .addComponent(jButton33))
                .addGap(18, 18, 18)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton29)
                    .addComponent(jButton34))
                .addContainerGap(122, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("පියවර  4", jPanel10);

        jPanel12.setBackground(java.awt.Color.white);

        txtSubSection.setFont(new java.awt.Font("AMALEE", 0, 18)); // NOI18N
        txtSubSection.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSubSectionActionPerformed(evt);
            }
        });

        jButton35.setFont(new java.awt.Font("DL-Manel-bold.-x", 0, 18)); // NOI18N
        jButton35.setText("wdodhï m%ldYkh fjk;a");
        jButton35.setToolTipText("<html><font face=\"DL-Manel-bold.-x\" size=\"5\"> 01'wdxYsl ld¾hidOkh 1)2 </font></html>");
        jButton35.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton35ActionPerformed(evt);
            }
        });

        jButton36.setFont(new java.awt.Font("DL-Manel-bold.-x", 0, 18)); // NOI18N
        jButton36.setText("fufyhqï ;;aj jd¾;dj");
        jButton36.setToolTipText("<html><font face=\"DL-Manel-bold.-x\" size=\"5\"> 01'wdxYsl ld¾hidOkh 1)2 </font></html>");

        jButton37.setFont(new java.awt.Font("DL-Manel-bold.-x", 0, 18)); // NOI18N
        jButton37.setText("wfmalaIs; o< ,dN .e,mSu");
        jButton37.setToolTipText("<html><font face=\"DL-Manel-bold.-x\" size=\"5\"> 01'wdxYsl ld¾hidOkh 1)2 </font></html>");

        jButton38.setFont(new java.awt.Font("DL-Manel-bold.-x", 0, 18)); // NOI18N
        jButton38.setText("wdodhï m%ldYkh nexl=");
        jButton38.setToolTipText("<html><font face=\"DL-Manel-bold.-x\" size=\"5\"> 01'wdxYsl ld¾hidOkh 1)2 </font></html>");

        jButton39.setFont(new java.awt.Font("DL-Manel-bold.-x", 0, 18)); // NOI18N
        jButton39.setText("wdodhï m%ldYkh ksIamdok");
        jButton39.setToolTipText("<html><font face=\"DL-Manel-bold.-x\" size=\"5\"> 01'wdxYsl ld¾hidOkh 1)2 </font></html>");

        jButton40.setFont(new java.awt.Font("DL-Manel-bold.-x", 0, 18)); // NOI18N
        jButton40.setText("nexl= úIaf,aYK jd¾;dj");
        jButton40.setToolTipText("<html><font face=\"DL-Manel-bold.-x\" size=\"5\"> 01'wdxYsl ld¾hidOkh 1)2 </font></html>");

        lblTitle4.setBackground(new java.awt.Color(0, 114, 198));
        lblTitle4.setFont(new java.awt.Font("Iskoola Pota", 0, 18)); // NOI18N
        lblTitle4.setForeground(new java.awt.Color(255, 255, 255));
        lblTitle4.setText("   අනු අංශගත වාර්තා");
        lblTitle4.setOpaque(true);

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel12Layout.createSequentialGroup()
                        .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton38, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel12Layout.createSequentialGroup()
                                .addComponent(txtSubSection, javax.swing.GroupLayout.PREFERRED_SIZE, 448, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 10, Short.MAX_VALUE))
                            .addComponent(jButton39, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton35, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton36, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton37, javax.swing.GroupLayout.DEFAULT_SIZE, 452, Short.MAX_VALUE)
                            .addComponent(jButton40, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(lblTitle4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitle4, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txtSubSection, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton35)
                    .addComponent(jButton36))
                .addGap(18, 18, 18)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton38)
                    .addComponent(jButton37))
                .addGap(18, 18, 18)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton40)
                    .addComponent(jButton39))
                .addContainerGap(128, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("පියවර  5", jPanel12);

        jPanel13.setBackground(java.awt.Color.white);
        jPanel13.setForeground(new java.awt.Color(200, 138, 103));

        jButton42.setFont(new java.awt.Font("Iskoola Pota", 0, 18)); // NOI18N
        jButton42.setText("F15");
        jButton42.setToolTipText("<html><font face=\"DL-Manel-bold.-x\" size=\"5\"> 01'wdxYsl ld¾hidOkh 1)2 </font></html>");
        jButton42.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton42ActionPerformed(evt);
            }
        });

        jButton43.setFont(new java.awt.Font("Iskoola Pota", 0, 18)); // NOI18N
        jButton43.setText("F32");
        jButton43.setToolTipText("<html><font face=\"DL-Manel-bold.-x\" size=\"5\"> 01'wdxYsl ld¾hidOkh 1)2 </font></html>");
        jButton43.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton43ActionPerformed(evt);
            }
        });

        jButton44.setFont(new java.awt.Font("Iskoola Pota", 0, 18)); // NOI18N
        jButton44.setText("F33");
        jButton44.setToolTipText("<html><font face=\"DL-Manel-bold.-x\" size=\"5\"> 01'wdxYsl ld¾hidOkh 1)2 </font></html>");
        jButton44.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton44ActionPerformed(evt);
            }
        });

        jButton45.setFont(new java.awt.Font("DL-Manel-bold.-x", 0, 18)); // NOI18N
        jButton45.setText("m%dfoaYsl fj,| ie,a ú.%yh");
        jButton45.setToolTipText("<html><font face=\"DL-Manel-bold.-x\" size=\"5\"> 01'wdxYsl ld¾hidOkh 1)2 </font></html>");

        jButton46.setFont(new java.awt.Font("DL-Manel-bold.-x", 0, 18)); // NOI18N
        jButton46.setText("fj,| wxYfha msßjeh úIaf,aYkh");
        jButton46.setToolTipText("<html><font face=\"DL-Manel-bold.-x\" size=\"5\"> 01'wdxYsl ld¾hidOkh 1)2 </font></html>");

        lblTitle5.setBackground(new java.awt.Color(0, 114, 198));
        lblTitle5.setFont(new java.awt.Font("Iskoola Pota", 0, 18)); // NOI18N
        lblTitle5.setForeground(new java.awt.Color(255, 255, 255));
        lblTitle5.setText("  පාරිභෝගික අංශ වාර්තා");
        lblTitle5.setOpaque(true);

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel13Layout.createSequentialGroup()
                        .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton46, javax.swing.GroupLayout.DEFAULT_SIZE, 454, Short.MAX_VALUE)
                            .addComponent(jButton44, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton42, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton43, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton45, javax.swing.GroupLayout.DEFAULT_SIZE, 450, Short.MAX_VALUE)))
                    .addComponent(lblTitle5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitle5, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton42)
                    .addGroup(jPanel13Layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(jButton43, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton44, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton45, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jButton46)
                .addContainerGap(166, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("පියවර  6", jPanel13);

        jPanel15.setBackground(java.awt.Color.white);
        jPanel15.setForeground(new java.awt.Color(221, 58, 156));

        jButton56.setFont(new java.awt.Font("DL-Manel-bold.-x", 0, 18)); // NOI18N
        jButton56.setText("úia;Srk wdodhï m%ldYkh YdLd uÜgñka");
        jButton56.setToolTipText("<html><font face=\"DL-Manel-bold.-x\" size=\"5\"> 01'wdxYsl ld¾hidOkh 1)2 </font></html>");
        jButton56.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);

        jButton57.setFont(new java.awt.Font("DL-Manel-bold.-x", 0, 18)); // NOI18N
        jButton57.setText("uQ,H ;;aj úIaf,aYk jd¾;dj");
        jButton57.setToolTipText("<html><font face=\"DL-Manel-bold.-x\" size=\"5\"> 01'wdxYsl ld¾hidOkh 1)2 </font></html>");
        jButton57.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);

        lblTitle6.setBackground(new java.awt.Color(0, 114, 198));
        lblTitle6.setFont(new java.awt.Font("DL-Manel-bold.-x", 1, 18)); // NOI18N
        lblTitle6.setForeground(new java.awt.Color(255, 255, 255));
        lblTitle6.setText(".%dóh nexl= wxY jd¾;d");
        lblTitle6.setOpaque(true);

        javax.swing.GroupLayout jPanel15Layout = new javax.swing.GroupLayout(jPanel15);
        jPanel15.setLayout(jPanel15Layout);
        jPanel15Layout.setHorizontalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel15Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel15Layout.createSequentialGroup()
                        .addComponent(jButton56, javax.swing.GroupLayout.DEFAULT_SIZE, 452, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton57, javax.swing.GroupLayout.DEFAULT_SIZE, 458, Short.MAX_VALUE))
                    .addComponent(lblTitle6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel15Layout.setVerticalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel15Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitle6, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton57)
                    .addComponent(jButton56))
                .addContainerGap(268, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("පියවර  7", jPanel15);

        jPanel16.setBackground(java.awt.Color.white);

        lblTitle7.setBackground(new java.awt.Color(0, 114, 198));
        lblTitle7.setFont(new java.awt.Font("Iskoola Pota", 0, 18)); // NOI18N
        lblTitle7.setForeground(new java.awt.Color(255, 255, 255));
        lblTitle7.setText("  වෙනත් වාර්තා");
        lblTitle7.setOpaque(true);

        javax.swing.GroupLayout jPanel16Layout = new javax.swing.GroupLayout(jPanel16);
        jPanel16.setLayout(jPanel16Layout);
        jPanel16Layout.setHorizontalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel16Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitle7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(2, 2, 2))
        );
        jPanel16Layout.setVerticalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel16Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitle7, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(317, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("පියවර  8", jPanel16);

        jButton4.setFont(new java.awt.Font("Iskoola Pota", 0, 18)); // NOI18N
        jButton4.setText("වසන්න");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTabbedPane2)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 403, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton4)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton15ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton15ActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton12ActionPerformed

    private void jButton29ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton29ActionPerformed
        mainSectionReports("R027_F28_IncomeStatement_Production.jrxml");
    }//GEN-LAST:event_jButton29ActionPerformed

    private void jButton30ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton30ActionPerformed
        mainSectionReports("R027_F28_IncomeStatement_MainSection.jrxml");
    }//GEN-LAST:event_jButton30ActionPerformed

    private void jButton31ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton31ActionPerformed
        mainSectionReports("R031_F28_IncomeStatementBank.jrxml");
    }//GEN-LAST:event_jButton31ActionPerformed

    private void txtSectionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSectionActionPerformed
        new FindSectionOrOutsider(null, TableHeaders.SECTIONFINDER_TABLE_MODEL, TableHeaders.SECTIONFINDER_TABLE_MODEL, 54, "මූලික අංශය").setVisible(true);
    }//GEN-LAST:event_txtSectionActionPerformed

    private void txtSubSectionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSubSectionActionPerformed
        new FindSectionOrOutsider(null, TableHeaders.SUBSECTIONFINDER_TABLE_MODEL, TableHeaders.SUBSECTIONFINDER_TABLE_MODEL2, 55, "අනු අංශය").setVisible(true);
    }//GEN-LAST:event_txtSubSectionActionPerformed

    private void jButton35ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton35ActionPerformed
        SectionedReports(3, "R027_F28_IncomeStatement.jrxml");
    }//GEN-LAST:event_jButton35ActionPerformed

    private void jButton42ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton42ActionPerformed
        customerSectionReports("R051_F28_F15.jrxml");
    }//GEN-LAST:event_jButton42ActionPerformed

    private void jButton43ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton43ActionPerformed
        customerSectionReports("R025_F28_F32_Kuru.jrxml");
    }//GEN-LAST:event_jButton43ActionPerformed

    private void jButton44ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton44ActionPerformed
        customerSectionReports("R026_F28_F33_Kuru.jrxml");
    }//GEN-LAST:event_jButton44ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        ManagerOperationalNavigation.navigateTo(new FinancialYearCompletedMonths(), jPanel7);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton41ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton41ActionPerformed
        AuditReportDetails auditReportDetails=new AuditReportDetails();
        auditReportDetails.setVisible(true);
    }//GEN-LAST:event_jButton41ActionPerformed

    private void jButton26ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton26ActionPerformed
        try {
            screenType=1;
            setCursor(new Cursor(Cursor.WAIT_CURSOR));
            JasperReport jasperReport = JasperCompileManager.compileReport(ReportFileLocator.locateReportFile("R050_F28_IncomeStatement_Sum_Main.jrxml"));
            fillReport(jasperReport);
            setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
        } catch (JRException ex) {
            Logger.getLogger(AuditReportPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton26ActionPerformed

    private void jButton27ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton27ActionPerformed
        try {
            screenType=1;
            setCursor(new Cursor(Cursor.WAIT_CURSOR));
            JasperReport jasperReport = JasperCompileManager.compileReport(ReportFileLocator.locateReportFile("R050_F28_IncomeStatement_Sum_Sub.jrxml"));
            fillReport(jasperReport);
            setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
        } catch (JRException ex) {
            Logger.getLogger(AuditReportPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton27ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton25;
    private javax.swing.JButton jButton26;
    private javax.swing.JButton jButton27;
    private javax.swing.JButton jButton28;
    private javax.swing.JButton jButton29;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton30;
    private javax.swing.JButton jButton31;
    private javax.swing.JButton jButton32;
    private javax.swing.JButton jButton33;
    private javax.swing.JButton jButton34;
    private javax.swing.JButton jButton35;
    private javax.swing.JButton jButton36;
    private javax.swing.JButton jButton37;
    private javax.swing.JButton jButton38;
    private javax.swing.JButton jButton39;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton40;
    private javax.swing.JButton jButton41;
    private javax.swing.JButton jButton42;
    private javax.swing.JButton jButton43;
    private javax.swing.JButton jButton44;
    private javax.swing.JButton jButton45;
    private javax.swing.JButton jButton46;
    private javax.swing.JButton jButton47;
    private javax.swing.JButton jButton56;
    private javax.swing.JButton jButton57;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    static javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JTabbedPane jTabbedPane2;
    private com.toedter.calendar.JDateChooser jdtFrom;
    private com.toedter.calendar.JMonthChooser jdtMonth;
    private com.toedter.calendar.JDateChooser jdtTo;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblTitle1;
    private javax.swing.JLabel lblTitle2;
    private javax.swing.JLabel lblTitle3;
    private javax.swing.JLabel lblTitle4;
    private javax.swing.JLabel lblTitle5;
    private javax.swing.JLabel lblTitle6;
    private javax.swing.JLabel lblTitle7;
    public static org.nbs.components.HiddenIDTextField txtSection;
    public static org.nbs.components.HiddenIDTextField txtSubSection;
    // End of variables declaration//GEN-END:variables
private void mainSectionReports(String path) {
        if (txtSection.getId() != 0) {
            try {
                JasperReport jasperReport = JasperCompileManager.compileReport(ReportFileLocator.locateReportFile(path));
                Map params = new HashMap<>();
                params.put("dFromDate", jdtFrom.getDate());
                params.put("dToDate", jdtTo.getDate());
                params.put("MPCSName", GeneralUserLogin.data.getBranchName());
                params.put("nSectionID", txtSection.getId());
                params.put("nOutSiderMFID", 0);
                params.put("nAct5ID", 0);
                JasperPrint jasperPrint = JasperFillManager.fillReport(jasperReport, params, DB.getConnection());
                JasperViewer.viewReport(jasperPrint, false);
            } catch (JRException | ClassNotFoundException | SQLException ex) {
                ex.printStackTrace();
            }
        } else {
            JOptionPane.showMessageDialog(this, "මූලික අංශය තෝරාගන්න", "", JOptionPane.ERROR_MESSAGE);
        }
    }

    private void customerSectionReports(String path) {
        try {
            JasperReport jasperReport = JasperCompileManager.compileReport(ReportFileLocator.locateReportFile(path));
            Map params = new HashMap<>();
            params.put("dFromDate", jdtFrom.getDate());
            params.put("dToDate", jdtTo.getDate());
            params.put("MPCSName", GeneralUserLogin.data.getBranchName());
            JasperPrint jasperPrint = JasperFillManager.fillReport(jasperReport, params, DB.getConnection());
            JasperViewer.viewReport(jasperPrint, false);
        } catch (JRException | ClassNotFoundException | SQLException ex) {
            ex.printStackTrace();
        }
    }
    
    private void fillReport(JasperReport jasperReport) {
        try {
            Map params = new HashMap();
            params.put("MPCSName", GeneralUserLogin.data.getBranchName());
            params.put("dFromDate", jdtFrom.getDate());
            params.put("dToDate", jdtTo.getDate());
            if (screenType == 2) {
//                params.put("nSectionID", txtSubSection.getId());
//                params.put("nOutSiderMFID", txtOutsider.getId());
//                params.put("nAcct5Cr", txtCrGLAccount.getId());
//                params.put("nAcct5Dr", txtDrGLAccount.getId());
            }else if (screenType == 4) {
                params.put("nMainSectionID", txtSection.getId());
            }else if (screenType == 3) {
                params.put("nSectionID", txtSubSection.getId());
            }
            JasperPrint jasperPrint = JasperFillManager.fillReport(jasperReport, params, DB.getConnection());
            if (GeneralUserLogin.data.isWebHosted()) {
                JasperPrintManager.printReport(jasperPrint, true);
            } else {
                JasperViewer.viewReport(jasperPrint, false);
            }
        } catch (JRException ex) {
            
        } catch (ClassNotFoundException ex) {
            
        } catch (SQLException ex) {
            
        }
    }
    
    void SectionedReports(int TYPE,String report){
        if (txtSubSection.getId() != 0) {
           try {
            screenType=TYPE;
            setCursor(new Cursor(Cursor.WAIT_CURSOR));
            JasperReport jasperReport = JasperCompileManager.compileReport(ReportFileLocator.locateReportFile(report));
            fillReport(jasperReport);
            setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
        } catch (JRException ex) {
            Logger.getLogger(AuditReportPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
        } else {
            JOptionPane.showMessageDialog(this, "මූලික අංශය තෝරාගන්න", "", JOptionPane.ERROR_MESSAGE);
        }
    }
}
