/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.nbs.view.Reports;

import Sources.ReportFileLocator;
import Sources.TableColumnFontChanger;
import com.nbs.connection.DB;
import com.nbs.impl.ServerConnection;
import com.nbs.view.common.GeneralUserLogin;
import com.nbs.view.common.TableHeaders;
import com.nbs.view.common.search.FindAccount5Data;
import com.nbs.view.common.search.FindSectionOrOutsider;
import java.awt.Component;
import java.awt.Cursor;
import java.rmi.RemoteException;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JCheckBox;
import javax.swing.JFrame;
import javax.swing.table.DefaultTableModel;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperPrintManager;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.view.JasperViewer;
import org.nbs.resources.Item;

/**
 *
 * @author mmh
 */
public class ReportsPanel extends javax.swing.JPanel {

    /**
     * Creates new form ReportsPanel
     */
    private DefaultTableModel dtm;
    private int screenType;

    public ReportsPanel() {
        initComponents();
        dtm = (DefaultTableModel) jXTable1.getModel();
        this.components = new Component[]{txtDrGLAccount, txtCrGLAccount, txtOutsider, txtSubSection, jButton1, jButton2, jButton3, jCheckBox1, jCheckBox2, jCheckBox3, txtSection, jCheckBox4, jButton6, jButton7, jCheckBox5,txtMainSection,jButton8,jCheckBox6};
        loadData(1, "0");
        TableColumnFontChanger.setIskolaPotha(jXTable1, 4, 18);
        jdtFrom.setDate(GeneralUserLogin.data.getSystemDate());
        jdtTo.setDate(GeneralUserLogin.data.getSystemDate());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jXTable1 = new org.jdesktop.swingx.JXTable();
        cmbSysCode = new org.nbs.components.HiddenItemComboBox();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jdtFrom = new com.toedter.calendar.JDateChooser();
        jdtTo = new com.toedter.calendar.JDateChooser();
        jLabel4 = new javax.swing.JLabel();
        jCheckBox1 = new javax.swing.JCheckBox();
        jLabel5 = new javax.swing.JLabel();
        jCheckBox2 = new javax.swing.JCheckBox();
        jLabel6 = new javax.swing.JLabel();
        jCheckBox3 = new javax.swing.JCheckBox();
        txtSubSection = new org.nbs.components.HiddenIDTextField();
        txtOutsider = new org.nbs.components.HiddenIDTextField();
        txtDrGLAccount = new org.nbs.components.HiddenIDTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        txtSection = new org.nbs.components.HiddenIDTextField();
        jButton6 = new javax.swing.JButton();
        jCheckBox4 = new javax.swing.JCheckBox();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtCrGLAccount = new org.nbs.components.HiddenIDTextField();
        jButton7 = new javax.swing.JButton();
        jCheckBox5 = new javax.swing.JCheckBox();
        jLabel10 = new javax.swing.JLabel();
        txtMainSection = new org.nbs.components.HiddenIDTextField();
        jButton8 = new javax.swing.JButton();
        jCheckBox6 = new javax.swing.JCheckBox();

        jXTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "nRepID", "cSystemCode", "cCriteriaCode", "nScreenTypeID", "cRportNameSin", "cRportName", "cRportFileName", "cRportFileNameSumm", "cRportFileNameAudit", "bGrp1,bGrp2", "bGrp3", "bGrp4", "bGrp5", "cGrp2", "bRepWindow", "cRepWinPara", "bActive", "nViewOrder", "cScreenTypeCombo"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jXTable1.setRowHeight(28);
        jXTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jXTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jXTable1);

        cmbSysCode.setFont(new java.awt.Font("Iskoola Pota", 0, 18)); // NOI18N
        cmbSysCode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbSysCodeActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Iskoola Pota", 0, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel1.setText("දින පරාසය :");

        jLabel2.setFont(new java.awt.Font("Iskoola Pota", 0, 18)); // NOI18N
        jLabel2.setText("සිට");

        jLabel3.setFont(new java.awt.Font("Iskoola Pota", 0, 18)); // NOI18N
        jLabel3.setText("දක්වා");

        jdtFrom.setDateFormatString("yyyy-MM-dd");
        jdtFrom.setFont(new java.awt.Font("Ubuntu", 1, 16)); // NOI18N

        jdtTo.setDateFormatString("yyyy-MM-dd");
        jdtTo.setFont(new java.awt.Font("Ubuntu", 1, 16)); // NOI18N

        jLabel4.setFont(new java.awt.Font("Iskoola Pota", 0, 18)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel4.setText("අංශය :");

        jCheckBox1.setFont(new java.awt.Font("Iskoola Pota", 0, 18)); // NOI18N
        jCheckBox1.setText("සියලු");
        jCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox1ActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Iskoola Pota", 0, 18)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel5.setText("පාර්ශවය :");

        jCheckBox2.setFont(new java.awt.Font("Iskoola Pota", 0, 18)); // NOI18N
        jCheckBox2.setText("සියලු");
        jCheckBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox2ActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Iskoola Pota", 0, 18)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel6.setText("හර ගිණුම :");

        jCheckBox3.setFont(new java.awt.Font("Iskoola Pota", 0, 18)); // NOI18N
        jCheckBox3.setText("සියලු");
        jCheckBox3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox3ActionPerformed(evt);
            }
        });

        txtSubSection.setFont(new java.awt.Font("AMALEE", 0, 18)); // NOI18N
        txtSubSection.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtSubSectionKeyReleased(evt);
            }
        });

        txtOutsider.setFont(new java.awt.Font("AMALEE", 0, 18)); // NOI18N
        txtOutsider.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtOutsiderKeyReleased(evt);
            }
        });

        txtDrGLAccount.setFont(new java.awt.Font("AMALEE", 0, 18)); // NOI18N
        txtDrGLAccount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDrGLAccountActionPerformed(evt);
            }
        });

        jButton1.setText("....");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("....");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("....");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setFont(new java.awt.Font("Iskoola Pota", 0, 18)); // NOI18N
        jButton4.setText("Exit");

        jButton5.setFont(new java.awt.Font("Iskoola Pota", 0, 18)); // NOI18N
        jButton5.setText("Print");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Iskoola Pota", 0, 18)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel7.setText("මූලික අංශය :");

        txtSection.setFont(new java.awt.Font("AMALEE", 0, 18)); // NOI18N
        txtSection.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtSectionKeyReleased(evt);
            }
        });
        txtSection.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSectionActionPerformed(evt);
            }
        });

        jButton6.setText("....");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jCheckBox4.setFont(new java.awt.Font("Iskoola Pota", 0, 18)); // NOI18N
        jCheckBox4.setText("සියලු");
        jCheckBox4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox4ActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Iskoola Pota", 0, 18)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel9.setText("බැර ගිණුම :");

        txtCrGLAccount.setFont(new java.awt.Font("AMALEE", 0, 18)); // NOI18N

        jButton7.setText("....");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jCheckBox5.setFont(new java.awt.Font("Iskoola Pota", 0, 18)); // NOI18N
        jCheckBox5.setText("සියලු");
        jCheckBox5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox5ActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Iskoola Pota", 0, 18)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel10.setText("ප්‍රධාන අංශය :");

        txtMainSection.setFont(new java.awt.Font("AMALEE", 0, 18)); // NOI18N
        txtMainSection.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtMainSectionKeyReleased(evt);
            }
        });

        jButton8.setText("....");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jCheckBox6.setFont(new java.awt.Font("Iskoola Pota", 0, 18)); // NOI18N
        jCheckBox6.setText("සියලු");
        jCheckBox6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cmbSysCode, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 395, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jdtFrom, javax.swing.GroupLayout.DEFAULT_SIZE, 239, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jdtTo, javax.swing.GroupLayout.DEFAULT_SIZE, 240, Short.MAX_VALUE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtSubSection, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtOutsider, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtDrGLAccount, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtSection, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtCrGLAccount, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtMainSection, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButton2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jCheckBox2, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jCheckBox3, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jCheckBox1, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jCheckBox4, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jCheckBox5, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jCheckBox6, javax.swing.GroupLayout.Alignment.TRAILING)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cmbSysCode, javax.swing.GroupLayout.DEFAULT_SIZE, 46, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jdtFrom, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE)
                            .addComponent(jdtTo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jCheckBox6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txtMainSection, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jCheckBox4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txtSection, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jCheckBox1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txtSubSection, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jCheckBox2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtOutsider, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jCheckBox3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtDrGLAccount, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jCheckBox5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCrGLAccount, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(23, 23, 23)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton4)
                            .addComponent(jButton5)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 451, Short.MAX_VALUE))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void cmbSysCodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbSysCodeActionPerformed
        loadData(2, cmbSysCode.getSelectedItem().getId() + "");
    }//GEN-LAST:event_cmbSysCodeActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        try {
            setCursor(new Cursor(Cursor.WAIT_CURSOR));
//            System.out.println(GeneralUserLogin.data.getReportPath() + String.valueOf(jXTable1.getValueAt(jXTable1.getSelectedRow(), 6)));

//            JasperReport jasperReport = JasperCompileManager.compileReport(GeneralUserLogin.data.getReportPath() + String.valueOf(jXTable1.getValueAt(jXTable1.getSelectedRow(), 6)));
            JasperReport jasperReport = JasperCompileManager.compileReport(ReportFileLocator.locateReportFile(String.valueOf(jXTable1.getValueAt(jXTable1.getSelectedRow(), 6))));
//            System.out.println(String.valueOf(jXTable1.getValueAt(jXTable1.getSelectedRow(), 6)));
//            if (cmbSysCode.getSelectedItem().getId() == 1) {
            fillReoprt(jasperReport);
//            } else if (cmbSysCode.getSelectedItem().getId()) {
//                fillReoprt(jasperReport, 1);
//            }
            setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
        } catch (JRException ex) {
            Logger.getLogger(ReportsPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        java.awt.Container c = this.getParent();
        while (!(c instanceof javax.swing.JFrame) && (c != null)) {
            c = c.getParent();
        }
        JFrame owner = null;
        if (c != null) {
            owner = (javax.swing.JFrame) c;

        }
        new FindSectionOrOutsider(owner, TableHeaders.SUBSECTIONFINDER_TABLE_MODEL, TableHeaders.SUBSECTIONFINDER_TABLE_MODEL2, 36, "අනු අංශය").setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        java.awt.Container c = this.getParent();
        while (!(c instanceof javax.swing.JFrame) && (c != null)) {
            c = c.getParent();
        }
        JFrame owner = null;
        if (c != null) {
            owner = (javax.swing.JFrame) c;

        }
        new FindSectionOrOutsider(owner, TableHeaders.OUTSIDERFINDER_TABLE_MODEL, TableHeaders.OUTSIDERFINDER_TABLE_MODEL2, 37, "පාර්ශවය").setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        java.awt.Container c = this.getParent();
        while (!(c instanceof javax.swing.JFrame) && (c != null)) {
            c = c.getParent();
        }
        JFrame owner = null;
        if (c != null) {
            owner = (javax.swing.JFrame) c;

        }
        new FindAccount5Data(owner, true, 13).setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed
    Component components[];
    private void jXTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jXTable1MouseClicked
        if (jXTable1.getSelectedRow() > -1) {
            if (String.valueOf(jXTable1.getValueAt(jXTable1.getSelectedRow(), 3)).equals("1")) {
                activateComponents(components, false);
                screenType = 1;
            } else if (String.valueOf(jXTable1.getValueAt(jXTable1.getSelectedRow(), 3)).equals("2")) {
                activateComponents(components, true);
                screenType = 2;
            }else if (String.valueOf(jXTable1.getValueAt(jXTable1.getSelectedRow(), 3)).equals("3")) {
                activateComponents(components, false);
                txtSubSection.setEnabled(true);
                jButton1.setEnabled(true);
                jCheckBox1.setEnabled(true);
                screenType = 3;
            }else if (String.valueOf(jXTable1.getValueAt(jXTable1.getSelectedRow(), 3)).equals("4")) {
                activateComponents(components, false);
                txtSection.setEnabled(true);
                jButton6.setEnabled(true);
                jCheckBox4.setEnabled(true);
                screenType = 4;
            }
            jLabel8.setText(String.valueOf(jXTable1.getValueAt(jXTable1.getSelectedRow(), 6)));
        }
    }//GEN-LAST:event_jXTable1MouseClicked

    private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1ActionPerformed
        if (jCheckBox1.isSelected()) {
            txtSubSection.setId(0);
            txtSubSection.setText("");
            txtSubSection.setEnabled(false);
            jButton1.setEnabled(false);
        } else {
            txtSubSection.setEnabled(true);
            jButton1.setEnabled(true);
        }
    }//GEN-LAST:event_jCheckBox1ActionPerformed

    private void jCheckBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox2ActionPerformed
        if (jCheckBox2.isSelected()) {
            txtOutsider.setText("");
            txtOutsider.setId(0);
            txtOutsider.setEnabled(false);
            jButton2.setEnabled(false);
        } else {
            txtOutsider.setEnabled(true);
            jButton2.setEnabled(true);
        }
    }//GEN-LAST:event_jCheckBox2ActionPerformed

    private void jCheckBox3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox3ActionPerformed
        if (jCheckBox3.isSelected()) {
            txtDrGLAccount.setText("");
            txtDrGLAccount.setId(0);
            txtDrGLAccount.setEnabled(false);
            jButton3.setEnabled(false);
        } else {
            txtDrGLAccount.setEnabled(true);
            jButton3.setEnabled(true);
        }
    }//GEN-LAST:event_jCheckBox3ActionPerformed

    private void txtSubSectionKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSubSectionKeyReleased
        if (txtSubSection.getText().trim().isEmpty()) {
            txtSubSection.setId(0);
        }
    }//GEN-LAST:event_txtSubSectionKeyReleased

    private void txtOutsiderKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtOutsiderKeyReleased
        if (txtOutsider.getText().trim().isEmpty()) {
            txtOutsider.setId(0);
        }
    }//GEN-LAST:event_txtOutsiderKeyReleased

    private void txtSectionKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSectionKeyReleased
        if (txtSection.getText().trim().isEmpty()) {
            txtSection.setId(0);
        }
    }//GEN-LAST:event_txtSectionKeyReleased

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        java.awt.Container c = this.getParent();
        while (!(c instanceof javax.swing.JFrame) && (c != null)) {
            c = c.getParent();
        }
        JFrame owner = null;
        if (c != null) {
            owner = (javax.swing.JFrame) c;

        }
        new FindSectionOrOutsider(owner, TableHeaders.SECTIONFINDER_TABLE_MODEL, TableHeaders.SECTIONFINDER_TABLE_MODEL, 51, "මූලික අංශය").setVisible(true);
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jCheckBox4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox4ActionPerformed
        if (jCheckBox4.isSelected()) {
            txtSection.setId(0);
            txtSection.setText("");
            txtSection.setEnabled(false);
            jButton6.setEnabled(false);
        } else {
            txtSection.setEnabled(true);
            jButton6.setEnabled(true);
        }
    }//GEN-LAST:event_jCheckBox4ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        java.awt.Container c = this.getParent();
        while (!(c instanceof javax.swing.JFrame) && (c != null)) {
            c = c.getParent();
        }
        JFrame owner = null;
        if (c != null) {
            owner = (javax.swing.JFrame) c;

        }
        new FindAccount5Data(owner, true, 17).setVisible(true);
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jCheckBox5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox5ActionPerformed
        if (jCheckBox5.isSelected()) {
            txtCrGLAccount.setText("");
            txtCrGLAccount.setId(0);
            txtCrGLAccount.setEnabled(false);
            jButton7.setEnabled(false);
        } else {
            txtCrGLAccount.setEnabled(true);
            jButton7.setEnabled(true);
        }
    }//GEN-LAST:event_jCheckBox5ActionPerformed

    private void txtDrGLAccountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDrGLAccountActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDrGLAccountActionPerformed

    private void txtMainSectionKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtMainSectionKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMainSectionKeyReleased

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jCheckBox6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox6ActionPerformed
        if (jCheckBox6.isSelected()) {
            txtMainSection.setId(0);
            txtMainSection.setText("");
            txtMainSection.setEnabled(false);
            jButton8.setEnabled(false);
        } else {
            txtMainSection.setEnabled(true);
            jButton8.setEnabled(true);
        }
    }//GEN-LAST:event_jCheckBox6ActionPerformed

    private void txtSectionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSectionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSectionActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private org.nbs.components.HiddenItemComboBox cmbSysCode;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JCheckBox jCheckBox3;
    private javax.swing.JCheckBox jCheckBox4;
    private javax.swing.JCheckBox jCheckBox5;
    private javax.swing.JCheckBox jCheckBox6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private org.jdesktop.swingx.JXTable jXTable1;
    private com.toedter.calendar.JDateChooser jdtFrom;
    private com.toedter.calendar.JDateChooser jdtTo;
    public static org.nbs.components.HiddenIDTextField txtCrGLAccount;
    public static org.nbs.components.HiddenIDTextField txtDrGLAccount;
    public static org.nbs.components.HiddenIDTextField txtMainSection;
    public static org.nbs.components.HiddenIDTextField txtOutsider;
    public static org.nbs.components.HiddenIDTextField txtSection;
    public static org.nbs.components.HiddenIDTextField txtSubSection;
    // End of variables declaration//GEN-END:variables

    private void loadData(int type, String code) {
        try {
            List<Object> inputs = new ArrayList<>();
            inputs.add(type);
            inputs.add(code);

            if (type == 1) {
                List<List<Object>> outputs = ServerConnection.getServerConnector().searchMultipleResults(inputs, "ssp_F28_LoadCombo_Reports", 2);
                Vector v = new Vector();
                for (List<Object> output : outputs) {
                    v.add(new Item(Integer.parseInt(String.valueOf(output.get(0))), String.valueOf(output.get(1))));
                }
                cmbSysCode.setModel(new DefaultComboBoxModel<>(v));
            } else if (type == 2) {
                dtm.setRowCount(0);
                List<List<Object>> outputs = ServerConnection.getServerConnector().searchMultipleResults(inputs, "ssp_F28_LoadCombo_Reports", 19);
                for (List<Object> output : outputs) {
                    Vector v = new Vector();
                    for (Object object : output) {
                        v.add(object);
                    }
                    dtm.addRow(v);
                }
            }
            for (int i = 0; i < jXTable1.getColumnCount(); i++) {
                if (i != 4) {
                    jXTable1.getColumn(i).setMaxWidth(0);
                    jXTable1.getColumn(i).setMinWidth(0);
                    jXTable1.getColumn(i).setPreferredWidth(0);
                }
            }
        } catch (SQLException ex) {
            Logger.getLogger(ReportsPanel.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(ReportsPanel.class.getName()).log(Level.SEVERE, null, ex);
        } catch (RemoteException ex) {
            Logger.getLogger(ReportsPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void fillReoprt(JasperReport jasperReport) {
        try {
            jButton5.setCursor(new Cursor(Cursor.WAIT_CURSOR));
            Map params = new HashMap();
            params.put("MPCSName", GeneralUserLogin.data.getBranchName());
            params.put("dFromDate", jdtFrom.getDate());
            params.put("dToDate", jdtTo.getDate());
            if (screenType == 2) {
                params.put("nSectionID", txtSubSection.getId());
                params.put("nOutSiderMFID", txtOutsider.getId());
                params.put("nAcct5Cr", txtCrGLAccount.getId());
                params.put("nAcct5Dr", txtDrGLAccount.getId());
            }else if (screenType == 4) {
                params.put("nMainSectionID", txtSection.getId());
            }else if (screenType == 3) {
                params.put("nSectionID", txtSubSection.getId());
            }
            JasperPrint jasperPrint = JasperFillManager.fillReport(jasperReport, params, DB.getConnection());
            if (GeneralUserLogin.data.isWebHosted()) {
                JasperPrintManager.printReport(jasperPrint, true);
            } else {
                JasperViewer.viewReport(jasperPrint, false);
            }
            jButton5.setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
        } catch (JRException ex) {
            Logger.getLogger(ReportsPanel.class.getName()).log(Level.SEVERE, null, ex);
            jButton5.setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(ReportsPanel.class.getName()).log(Level.SEVERE, null, ex);
            jButton5.setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
        } catch (SQLException ex) {
            Logger.getLogger(ReportsPanel.class.getName()).log(Level.SEVERE, null, ex);
            jButton5.setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
        }
    }

//    private void fillReoprt(JasperReport jasperReport, int type) {
//        if (type == 1) {
//            try {
//                jButton5.setCursor(new Cursor(Cursor.WAIT_CURSOR));
//                Map params = new HashMap();
//                params.put("MPCSName", GeneralUserLogin.data.getBranchName());
//                params.put("dFromDate", jdtFrom.getDate());
//                params.put("dToDate", jdtTo.getDate());
//                if (screenType == 2) {
//                    params.put("nSectionID", txtSubSection.getId());
//                    params.put("nOutSiderMFID", txtOutsider.getId());
//                    params.put("nAct5ID", txtGLAccount.getId());
//                }
//                System.out.println(params);
//                JasperPrint jasperPrint = JasperFillManager.fillReport(jasperReport, params, DB.getConnection());
//                if (GeneralUserLogin.data.isWebHosted()) {
//                    JasperPrintManager.printReport(jasperPrint, true);
//                } else {
//                    JasperViewer.viewReport(jasperPrint, false);
//                }
//                jButton5.setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
//            } catch (JRException ex) {
//                Logger.getLogger(ReportsPanel.class.getName()).log(Level.SEVERE, null, ex);
//                jButton5.setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
//            } catch (ClassNotFoundException ex) {
//                Logger.getLogger(ReportsPanel.class.getName()).log(Level.SEVERE, null, ex);
//                jButton5.setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
//            } catch (SQLException ex) {
//                Logger.getLogger(ReportsPanel.class.getName()).log(Level.SEVERE, null, ex);
//                jButton5.setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
//            }
//        }
//    }
    private void activateComponents(Component[] components, boolean active) {
        for (Component component : components) {
            if (component instanceof JCheckBox) {
                ((JCheckBox) component).setSelected(false);
            }
            component.setEnabled(active);
        }
    }
}
