/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.nbs.view.Member;

/**
 *
 * @author mmh
 */
public class NewCustomer2 extends javax.swing.JPanel {

    /**
     * Creates new form NewCustomer1
     */
    public NewCustomer2() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lableCivil = new javax.swing.JLabel();
        cmbCivilStatus = new org.nbs.components.HiddenItemComboBox();
        lableNational = new javax.swing.JLabel();
        cmbNationality = new org.nbs.components.HiddenItemComboBox();
        lableReligion = new javax.swing.JLabel();
        cmbReligion = new org.nbs.components.HiddenItemComboBox();
        jPanel5 = new javax.swing.JPanel();
        lableAdd1 = new javax.swing.JLabel();
        txtAddress_1 = new javax.swing.JTextField();
        lableAdd2 = new javax.swing.JLabel();
        txtAddress_2 = new javax.swing.JTextField();
        lableAdd3 = new javax.swing.JLabel();
        txtAddress_3 = new javax.swing.JTextField();
        lableAdd4 = new javax.swing.JLabel();
        txtAddress_4 = new javax.swing.JTextField();
        lableTel = new javax.swing.JLabel();
        txtTel_1 = new javax.swing.JTextField();
        lableEmail = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        txtTel_2 = new javax.swing.JTextField();
        jPanel10 = new javax.swing.JPanel();
        lableAdd5 = new javax.swing.JLabel();
        txtRsAddress_1 = new javax.swing.JTextField();
        lableAdd6 = new javax.swing.JLabel();
        txtRsAddress_2 = new javax.swing.JTextField();
        lableAdd7 = new javax.swing.JLabel();
        txtRsAddress_3 = new javax.swing.JTextField();
        lableAdd8 = new javax.swing.JLabel();
        txtRsAddress_4 = new javax.swing.JTextField();
        lableTel1 = new javax.swing.JLabel();
        txtRsTel_1 = new javax.swing.JTextField();
        lableEmail1 = new javax.swing.JLabel();
        txtRsEmail = new javax.swing.JTextField();
        txtRsTel_2 = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        lableMemNo = new javax.swing.JLabel();
        txtMemNo = new javax.swing.JTextField();
        lableDate = new javax.swing.JLabel();
        jdtMemDate = new com.toedter.calendar.JDateChooser();
        lableMemPosition = new javax.swing.JLabel();
        cmbPosition = new org.nbs.components.HiddenItemComboBox();
        lableMemStatus = new javax.swing.JLabel();
        cmbMemStatus = new org.nbs.components.HiddenItemComboBox();
        jLabel1 = new javax.swing.JLabel();
        txtMemFee = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtF10No = new javax.swing.JTextField();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(1082, 495));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "මූලික තොරතුරු", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Iskoola Pota", 0, 18))); // NOI18N

        lableCivil.setFont(new java.awt.Font("Iskoola Pota", 0, 18)); // NOI18N
        lableCivil.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lableCivil.setText("විවාහක / අවිවාහක බව :");

        cmbCivilStatus.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        cmbCivilStatus.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                cmbCivilStatusKeyReleased(evt);
            }
        });

        lableNational.setFont(new java.awt.Font("Iskoola Pota", 0, 18)); // NOI18N
        lableNational.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lableNational.setText("ජාතිය :");

        cmbNationality.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        cmbNationality.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                cmbNationalityKeyReleased(evt);
            }
        });

        lableReligion.setFont(new java.awt.Font("Iskoola Pota", 0, 18)); // NOI18N
        lableReligion.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lableReligion.setText("ආගම :");

        cmbReligion.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lableCivil, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lableNational, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lableReligion, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cmbNationality, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbCivilStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbReligion, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lableCivil, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbCivilStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lableNational, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbNationality, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lableReligion, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbReligion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(36, Short.MAX_VALUE))
        );

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "නිවසේ ලිපිනය", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Iskoola Pota", 0, 18))); // NOI18N

        lableAdd1.setFont(new java.awt.Font("Iskoola Pota", 0, 18)); // NOI18N
        lableAdd1.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lableAdd1.setText("ලිපින පෙල 1 :");

        txtAddress_1.setFont(new java.awt.Font("AMALEE", 1, 14)); // NOI18N
        txtAddress_1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtAddress_1.setPreferredSize(new java.awt.Dimension(2, 25));
        txtAddress_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAddress_1ActionPerformed(evt);
            }
        });
        txtAddress_1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtAddress_1KeyTyped(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtAddress_1KeyReleased(evt);
            }
        });

        lableAdd2.setFont(new java.awt.Font("Iskoola Pota", 0, 18)); // NOI18N
        lableAdd2.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lableAdd2.setText("ලිපින පෙල 2 :");

        txtAddress_2.setFont(new java.awt.Font("AMALEE", 1, 14)); // NOI18N
        txtAddress_2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtAddress_2.setPreferredSize(new java.awt.Dimension(2, 25));
        txtAddress_2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtAddress_2KeyTyped(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtAddress_2KeyReleased(evt);
            }
        });

        lableAdd3.setFont(new java.awt.Font("Iskoola Pota", 0, 18)); // NOI18N
        lableAdd3.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lableAdd3.setText("ලිපින පෙල 3 :");

        txtAddress_3.setFont(new java.awt.Font("AMALEE", 1, 14)); // NOI18N
        txtAddress_3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtAddress_3.setPreferredSize(new java.awt.Dimension(2, 25));
        txtAddress_3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtAddress_3KeyTyped(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtAddress_3KeyReleased(evt);
            }
        });

        lableAdd4.setFont(new java.awt.Font("Iskoola Pota", 0, 18)); // NOI18N
        lableAdd4.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lableAdd4.setText("ලිපින පෙල 4 :");

        txtAddress_4.setFont(new java.awt.Font("AMALEE", 1, 14)); // NOI18N
        txtAddress_4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtAddress_4.setPreferredSize(new java.awt.Dimension(2, 25));
        txtAddress_4.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtAddress_4KeyTyped(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtAddress_4KeyReleased(evt);
            }
        });

        lableTel.setFont(new java.awt.Font("Iskoola Pota", 0, 18)); // NOI18N
        lableTel.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lableTel.setText("දුරකතන අංක 1 සහ 2 :");

        txtTel_1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        txtTel_1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtTel_1.setPreferredSize(new java.awt.Dimension(2, 25));
        txtTel_1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtTel_1KeyReleased(evt);
            }
        });

        lableEmail.setFont(new java.awt.Font("Iskoola Pota", 0, 18)); // NOI18N
        lableEmail.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lableEmail.setText("විද්‍යුත් තැපෑල :");

        txtEmail.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        txtEmail.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtEmail.setPreferredSize(new java.awt.Dimension(2, 25));
        txtEmail.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtEmailKeyReleased(evt);
            }
        });

        txtTel_2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        txtTel_2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtTel_2.setPreferredSize(new java.awt.Dimension(2, 25));
        txtTel_2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtTel_2KeyReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lableAdd1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lableAdd2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lableAdd3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lableAdd4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lableTel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lableEmail, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtAddress_1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtAddress_2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtAddress_3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtAddress_4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(txtTel_1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtTel_2, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txtEmail, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lableAdd1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtAddress_1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lableAdd2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtAddress_2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lableAdd3, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtAddress_3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lableAdd4, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtAddress_4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lableTel, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTel_1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTel_2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lableEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel10.setBackground(java.awt.Color.white);
        jPanel10.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "ව්‍යාපාරික ලිපිනය", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Iskoola Pota", 0, 18))); // NOI18N

        lableAdd5.setFont(new java.awt.Font("Iskoola Pota", 0, 18)); // NOI18N
        lableAdd5.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lableAdd5.setText("ලිපින පෙල 1 :");

        txtRsAddress_1.setFont(new java.awt.Font("AMALEE", 1, 14)); // NOI18N
        txtRsAddress_1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtRsAddress_1.setPreferredSize(new java.awt.Dimension(2, 25));
        txtRsAddress_1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtRsAddress_1KeyTyped(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtRsAddress_1KeyReleased(evt);
            }
        });

        lableAdd6.setFont(new java.awt.Font("Iskoola Pota", 0, 18)); // NOI18N
        lableAdd6.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lableAdd6.setText("ලිපින පෙල 2 :");

        txtRsAddress_2.setFont(new java.awt.Font("AMALEE", 1, 14)); // NOI18N
        txtRsAddress_2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtRsAddress_2.setPreferredSize(new java.awt.Dimension(2, 25));
        txtRsAddress_2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtRsAddress_2KeyTyped(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtRsAddress_2KeyReleased(evt);
            }
        });

        lableAdd7.setFont(new java.awt.Font("Iskoola Pota", 0, 18)); // NOI18N
        lableAdd7.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lableAdd7.setText("ලිපින පෙල 3 :");

        txtRsAddress_3.setFont(new java.awt.Font("AMALEE", 1, 14)); // NOI18N
        txtRsAddress_3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtRsAddress_3.setPreferredSize(new java.awt.Dimension(2, 25));
        txtRsAddress_3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtRsAddress_3KeyTyped(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtRsAddress_3KeyReleased(evt);
            }
        });

        lableAdd8.setFont(new java.awt.Font("Iskoola Pota", 0, 18)); // NOI18N
        lableAdd8.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lableAdd8.setText("ලිපින පෙල 4 :");

        txtRsAddress_4.setFont(new java.awt.Font("AMALEE", 1, 14)); // NOI18N
        txtRsAddress_4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtRsAddress_4.setPreferredSize(new java.awt.Dimension(2, 25));
        txtRsAddress_4.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtRsAddress_4KeyTyped(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtRsAddress_4KeyReleased(evt);
            }
        });

        lableTel1.setFont(new java.awt.Font("Iskoola Pota", 0, 18)); // NOI18N
        lableTel1.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lableTel1.setText("දුරකතන අංක 1 සහ 2 :");

        txtRsTel_1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        txtRsTel_1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtRsTel_1.setPreferredSize(new java.awt.Dimension(2, 25));
        txtRsTel_1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtRsTel_1KeyReleased(evt);
            }
        });

        lableEmail1.setFont(new java.awt.Font("Iskoola Pota", 0, 18)); // NOI18N
        lableEmail1.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lableEmail1.setText("විද්‍යුත් තැපෑල :");

        txtRsEmail.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        txtRsEmail.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtRsEmail.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtRsEmailKeyReleased(evt);
            }
        });

        txtRsTel_2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        txtRsTel_2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtRsTel_2.setPreferredSize(new java.awt.Dimension(2, 25));
        txtRsTel_2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtRsTel_2KeyReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lableTel1, javax.swing.GroupLayout.DEFAULT_SIZE, 167, Short.MAX_VALUE)
                    .addComponent(lableEmail1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addComponent(txtRsTel_1, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtRsTel_2, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txtRsEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 355, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(lableAdd5, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lableAdd6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lableAdd7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lableAdd8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(12, 12, 12)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtRsAddress_4, javax.swing.GroupLayout.DEFAULT_SIZE, 355, Short.MAX_VALUE)
                    .addComponent(txtRsAddress_3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtRsAddress_2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtRsAddress_1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lableAdd5, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtRsAddress_1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lableAdd6, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtRsAddress_2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtRsAddress_3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(lableAdd7, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(lableAdd8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(txtRsAddress_4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtRsTel_1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtRsTel_2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(lableTel1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtRsEmail)
                    .addComponent(lableEmail1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "සාමාජිකත්ව තොරතුරු", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Iskoola Pota", 0, 18))); // NOI18N

        lableMemNo.setFont(new java.awt.Font("Iskoola Pota", 0, 18)); // NOI18N
        lableMemNo.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lableMemNo.setText("සාමාජික අංකය :");

        txtMemNo.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        txtMemNo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtMemNo.setPreferredSize(new java.awt.Dimension(2, 25));

        lableDate.setFont(new java.awt.Font("Iskoola Pota", 0, 18)); // NOI18N
        lableDate.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lableDate.setText("දිනය :");

        jdtMemDate.setDateFormatString("dd-MM-yyyy");
        jdtMemDate.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N

        lableMemPosition.setFont(new java.awt.Font("Iskoola Pota", 0, 18)); // NOI18N
        lableMemPosition.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lableMemPosition.setText("තත්වය :");

        cmbPosition.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N

        lableMemStatus.setFont(new java.awt.Font("Iskoola Pota", 0, 18)); // NOI18N
        lableMemStatus.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lableMemStatus.setText("ආකාරය :");

        cmbMemStatus.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N

        jLabel1.setFont(new java.awt.Font("Iskoola Pota", 0, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setText("සාමාජික ගාස්තුව :");

        txtMemFee.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtMemFee.setPreferredSize(new java.awt.Dimension(2, 25));

        jLabel2.setFont(new java.awt.Font("Iskoola Pota", 0, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("F10 අංකය :");

        txtF10No.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtF10No.setPreferredSize(new java.awt.Dimension(2, 25));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(lableMemNo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 127, Short.MAX_VALUE)
                        .addComponent(lableMemPosition, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lableMemStatus, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(26, 26, 26)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cmbMemStatus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(txtMemNo, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lableDate)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jdtMemDate, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE))
                    .addComponent(cmbPosition, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtMemFee, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtF10No, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lableMemNo, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtMemNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lableDate, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jdtMemDate, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lableMemPosition, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbPosition, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lableMemStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbMemStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtMemFee, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtF10No, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(114, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void cmbCivilStatusKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cmbCivilStatusKeyReleased

    }//GEN-LAST:event_cmbCivilStatusKeyReleased

    private void cmbNationalityKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cmbNationalityKeyReleased

    }//GEN-LAST:event_cmbNationalityKeyReleased

    private void txtAddress_1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtAddress_1KeyReleased

    }//GEN-LAST:event_txtAddress_1KeyReleased

    private void txtAddress_1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtAddress_1KeyTyped

    }//GEN-LAST:event_txtAddress_1KeyTyped

    private void txtAddress_2KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtAddress_2KeyReleased

    }//GEN-LAST:event_txtAddress_2KeyReleased

    private void txtAddress_2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtAddress_2KeyTyped

    }//GEN-LAST:event_txtAddress_2KeyTyped

    private void txtAddress_3KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtAddress_3KeyReleased

    }//GEN-LAST:event_txtAddress_3KeyReleased

    private void txtAddress_3KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtAddress_3KeyTyped

    }//GEN-LAST:event_txtAddress_3KeyTyped

    private void txtAddress_4KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtAddress_4KeyReleased

    }//GEN-LAST:event_txtAddress_4KeyReleased

    private void txtAddress_4KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtAddress_4KeyTyped

    }//GEN-LAST:event_txtAddress_4KeyTyped

    private void txtTel_1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTel_1KeyReleased

    }//GEN-LAST:event_txtTel_1KeyReleased

    private void txtEmailKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtEmailKeyReleased

    }//GEN-LAST:event_txtEmailKeyReleased

    private void txtTel_2KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTel_2KeyReleased

    }//GEN-LAST:event_txtTel_2KeyReleased

    private void txtRsAddress_1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtRsAddress_1KeyReleased
        if (evt.getKeyCode() == 10) {
            txtRsAddress_2.grabFocus();
        }
    }//GEN-LAST:event_txtRsAddress_1KeyReleased

    private void txtRsAddress_1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtRsAddress_1KeyTyped

    }//GEN-LAST:event_txtRsAddress_1KeyTyped

    private void txtRsAddress_2KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtRsAddress_2KeyReleased
        if (evt.getKeyCode() == 10) {
            txtRsAddress_3.grabFocus();
        }
    }//GEN-LAST:event_txtRsAddress_2KeyReleased

    private void txtRsAddress_2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtRsAddress_2KeyTyped

    }//GEN-LAST:event_txtRsAddress_2KeyTyped

    private void txtRsAddress_3KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtRsAddress_3KeyReleased
        if (evt.getKeyCode() == 10) {
            txtRsAddress_4.grabFocus();
        }
    }//GEN-LAST:event_txtRsAddress_3KeyReleased

    private void txtRsAddress_3KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtRsAddress_3KeyTyped

    }//GEN-LAST:event_txtRsAddress_3KeyTyped

    private void txtRsAddress_4KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtRsAddress_4KeyReleased
        if (evt.getKeyCode() == 10) {
            txtRsTel_1.grabFocus();
        }
    }//GEN-LAST:event_txtRsAddress_4KeyReleased

    private void txtRsAddress_4KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtRsAddress_4KeyTyped

    }//GEN-LAST:event_txtRsAddress_4KeyTyped

    private void txtRsTel_1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtRsTel_1KeyReleased
        if (evt.getKeyCode() == 10) {
            txtRsTel_2.grabFocus();
        }
    }//GEN-LAST:event_txtRsTel_1KeyReleased

    private void txtRsEmailKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtRsEmailKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRsEmailKeyReleased

    private void txtRsTel_2KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtRsTel_2KeyReleased
        if (evt.getKeyCode() == 10) {
            txtRsEmail.grabFocus();
        }
    }//GEN-LAST:event_txtRsTel_2KeyReleased

    private void txtAddress_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAddress_1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAddress_1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    protected static org.nbs.components.HiddenItemComboBox cmbCivilStatus;
    protected static org.nbs.components.HiddenItemComboBox cmbMemStatus;
    protected static org.nbs.components.HiddenItemComboBox cmbNationality;
    protected static org.nbs.components.HiddenItemComboBox cmbPosition;
    protected static org.nbs.components.HiddenItemComboBox cmbReligion;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    protected static javax.swing.JPanel jPanel1;
    protected static javax.swing.JPanel jPanel10;
    protected static javax.swing.JPanel jPanel2;
    protected static javax.swing.JPanel jPanel5;
    protected static com.toedter.calendar.JDateChooser jdtMemDate;
    protected static javax.swing.JLabel lableAdd1;
    protected static javax.swing.JLabel lableAdd2;
    protected static javax.swing.JLabel lableAdd3;
    protected static javax.swing.JLabel lableAdd4;
    protected static javax.swing.JLabel lableAdd5;
    protected static javax.swing.JLabel lableAdd6;
    protected static javax.swing.JLabel lableAdd7;
    protected static javax.swing.JLabel lableAdd8;
    protected static javax.swing.JLabel lableCivil;
    protected static javax.swing.JLabel lableDate;
    protected static javax.swing.JLabel lableEmail;
    protected static javax.swing.JLabel lableEmail1;
    protected static javax.swing.JLabel lableMemNo;
    protected static javax.swing.JLabel lableMemPosition;
    protected static javax.swing.JLabel lableMemStatus;
    protected static javax.swing.JLabel lableNational;
    protected static javax.swing.JLabel lableReligion;
    protected static javax.swing.JLabel lableTel;
    protected static javax.swing.JLabel lableTel1;
    protected static javax.swing.JTextField txtAddress_1;
    protected static javax.swing.JTextField txtAddress_2;
    protected static javax.swing.JTextField txtAddress_3;
    protected static javax.swing.JTextField txtAddress_4;
    protected static javax.swing.JTextField txtEmail;
    public static javax.swing.JTextField txtF10No;
    public static javax.swing.JTextField txtMemFee;
    protected static javax.swing.JTextField txtMemNo;
    protected static javax.swing.JTextField txtRsAddress_1;
    protected static javax.swing.JTextField txtRsAddress_2;
    protected static javax.swing.JTextField txtRsAddress_3;
    protected static javax.swing.JTextField txtRsAddress_4;
    protected static javax.swing.JTextField txtRsEmail;
    protected static javax.swing.JTextField txtRsTel_1;
    protected static javax.swing.JTextField txtRsTel_2;
    protected static javax.swing.JTextField txtTel_1;
    protected static javax.swing.JTextField txtTel_2;
    // End of variables declaration//GEN-END:variables

    
}
