/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

 /*
 * frm_Act_Budget.java
 *needed
 * Created on Jan 6, 2014, 8:11:32 AM
 */
package com.nbs.view.manager;

import Resources.SystemParameterList;
import Sources.TableColumnFontChanger;
import Sources.TableColumnRightAlign;
import com.nbs.impl.ServerConnection;
import com.nbs.view.common.FormatConstants;
import com.nbs.view.common.GeneralUserLogin;
import com.nbs.view.common.TableHeaders;
import com.nbs.view.common.search.FindSectionOrOutsider;
import java.awt.Color;
import java.awt.Component;
import java.awt.Font;
import java.rmi.RemoteException;
import java.sql.SQLException;
import java.text.ParseException;
import java.util.ArrayList;
import java.util.List;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;
import org.nbs.resources.Item;

/**
 *
 * @author mmh
 */
public class ClosingStockNewFormat extends javax.swing.JDialog {

    private DefaultTableModel dtm;
    private int month = 0;

    /**
     * Creates new form frm_Act_Budget
     */
    public ClosingStockNewFormat(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        dtm = (DefaultTableModel) dataTable.getModel();
        setTitle("Server on " + GeneralUserLogin.data.getIP());
        loadFinancialYear();
        TableColumnRightAlign.alignMany(dataTable, new int[]{1, 2});
        TableColumnFontChanger.setAmalee(dataTable, 0);
        month = jMonthChooser1.getMonth() + 1;
        viewDT(cmbFinancialYear.getSelectedItem().getId(), month);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        dataTable = new org.jdesktop.swingx.JXTable();
        jPanel4 = new javax.swing.JPanel();
        txtSubSection = new org.nbs.components.HiddenIDTextField();
        txtBuying = new javax.swing.JTextField();
        txtSelling = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        cmbFinancialYear = new org.nbs.components.HiddenItemComboBox();
        jLabel3 = new javax.swing.JLabel();
        jMonthChooser1 = new com.toedter.calendar.JMonthChooser();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(java.awt.Color.white);

        jPanel2.setBackground(new java.awt.Color(0, 88, 136));
        jPanel2.setBorder(null);

        jLabel1.setFont(new java.awt.Font("Iskoola Pota", 1, 25)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(254, 254, 254));
        jLabel1.setText("මාසික තොග ගැලපීම");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 431, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 57, Short.MAX_VALUE)
        );

        jPanel3.setBackground(java.awt.Color.white);

        dataTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Descri", "Buying Price", "Selling Price", "SubsectionID", "RecID"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        dataTable.getTableHeader().setReorderingAllowed(false);
        dataTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dataTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(dataTable);
        if (dataTable.getColumnModel().getColumnCount() > 0) {
            dataTable.getColumnModel().getColumn(0).setMinWidth(700);
            dataTable.getColumnModel().getColumn(0).setPreferredWidth(700);
            dataTable.getColumnModel().getColumn(0).setMaxWidth(700);
            dataTable.getColumnModel().getColumn(1).setMinWidth(325);
            dataTable.getColumnModel().getColumn(1).setPreferredWidth(325);
            dataTable.getColumnModel().getColumn(1).setMaxWidth(325);
            dataTable.getColumnModel().getColumn(2).setMinWidth(325);
            dataTable.getColumnModel().getColumn(2).setPreferredWidth(325);
            dataTable.getColumnModel().getColumn(2).setMaxWidth(325);
            dataTable.getColumnModel().getColumn(3).setMinWidth(0);
            dataTable.getColumnModel().getColumn(3).setPreferredWidth(0);
            dataTable.getColumnModel().getColumn(3).setMaxWidth(0);
            dataTable.getColumnModel().getColumn(4).setMinWidth(0);
            dataTable.getColumnModel().getColumn(4).setPreferredWidth(0);
            dataTable.getColumnModel().getColumn(4).setMaxWidth(0);
        }

        jPanel4.setBackground(java.awt.Color.white);
        jPanel4.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 2, 1, 1));

        txtSubSection.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtSubSection.setFont(new java.awt.Font("AMALEE", 0, 18)); // NOI18N
        txtSubSection.setMaximumSize(new java.awt.Dimension(700, 28));
        txtSubSection.setMinimumSize(new java.awt.Dimension(700, 28));
        txtSubSection.setPreferredSize(new java.awt.Dimension(700, 28));
        txtSubSection.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtSubSectionKeyReleased(evt);
            }
        });
        txtSubSection.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSubSectionActionPerformed(evt);
            }
        });
        txtSubSection.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtSubSectionFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtSubSectionFocusLost(evt);
            }
        });

        txtBuying.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        txtBuying.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        txtBuying.setText("0.00");
        txtBuying.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtBuying.setMaximumSize(new java.awt.Dimension(325, 25));
        txtBuying.setMinimumSize(new java.awt.Dimension(325, 25));
        txtBuying.setPreferredSize(new java.awt.Dimension(325, 25));
        txtBuying.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtBuyingFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtBuyingFocusLost(evt);
            }
        });
        txtBuying.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtBuyingMouseClicked(evt);
            }
        });
        txtBuying.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBuyingActionPerformed(evt);
            }
        });
        txtBuying.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtBuyingKeyReleased(evt);
            }
        });

        txtSelling.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        txtSelling.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        txtSelling.setText("0.00");
        txtSelling.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtSelling.setMaximumSize(new java.awt.Dimension(325, 25));
        txtSelling.setMinimumSize(new java.awt.Dimension(325, 25));
        txtSelling.setPreferredSize(new java.awt.Dimension(325, 25));
        txtSelling.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtSellingFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtSellingFocusLost(evt);
            }
        });
        txtSelling.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtSellingMouseClicked(evt);
            }
        });
        txtSelling.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSellingActionPerformed(evt);
            }
        });
        txtSelling.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtSellingKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(txtSubSection, javax.swing.GroupLayout.PREFERRED_SIZE, 700, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(txtBuying, javax.swing.GroupLayout.PREFERRED_SIZE, 325, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(txtSelling, javax.swing.GroupLayout.PREFERRED_SIZE, 325, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txtSubSection, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(txtBuying, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(txtSelling, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        jButton2.setText("Clear");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(1153, 1153, 1153)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 507, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel5.setBackground(java.awt.Color.white);
        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(java.awt.Color.blue));

        jLabel2.setFont(new java.awt.Font("Iskoola Pota", 0, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("මුදල් වර්ෂය :");

        cmbFinancialYear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbFinancialYearActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Iskoola Pota", 0, 18)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("මාසය :");

        jMonthChooser1.setMinimumSize(new java.awt.Dimension(200, 28));
        jMonthChooser1.setPreferredSize(new java.awt.Dimension(200, 27));
        jMonthChooser1.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jMonthChooser1PropertyChange(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cmbFinancialYear, javax.swing.GroupLayout.PREFERRED_SIZE, 356, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jMonthChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(453, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cmbFinancialYear, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jMonthChooser1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void dataTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dataTableMouseClicked
    if (dataTable.getSelectedRow() > -1) {
        int selectedRow = dataTable.getSelectedRow();
        JTextField fields[] = {txtSubSection, txtBuying, txtSelling};
        for (int i = 0; i < dataTable.getColumnCount(); i++) {
            switch (i) {
                case 0:
                    txtSubSection.setText(String.valueOf(dataTable.getValueAt(selectedRow, 0)));
                case 1:
                    txtBuying.setText(String.valueOf(dataTable.getValueAt(selectedRow, 1)));
                case 2:
                    txtSelling.setText(String.valueOf(dataTable.getValueAt(selectedRow, 2)));
                case 3:
                    txtSubSection.setId(Integer.parseInt(String.valueOf(dataTable.getValueAt(selectedRow, 3))));
                case 4:
                    dtid = Integer.parseInt(String.valueOf(dataTable.getValueAt(selectedRow, 4)));
                    break;
                default:
                    break;
            }
        }

    }
}//GEN-LAST:event_dataTableMouseClicked

private void txtBuyingKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBuyingKeyReleased

}//GEN-LAST:event_txtBuyingKeyReleased

private void txtBuyingMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtBuyingMouseClicked

}//GEN-LAST:event_txtBuyingMouseClicked

private void txtSellingMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtSellingMouseClicked

}//GEN-LAST:event_txtSellingMouseClicked

private void txtSellingKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSellingKeyReleased

}//GEN-LAST:event_txtSellingKeyReleased

private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

}//GEN-LAST:event_jButton2ActionPerformed

    private void txtSubSectionKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSubSectionKeyReleased

    }//GEN-LAST:event_txtSubSectionKeyReleased

    private void txtSubSectionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSubSectionActionPerformed
        new FindSectionOrOutsider(this, true, TableHeaders.SUBSECTIONFINDER_TABLE_MODEL, TableHeaders.SUBSECTIONFINDER_TABLE_MODEL2, 64, "අංශය").setVisible(true);
    }//GEN-LAST:event_txtSubSectionActionPerformed

    private void txtBuyingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBuyingActionPerformed
        txtSelling.grabFocus();
    }//GEN-LAST:event_txtBuyingActionPerformed

    private void txtSellingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSellingActionPerformed
        JTextField fields[] = {txtBuying, txtSelling};
        for (JTextField field : fields) {
            if (field.getText().trim().isEmpty()) {
                JOptionPane.showMessageDialog(this, "යම් මාසයක දත්ත ඇතුලත් වී නොමැත. කරුණාකර නැවත පිරික්සන්න.", "කරුණාකර නැවත පිරික්සන්න.", JOptionPane.ERROR_MESSAGE);
                return;

            }
        }

        saveClosingStock();
        month = jMonthChooser1.getMonth()+1;
        viewDT(cmbFinancialYear.getSelectedItem().getId(), month);
        initTxtFields();
        txtSubSection.grabFocus();
        dtid = 0;
    }//GEN-LAST:event_txtSellingActionPerformed

    private void cmbFinancialYearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbFinancialYearActionPerformed
        month = jMonthChooser1.getMonth()+1;
        viewDT(cmbFinancialYear.getSelectedItem().getId(), month);
    }//GEN-LAST:event_cmbFinancialYearActionPerformed

    private void txtSubSectionFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtSubSectionFocusGained
        focusGained(evt.getComponent());
    }//GEN-LAST:event_txtSubSectionFocusGained

    private void txtBuyingFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtBuyingFocusGained
        focusGained(evt.getComponent());
    }//GEN-LAST:event_txtBuyingFocusGained

    private void txtSellingFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtSellingFocusGained
        focusGained(evt.getComponent());
    }//GEN-LAST:event_txtSellingFocusGained

    private void txtSubSectionFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtSubSectionFocusLost
        focusLost(evt.getComponent());
    }//GEN-LAST:event_txtSubSectionFocusLost

    private void txtBuyingFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtBuyingFocusLost
        focusLost(evt.getComponent());
    }//GEN-LAST:event_txtBuyingFocusLost

    private void txtSellingFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtSellingFocusLost
        focusLost(evt.getComponent());
    }//GEN-LAST:event_txtSellingFocusLost

    private void jMonthChooser1PropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jMonthChooser1PropertyChange
        String propertyName = evt.getPropertyName();
        if ("month".equals(propertyName)) {
            month = jMonthChooser1.getMonth()+1;
            viewDT(cmbFinancialYear.getSelectedItem().getId(), month);
        }
    }//GEN-LAST:event_jMonthChooser1PropertyChange

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ClosingStockNewFormat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ClosingStockNewFormat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ClosingStockNewFormat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ClosingStockNewFormat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                ClosingStockNewFormat dialog = new ClosingStockNewFormat(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {

                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private org.nbs.components.HiddenItemComboBox cmbFinancialYear;
    private org.jdesktop.swingx.JXTable dataTable;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private com.toedter.calendar.JMonthChooser jMonthChooser1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    public static javax.swing.JTextField txtBuying;
    private javax.swing.JTextField txtSelling;
    public static org.nbs.components.HiddenIDTextField txtSubSection;
    // End of variables declaration//GEN-END:variables

    private void viewPanel() {
//        if (jRadioButton1.isSelected()) {
//            jPanel5.setVisible(false);
//        }else if (jRadioButton2.isSelected()) {
//            jPanel3.setVisible(false);
//        }
    }

    private void loadFinancialYear() {
        try {
            List<Object> inputs = new ArrayList<>();
            inputs.add(7);
            inputs.add(null);
            inputs.add(null);
            inputs.add(0);
            inputs.add(0);
            List<List<Object>> outputs = ServerConnection.getServerConnector().searchMultipleResults(inputs, "ssp_F28_LoadCombo_ViewStock", 2);
            Vector v = new Vector();
            for (List<Object> output : outputs) {

                v.add(new Item(Integer.parseInt(String.valueOf(output.get(0))), String.valueOf(output.get(1))));

            }
            cmbFinancialYear.setModel(new DefaultComboBoxModel<>(v));
        } catch (SQLException ex) {
            Logger.getLogger(ClosingStockNewFormat.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(ClosingStockNewFormat.class.getName()).log(Level.SEVERE, null, ex);
        } catch (RemoteException ex) {
            Logger.getLogger(ClosingStockNewFormat.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    private int dtid = 0;

    private void saveClosingStock() {
        try {
            List<Object> inputs = new ArrayList<>();
            inputs.add(dtid);
            inputs.add(cmbFinancialYear.getSelectedItem().getId());
            inputs.add(txtSubSection.getId());
            int monthSelectedBuying = jMonthChooser1.getMonth();
            monthSelectedBuying *= 2;
            int monthSelectedSelling = monthSelectedBuying + 1;
            System.out.println(monthSelectedBuying+" and "+monthSelectedSelling);
            for (int i = 0; i < 24; i++) {
                if (monthSelectedBuying == i) {
                    inputs.add(txtBuying.getText());
                } else if (monthSelectedSelling == i) {
                    inputs.add(txtSelling.getText());
                } else {
                    inputs.add(0.00);
                }
            }
            inputs.add(GeneralUserLogin.data.getUsername());
            ServerConnection.getServerConnector().insertData(inputs, "ssp_F28_Insert_ClosingStockNew", 0);
        } catch (RemoteException ex) {
            Logger.getLogger(ClosingStockNewFormat.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(ClosingStockNewFormat.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(ClosingStockNewFormat.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void viewDT(int finYearID, int month) {
        try {
            dtm.setRowCount(0);
            List<Object> inputs = new ArrayList<>();
            inputs.add(finYearID);
            inputs.add(month);
            System.out.println(inputs+"fin");
            List<List<Object>> outputs = ServerConnection.getServerConnector().searchMultipleResults(inputs, "ssp_F28_LoadCombo_ClosingStockNewFormat", 5);
            System.out.println(outputs);
            for (List<Object> output : outputs) {
                Vector v = new Vector();
                for (Object object : output) {
                    v.add(object);
                }
                System.out.println(v+" Vector");
                dtm.addRow(v);
            }
        } catch (RemoteException ex) {
            Logger.getLogger(ClosingStockNewFormat.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(ClosingStockNewFormat.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(ClosingStockNewFormat.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void initTxtFields() {
        JTextField fields[] = {txtBuying, txtSelling};
        for (JTextField field : fields) {
            field.setText("0.00");
        }
        txtSubSection.setText("");
        txtSubSection.setId(0);
    }

    private void focusGained(Component component) {
        component.setBackground(Color.YELLOW);
        ((JTextField) component).selectAll();
    }

    private void focusLost(Component component) {
        component.setBackground(Color.WHITE);
        ((JTextField) component).select(0, 0);
    }
}
