/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.nbs.view.manager;

import com.nbs.view.Reports.ReportsPanel;
import Sources.GLCodes;
import Sources.User;
import com.nbs.constants.AccessLevels;
import com.nbs.view.common.EmptyPanel;
import static com.nbs.view.common.GeneralUserLogin.data;
import com.nbs.view.common.TableHeaders;
import com.nbs.view.common.search.FindAccount5Data;
import com.nbs.view.common.search.FindSectionOrOutsider;
import java.awt.Font;
import java.awt.Toolkit;
import javax.swing.JFrame;
import javax.swing.event.TreeSelectionEvent;
import javax.swing.event.TreeSelectionListener;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.DefaultTreeModel;

/**
 *
 * @author ASUS
 */
public class ManagerOperational extends javax.swing.JFrame {

    private int acessLevel;
    public static int node;
    User user;

    /**
     * Creates new form temp
     */
    //public static 
    public ManagerOperational() {
        //  setSize(Toolkit.getDefaultToolkit().getScreenSize());
        initComponents();
        setTitle("Server on " + data.getIP());
//        this.setExtendedState(this.getExtendedState() | JFrame.MAXIMIZED_BOTH);
        defTree();
        DefaultMutableTreeNode selectedNode = (DefaultMutableTreeNode) jTree1.getLastSelectedPathComponent();
        if (selectedNode != null) {
            treeSet();
        }
        setExtendedState(JFrame.MAXIMIZED_BOTH);
        statusBranch.setText(data.getBranchID() + "-" + data.getBranchName());

    }

    public ManagerOperational(int accessLevel) {
        this.acessLevel = accessLevel;
        initComponents();
        setTitle("Server on " + data.getIP());
        setSize(Toolkit.getDefaultToolkit().getScreenSize());
        defTree();
//        treeSet();
        setExtendedState(JFrame.MAXIMIZED_BOTH);
        Title.setFont(new Font("Tahoma", Font.BOLD, 24));
    }

    public ManagerOperational(int accessLevel, User user) {
        this.acessLevel = accessLevel;
        initComponents();
        this.user = user;
        setTitle("Server on " + data.getIP());
        setSize(Toolkit.getDefaultToolkit().getScreenSize());
        defTree();
        treeSet();
        setExtendedState(JFrame.MAXIMIZED_BOTH);
        Title.setFont(new Font("Tahoma", Font.BOLD, 24));
    }

    public ManagerOperational(String title, int acessLevel) {
        this(acessLevel);
        treeSet();
        if (acessLevel == AccessLevels.MANAGER) {
            Title.setFont(new Font("Tahoma", Font.BOLD, 24));
        } else {
            Title.setFont(new Font("AMALEE", Font.BOLD, 24));
        }
        Title.setText(title.replaceAll("<html>", "").replaceAll("</html>", "").replaceAll("<br>", "").replaceAll("<center>", "").replaceAll("</center>", ""));
    }

    public ManagerOperational(String title, int acessLevel, User user) {
        this(title, acessLevel);
        this.user = user;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        Title = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTree1 = new javax.swing.JTree();
        jPanel7 = new javax.swing.JPanel();
        jXStatusBar1 = new org.jdesktop.swingx.JXStatusBar();
        online = new javax.swing.JLabel();
        statusMFID2 = new javax.swing.JLabel();
        statusGLID2 = new javax.swing.JLabel();
        clockLabel3 = new org.nbs.components.ClockLabel("yyyy-MM-dd hh:mm:ss a");
        statusBranch = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(135, 206, 250));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.setForeground(new java.awt.Color(255, 0, 0));

        Title.setFont(new java.awt.Font("AMALEE", 1, 24)); // NOI18N
        Title.setText("Manager");

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/manager-icon.gif"))); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(Title, javax.swing.GroupLayout.PREFERRED_SIZE, 326, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(Title, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel5.setBackground(new java.awt.Color(204, 255, 255));

        jScrollPane1.setBorder(null);

        jTree1.setBorder(null);
        jTree1.setFont(new java.awt.Font("Iskoola Pota", 0, 14)); // NOI18N
        javax.swing.tree.DefaultMutableTreeNode treeNode1 = new javax.swing.tree.DefaultMutableTreeNode("root");
        jTree1.setModel(new javax.swing.tree.DefaultTreeModel(treeNode1));
        jTree1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jTree1MouseReleased(evt);
            }
        });
        jScrollPane1.setViewportView(jTree1);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
        );

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));
        jPanel7.setLayout(new java.awt.BorderLayout());

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(1, 1, 1)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, 569, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())))
        );

        jXStatusBar1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        online.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        online.setForeground(new java.awt.Color(253, 16, 4));
        online.setText("ONLINE");

        statusMFID2.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        statusMFID2.setForeground(new java.awt.Color(253, 16, 4));

        statusGLID2.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        statusGLID2.setForeground(new java.awt.Color(253, 16, 4));

        clockLabel3.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        clockLabel3.setForeground(new java.awt.Color(11, 35, 121));

        statusBranch.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        statusBranch.setForeground(new java.awt.Color(253, 16, 4));

        javax.swing.GroupLayout jXStatusBar1Layout = new javax.swing.GroupLayout(jXStatusBar1);
        jXStatusBar1.setLayout(jXStatusBar1Layout);
        jXStatusBar1Layout.setHorizontalGroup(
            jXStatusBar1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jXStatusBar1Layout.createSequentialGroup()
                .addComponent(online)
                .addGap(11, 11, 11)
                .addComponent(statusMFID2, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(statusGLID2, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(statusBranch, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 591, Short.MAX_VALUE)
                .addComponent(clockLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jXStatusBar1Layout.setVerticalGroup(
            jXStatusBar1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(clockLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(online, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(statusMFID2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(statusGLID2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(statusBranch, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jXStatusBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jXStatusBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTree1MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTree1MouseReleased
        //jTree1.getSel
    }//GEN-LAST:event_jTree1MouseReleased

    /**
     *
     */
    static ManagerOperational managerOperational;

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ManagerOperational.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ManagerOperational.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ManagerOperational.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ManagerOperational.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>


        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                managerOperational = new ManagerOperational();
                managerOperational.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Title;
    private org.nbs.components.ClockLabel clockLabel3;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel5;
    public static javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    static javax.swing.JTree jTree1;
    private org.jdesktop.swingx.JXStatusBar jXStatusBar1;
    private javax.swing.JLabel online;
    private javax.swing.JLabel statusBranch;
    public static javax.swing.JLabel statusGLID2;
    private javax.swing.JLabel statusMFID2;
    // End of variables declaration//GEN-END:variables
    private void treeSet() {
        jTree1.getSelectionModel().addTreeSelectionListener(new TreeSelectionListener() {
            @Override
            public void valueChanged(TreeSelectionEvent tse) {
                DefaultMutableTreeNode selectedNode = (DefaultMutableTreeNode) jTree1.getLastSelectedPathComponent();

                String code = selectedNode.getUserObject().toString().substring(0, 5);
                String header = selectedNode.getUserObject().toString().substring(6);
                if (null != code) {
                    System.out.println(code);
                    switch (code) {
                        case "01-01":
                            ManagerOperationalNavigation.navigateTo(code, new CommonJurnalForm(header, JurnalTableHeaders._01_01, code, user), jPanel7, Nodes.DAILYCASH);
                            setButtonStatus();
                            statusGLID2.setText(GLCodes.AB16BUYINGS + "");
                            break;
                        case "01-02":
                            ManagerOperationalNavigation.navigateTo(code, new CommonJurnalForm(header, JurnalTableHeaders._01_02, code, user), jPanel7, Nodes.DAILYCASH);
                            setButtonStatus();
                            statusGLID2.setText(GLCodes.AB16CASHPURCHASE + "");
                            break;
                        case "01-03":
                            ManagerOperationalNavigation.navigateTo(code, new CommonJurnalForm(header, JurnalTableHeaders._01_03, code, user), jPanel7, Nodes.DAILYCASH);
                            setButtonStatus();
                            statusGLID2.setText(GLCodes.AB16PURCHASEDADVANCE + "");
                            break;
                        case "01-04":
                            ManagerOperationalNavigation.navigateTo(code, new CommonJurnalForm(header, JurnalTableHeaders._01_04, code, user), jPanel7, Nodes.DAILYCASH);
                            setButtonStatus();
                            statusGLID2.setText(GLCodes.AB16STORESRECEIVINGS + "");
                            break;
                        case "01-05":
                            if (data.isB9old()) {
                                ManagerOperationalNavigation.navigateTo(code, new CommonJurnalForm(header, JurnalTableHeaders._01_05, code, user), jPanel7, Nodes.DAILYCASH);
                            } else {
                                ManagerOperationalNavigation.navigateTo(code, new CommonJurnalForm(header, JurnalTableHeaders._01_05_NEW, code, user), jPanel7, Nodes.DAILYCASH);
                            }

                            setButtonStatus();
                            statusGLID2.setText(GLCodes.B9 + "");
                            break;
                        case "01-06":
                            ManagerOperationalNavigation.navigateTo(code, new CommonJurnalForm(header, JurnalTableHeaders._01_06, code, user), jPanel7, Nodes.DAILYCASH);
                            setButtonStatus();
                            statusGLID2.setText(GLCodes.F17 + "");
                            break;
                        case "01-07":
                            ManagerOperationalNavigation.navigateTo(code, new CommonJurnalForm(header, JurnalTableHeaders._01_07, code, user), jPanel7, Nodes.DAILYCASH);
                            setButtonStatus();
                            statusGLID2.setText(GLCodes.F18 + "");
                            break;
                        case "01-08":
                            ManagerOperationalNavigation.navigateTo(code, new CommonJurnalForm(header, JurnalTableHeaders._01_08, code, user), jPanel7, Nodes.DAILYCASH);
                            setButtonStatus();
                            statusGLID2.setText(GLCodes.F19 + "");
                            break;
                        case "01-09":
                            ManagerOperationalNavigation.navigateTo(code, new CommonJurnalForm(header, JurnalTableHeaders._05, GLCodes.C9SALE, code, user), jPanel7, GLCodes.C9SALE);
                            setButtonStatus();
                            statusGLID2.setText(GLCodes.C9SALE + "");
                            break;
                        case "01-10":
                            EmptyPanel emptyPanel1 = new EmptyPanel();
                            ManagerOperationalNavigation.navigateTo(emptyPanel1, jPanel7);
                            setButtonStatus();
//                            new ClosingStock(ManagerOperational.this, true).setVisible(true);
                            new ClosingStockNewFormat(ManagerOperational.this, true).setVisible(true);
                            break;
                        case "01-11":
                            ManagerOperationalNavigation.navigateTo(code, new CommonJurnalForm(header, JurnalTableHeaders._01_11, code, user), jPanel7, Nodes.DAILYCASH);
                            setButtonStatus();
                            break;
                        case "02-01":
                            ManagerOperationalNavigation.navigateTo(code, new CommonJurnalForm(header, JurnalTableHeaders._02_01, code, ManagerOperational.this.user), jPanel7, Nodes.DAILYCASH);
                            setButtonStatus();
                            statusGLID2.setText(GLCodes.CASHRECEIVINGS + "");
                            break;

                        case "02-02":
                            ManagerOperationalNavigation.navigateTo(code, new CommonJurnalForm(header, JurnalTableHeaders._02_02, code, ManagerOperational.this.user), jPanel7, Nodes.DAILYCASH);
                            setButtonStatus();
                            statusGLID2.setText(GLCodes.STAMPRECEIVINGS + "");
                            break;

                        case "02-03":
                            ManagerOperationalNavigation.navigateTo(code, new CommonJurnalForm(header, JurnalTableHeaders._02_03, code, ManagerOperational.this.user), jPanel7, Nodes.DAILYCASH);
                            setButtonStatus();
                            statusGLID2.setText(GLCodes.CASHTIES + "");
                            break;

                        case "02-04":
                            ManagerOperationalNavigation.navigateTo(code, new CommonJurnalForm(header, JurnalTableHeaders._02_04, code, ManagerOperational.this.user), jPanel7, Nodes.DAILYCASH);
                            setButtonStatus();
                            statusGLID2.setText(GLCodes.STAMPTIES + "");
                            break;

                        case "03-01":
                            ManagerOperationalNavigation.navigateTo(code, new CommonJurnalForm(header, JurnalTableHeaders._03, GLCodes.PURCHASES, code, user), jPanel7, GLCodes.PURCHASES);
                            setButtonStatus();
                            statusGLID2.setText(GLCodes.PURCHASES + "");
                            break;
                        case "03-02":
                            ManagerOperationalNavigation.navigateTo(code, new CommonJurnalForm(header, JurnalTableHeaders._03, GLCodes.CREDITORSPAYMENTS, code, user), jPanel7, GLCodes.CREDITORSPAYMENTS);
                            setButtonStatus();
                            statusGLID2.setText(GLCodes.CREDITORSPAYMENTS + "");
                            break;

                        case "03-03":
                            ManagerOperationalNavigation.navigateTo(code, new CommonJurnalForm(header, JurnalTableHeaders._03, GLCodes.OTHERPAYMENTS, code, user), jPanel7, GLCodes.OTHERPAYMENTS);
                            setButtonStatus();
                            statusGLID2.setText(GLCodes.OTHERPAYMENTS + "");
                            break;

                        case "03-04":
                            ManagerOperationalNavigation.navigateTo(code, new CommonJurnalForm(header, JurnalTableHeaders._03, GLCodes.ADVANCEPURCHASES, code, user), jPanel7, GLCodes.ADVANCEPURCHASES);
                            setButtonStatus();
                            statusGLID2.setText(GLCodes.ADVANCEPURCHASES + "");
                            break;

                        case "03-05":
                            ManagerOperationalNavigation.navigateTo(code, new CommonJurnalForm(header, JurnalTableHeaders._03, GLCodes.OTHERADVANCES, code, user), jPanel7, GLCodes.OTHERADVANCES);
                            setButtonStatus();
                            statusGLID2.setText(GLCodes.OTHERADVANCES + "");
                            break;

                        case "03-06":
                            ManagerOperationalNavigation.navigateTo(code, new CommonJurnalForm(header, JurnalTableHeaders._03, GLCodes.LOANPAYMENTS, code, user), jPanel7, GLCodes.LOANPAYMENTS);
                            setButtonStatus();
                            statusGLID2.setText(GLCodes.LOANPAYMENTS + "");
                            break;

                        case "03-07":
                            ManagerOperationalNavigation.navigateTo(code, new CommonJurnalForm(header, JurnalTableHeaders._03, GLCodes.DEPOSITPAYMENTS, code, user), jPanel7, GLCodes.DEPOSITPAYMENTS);
                            setButtonStatus();
                            statusGLID2.setText(GLCodes.DEPOSITPAYMENTS + "");
                            break;

                        case "03-08":
                            ManagerOperationalNavigation.navigateTo(code, new CommonJurnalForm(header, JurnalTableHeaders._03_08, GLCodes.NOGLCODE, code, user), jPanel7, Nodes.SAVINGSACCOUNTSCREDITS);
                            setButtonStatus();
                            break;

                        case "04-01":
//                            System.out.println("user level is "+user.getLevel());
//                            if (user.getLevel() == AccessLevels.CHEQUE) {
                            ManagerOperationalNavigation.navigateTo(code, new CommonJurnalForm(header, JurnalTableHeaders._04_01, code, user), jPanel7, Nodes.DAILYCASH);
                            setButtonStatus();
                            statusGLID2.setText(GLCodes.NOGLCODE + "");
                            break;
//                            } else {
//                                JOptionPane.showMessageDialog(null, "ඔබට අවසර නොමැත", "ඔබට අවසර නොමැත", JOptionPane.ERROR_MESSAGE);
//                                break;
//                            }

                        case "04-02":
                            ManagerOperationalNavigation.navigateTo(code, new CommonJurnalForm(header, JurnalTableHeaders._04_02, code, user), jPanel7, Nodes.DAILYCASH);
                            setButtonStatus();
                            statusGLID2.setText(GLCodes.NOGLCODE + "");
                            break;

                        case "04-03":
                            ManagerOperationalNavigation.navigateTo(code, new CommonJurnalForm(header, user), jPanel7, Nodes.DAILYCASH);
                            setButtonStatus();
                            statusGLID2.setText(GLCodes.DEPOSITPAYMENTS + "");
                            break;

                        case "04-04":
                            ManagerOperationalNavigation.navigateTo(code, new CommonJurnalForm(header, user), jPanel7, Nodes.DAILYCASH);
                            setButtonStatus();
                            statusGLID2.setText(GLCodes.DEPOSITPAYMENTS + "");
                            break;

                        case "04-05":
                            ManagerOperationalNavigation.navigateTo(code, new CommonJurnalForm(header, user), jPanel7, Nodes.DAILYCASH);
                            setButtonStatus();
                            statusGLID2.setText(GLCodes.DEPOSITPAYMENTS + "");
                            break;

                        case "04-06":
                            ManagerOperationalNavigation.navigateTo(code, new CommonJurnalForm(header, user), jPanel7, Nodes.DAILYCASH);
                            setButtonStatus();
                            statusGLID2.setText(GLCodes.DEPOSITPAYMENTS + "");
                            break;

                        case "04-07":
                            ManagerOperationalNavigation.navigateTo(code, new CommonJurnalForm(header, user), jPanel7, Nodes.DAILYCASH);
                            setButtonStatus();
                            statusGLID2.setText(GLCodes.DEPOSITPAYMENTS + "");
                            break;

                        case "04-08":
                            ManagerOperationalNavigation.navigateTo(code, new CommonJurnalForm(header, user), jPanel7, Nodes.DAILYCASH);
                            setButtonStatus();
                            statusGLID2.setText(GLCodes.DEPOSITPAYMENTS + "");
                            break;

                        case "05-01":
                            ManagerOperationalNavigation.navigateTo(code, new CommonJurnalForm(header, JurnalTableHeaders._05, GLCodes.DRNOTE, code, user), jPanel7, GLCodes.DRNOTE);
                            setButtonStatus();
                            statusGLID2.setText(GLCodes.DRNOTE + "");
                            break;

                        case "05-02":
                            ManagerOperationalNavigation.navigateTo(code, new CommonJurnalForm(header, JurnalTableHeaders._05, GLCodes.CRNOTE, code, user), jPanel7, GLCodes.CRNOTE);
                            setButtonStatus();
                            statusGLID2.setText(GLCodes.CRNOTE + "");
                            break;

                        case "05-03":
                            ManagerOperationalNavigation.navigateTo(code, new CommonJurnalForm(header, JurnalTableHeaders._05, GLCodes.BANKDRNOTE, code, user), jPanel7, GLCodes.BANKDRNOTE);
                            setButtonStatus();
                            statusGLID2.setText(GLCodes.BANKDRNOTE + "");
                            break;
                        case "05-04":
                            ManagerOperationalNavigation.navigateTo(code, new CommonJurnalForm(header, JurnalTableHeaders._05, GLCodes.BANKCRNOTE, code, user), jPanel7, GLCodes.BANKCRNOTE);
                            setButtonStatus();
                            statusGLID2.setText(GLCodes.BANKCRNOTE + "");
                            break;
                        case "05-05":
                            ManagerOperationalNavigation.navigateTo(code, new CommonJurnalForm(header, JurnalTableHeaders._05, GLCodes.COMMONDRNOTE, code, user), jPanel7, GLCodes.COMMONDRNOTE);
                            setButtonStatus();
                            statusGLID2.setText(GLCodes.COMMONDRNOTE + "");
                            break;
                        case "05-06":
                            ManagerOperationalNavigation.navigateTo(code, new CommonJurnalForm(header, JurnalTableHeaders._05, GLCodes.COMMONCRNOTE, code, user), jPanel7, GLCodes.COMMONCRNOTE);
                            setButtonStatus();
                            statusGLID2.setText(GLCodes.COMMONCRNOTE + "");
                            break;
                        case "06-01":
                            FindSectionOrOutsider sectionOrOutsider1 = new FindSectionOrOutsider(TableHeaders.SECTIONFINDER_TABLE_MODEL, TableHeaders.SECTIONFINDER_TABLE_MODEL2, 100, header);
                            ManagerOperationalNavigation.navigateTo(code, sectionOrOutsider1.jPanel1, jPanel7, Nodes.DAILYCASH);
                            setButtonStatus();
                            statusGLID2.setText(GLCodes.NOGLCODE + "");
                            break;
                        case "06-02":
                            FindSectionOrOutsider sectionOrOutsider2 = new FindSectionOrOutsider(TableHeaders.PERFORMANCEAPPRAISALSECTIONFINDER_TABLE_MODEL, TableHeaders.PERFORMANCEAPPRAISALSECTIONFINDER_TABLE_MODEL2, 100, header);
                            ManagerOperationalNavigation.navigateTo(code, sectionOrOutsider2.jPanel1, jPanel7, Nodes.DAILYCASH);
                            setButtonStatus();
                            statusGLID2.setText(GLCodes.NOGLCODE + "");
                            break;
                        case "06-03":
                            FindSectionOrOutsider sectionOrOutsider3 = new FindSectionOrOutsider(TableHeaders.SUBSECTIONFINDER_TABLE_MODEL, TableHeaders.SUBSECTIONFINDER_TABLE_MODEL2, 100, header);
                            ManagerOperationalNavigation.navigateTo(code, sectionOrOutsider3.jPanel1, jPanel7, Nodes.DAILYCASH);
                            setButtonStatus();
                            statusGLID2.setText(GLCodes.NOGLCODE + "");
                            break;
                        case "06-04":
                            FindSectionOrOutsider sectionOrOutsider4 = new FindSectionOrOutsider(TableHeaders.OUTSIDERFINDER_TABLE_MODEL, TableHeaders.OUTSIDERFINDER_TABLE_MODEL2, 101, header);
                            ManagerOperationalNavigation.navigateTo(code, sectionOrOutsider4.jPanel1, jPanel7, Nodes.DAILYCASH);
                            setButtonStatus();
                            statusGLID2.setText(GLCodes.NOGLCODE + "");
                            break;

                        case "06-05":
                            FindSectionOrOutsider sectionOrOutsider5 = new FindSectionOrOutsider(TableHeaders.OUTSIDERTYPEFINDER_TABLE_MODEL, TableHeaders.OUTSIDERTYPEFINDER_TABLE_MODEL2, 102, header);
                            ManagerOperationalNavigation.navigateTo(code, sectionOrOutsider5.jPanel1, jPanel7, Nodes.DAILYCASH);
                            setButtonStatus();
                            statusGLID2.setText(GLCodes.NOGLCODE + "");
                            break;

                        case "06-06":
                            FindSectionOrOutsider sectionOrOutsider6 = new FindSectionOrOutsider(TableHeaders.REASON_TABLE_MODEL, TableHeaders.REASON_TABLE_MODEL2, 102, header, "ALL");
                            ManagerOperationalNavigation.navigateTo(code, sectionOrOutsider6.jPanel1, jPanel7, Nodes.DAILYCASH);
                            setButtonStatus();
                            statusGLID2.setText(GLCodes.NOGLCODE + "");
                            break;

                        case "06-07":
                            java.awt.Container c = ManagerOperational.this.getParent();
                            while (!(c instanceof javax.swing.JFrame) && (c != null)) {
                                c = c.getParent();
                            }
                            JFrame owner = null;
                            if (c != null) {
                                owner = (javax.swing.JFrame) c;

                            }
                            FindAccount5Data account5Data = new FindAccount5Data(owner, true, 0);
                            account5Data.setVisible(true);
                            EmptyPanel emptyPanel3 = new EmptyPanel();
                            ManagerOperationalNavigation.navigateTo(emptyPanel3, jPanel7);
                            setButtonStatus();
                            statusGLID2.setText(GLCodes.NOGLCODE + "");
                            break;
                        case "07-01":
                            ManagerOperationalNavigation.navigateTo(code, new CommonJurnalForm(header, JurnalTableHeaders._07_01, code, user), jPanel7, Nodes.DAILYCASH);
                            setButtonStatus();
                            statusGLID2.setText(GLCodes.RURALBANK9E + "");
                            break;
                        case "08-01":
                            ManagerOperationalNavigation.navigateTo(code, new CommonJurnalForm(header, JurnalTableHeaders._05, GLCodes.COMMONADMINDR, code, user), jPanel7, GLCodes.COMMONADMINDR);
                            setButtonStatus();
                            statusGLID2.setText(GLCodes.COMMONADMINDR + "");
                            break;
                        case "08-02":
                            ManagerOperationalNavigation.navigateTo(code, new CommonJurnalForm(header, JurnalTableHeaders._05, GLCodes.COMMONADMINCR, code, user), jPanel7, GLCodes.COMMONADMINCR);
                            setButtonStatus();
                            statusGLID2.setText(GLCodes.COMMONADMINCR + "");
                            break;
                        case "08-03":
                            ManagerOperationalNavigation.navigateTo(code, new CommonJurnalForm(header, JurnalTableHeaders._05, GLCodes.COMMONEXPENCEMATCHDR, code, user), jPanel7, GLCodes.COMMONEXPENCEMATCHDR);
                            setButtonStatus();
                            statusGLID2.setText(GLCodes.COMMONEXPENCEMATCHDR + "");
                            break;
                        case "08-04":
                            ManagerOperationalNavigation.navigateTo(code, new CommonJurnalForm(header, JurnalTableHeaders._05, GLCodes.COMMONEXPENCEMATCHCR, code, user), jPanel7, GLCodes.COMMONEXPENCEMATCHCR);
                            setButtonStatus();
                            statusGLID2.setText(GLCodes.COMMONEXPENCEMATCHCR + "");
                            break;
                        case "10-02":
                            ManagerOperationalNavigation.navigateTo(code, new CommonJurnalForm(header, JurnalTableHeaders._10_02, code, user), jPanel7, Nodes.DAILYCASH);
                            setButtonStatus();
                            statusGLID2.setText(GLCodes.NOGLCODE + "");
                            break;
                        case "10-03":
                            ManagerOperationalNavigation.navigateTo(code, new CommonJurnalForm(header, JurnalTableHeaders._10_03, code, user), jPanel7, Nodes.DAILYCASH);
                            setButtonStatus();
                            statusGLID2.setText(GLCodes.NOGLCODE + "");
                            break;
                        case "12-01":
                            ManagerOperationalNavigation.navigateTo(new ReportsPanel(), jPanel7);
                            setButtonStatus();
                            statusGLID2.setText(GLCodes.NOGLCODE + "");
                            break;
                        case "12-02":
                            ManagerOperationalNavigation.navigateTo(new FinancialYearCompletedMonths(), jPanel7);
                            setButtonStatus();
                            statusGLID2.setText(GLCodes.NOGLCODE + "");
                            break;
                        default:
                            EmptyPanel emptyPanel2 = new EmptyPanel();
                            ManagerOperationalNavigation.navigateTo(emptyPanel2, jPanel7);
                            setButtonStatus();
                            break;
                    }
                }
            }

            private void setButtonStatus() {
                if (!ManagerOperational.this.user.isAddable()) {
                    CommonJurnalForm.itemNewVoucher.setEnabled(false);
                    CommonJurnalForm.itemNewCashier.setEnabled(false);
                    CommonJurnalForm.itemNewJournal.setEnabled(false);
                    CommonJurnalForm.itemNewRB.setEnabled(false);
                    CommonJurnalForm.itemNewStock.setEnabled(false);
                }
                if (!ManagerOperational.this.user.isEditable()) {
                    CommonJurnalForm.itemEditVoucher.setEnabled(false);
                    CommonJurnalForm.itemEditCashier.setEnabled(false);
                    CommonJurnalForm.itemEditJournal.setEnabled(false);
                    CommonJurnalForm.itemEditRB.setEnabled(false);
                    CommonJurnalForm.itemEditStock.setEnabled(false);
                }
            }
        });

    }

    private void defTree() {

        DefaultTreeModel model = (DefaultTreeModel) jTree1.getModel();
        DefaultMutableTreeNode root = (DefaultMutableTreeNode) model.getRoot();

        TreeGen gen = new TreeGen();
        gen.generateTree(jTree1, acessLevel);

//finally call
        model.reload(root);
//        CommonJurnalFormComponentStateSave stateSave = new CommonJurnalFormComponentStateSave();
    }

}
